/**
 * The server-function demos' whole styling: one palette, the theme on `:root`,
 * and the sheets every demo page shares.
 *
 * Each demo used to carry its own copy of the same CSS — a dark theme, then a
 * light one written after it that won the cascade everywhere. What rendered was
 * the light one; it is the default here, and the dark one is back as what it
 * always wanted to be: the `scheme.dark` side of the theme variables.
 */
import {
  alignItems,
  ariaCurrent,
  at,
  bg,
  blockSize,
  borderBlockEndColor,
  borderBlockEndStyle,
  borderBlockEndWidth,
  borderColor,
  borderStyle,
  borderWidth,
  clipOverflow,
  color,
  craftGlobalStyles,
  craftStyles,
  cssString,
  cssVars,
  cursor,
  darkOf,
  defineBreakpoints,
  definePalette,
  defineStateAxis,
  display,
  flex,
  flexShrink,
  flexWrap,
  font,
  fontFamily,
  fontSize,
  fontWeight,
  gap,
  gridTemplateColumns,
  inlineSize,
  interaction,
  justifyContent,
  kind,
  letterSpacing,
  lineHeight,
  lineWidth,
  listStyleType,
  marginBlock,
  marginBlockEnd,
  marginBlockStart,
  marginInline,
  marginInlineEnd,
  math,
  maxInlineSize,
  minBlockSize,
  minWidth,
  monospaceStack,
  num,
  opacity,
  overflowWrap,
  p,
  placeItems,
  pseudo,
  px,
  py,
  radii,
  radius,
  scheme,
  set,
  shadow,
  space,
  systemUiStack,
  text,
  textAlign,
  textDecorationLine,
  textOverflow,
  textTransform,
  tracks,
  unit,
  when,
  whiteSpace,
} from '@craft-ts/style';

const demo = definePalette('serverDemo', {
  surface: {
    page: { light: '#f6f7fb', dark: '#0b1020' },
    panel: { light: '#ffffff', dark: '#151f37' },
    sunken: { light: '#fafbfc', dark: '#0d162a' },
    nav: { light: '#ffffff', dark: '#11192d' },
    navHover: { light: '#f1f3f8', dark: '#1b2640' },
    accentSoft: { light: '#edf2ff', dark: '#263c73' },
    accentFaint: { light: '#f5f7ff', dark: '#1b2a52' },
    button: { light: '#4665c4', dark: '#9fb5ff' },
    buttonHover: { light: '#3855ad', dark: '#b4c6ff' },
    danger: { light: '#b8505a', dark: '#a94f55' },
    dangerHover: { light: '#9e414b', dark: '#c0626a' },
    error: { light: '#fff5f5', dark: '#42252e' },
    success: { light: '#4a9b73', dark: '#52e2ae' },
  },
  text: {
    strong: { light: '#172033', dark: '#f5f7ff' },
    body: { light: '#344057', dark: '#dce5f8' },
    copy: { light: '#5f6a80', dark: '#aab6cf' },
    muted: { light: '#6b7488', dark: '#8f9cb8' },
    accent: { light: '#4a64b8', dark: '#8da8ff' },
    accentStrong: { light: '#3159c8', dark: '#a9bbff' },
    onButton: { light: '#ffffff', dark: '#0b1020' },
    onDanger: { light: '#ffffff', dark: '#ffffff' },
    error: { light: '#9e414b', dark: '#ffd7d0' },
    success: { light: '#3b7d5c', dark: '#b5f0d0' },
  },
  border: {
    panel: { light: '#e2e6ef', dark: '#293655' },
    subtle: { light: '#e3e7ef', dark: '#2d3d61' },
    input: { light: '#c9cfdc', dark: '#3a4a70' },
    focus: { light: '#7991df', dark: '#89a4ff' },
    accent: { light: '#d8e0f7', dark: '#384a75' },
    error: { light: '#edc5c8', dark: '#a94f55' },
    nav: { light: '#e5e8f0', dark: '#273351' },
  },
  effect: {
    shadow: { light: '#25345a0a', dark: '#00000033' },
    focusGlow: { light: '#5570c71c', dark: '#89a4ff22' },
  },
});

const themed = { inherits: true };

/** One theme variable per palette entry, light by default. */
const tone = cssVars('serverDemo', {
  page: kind.color(demo.surface.page, themed),
  panel: kind.color(demo.surface.panel, themed),
  sunken: kind.color(demo.surface.sunken, themed),
  nav: kind.color(demo.surface.nav, themed),
  navHover: kind.color(demo.surface.navHover, themed),
  accentSoft: kind.color(demo.surface.accentSoft, themed),
  accentFaint: kind.color(demo.surface.accentFaint, themed),
  button: kind.color(demo.surface.button, themed),
  buttonHover: kind.color(demo.surface.buttonHover, themed),
  danger: kind.color(demo.surface.danger, themed),
  dangerHover: kind.color(demo.surface.dangerHover, themed),
  errorSurface: kind.color(demo.surface.error, themed),
  successDot: kind.color(demo.surface.success, themed),
  strong: kind.color(demo.text.strong, themed),
  body: kind.color(demo.text.body, themed),
  copy: kind.color(demo.text.copy, themed),
  muted: kind.color(demo.text.muted, themed),
  accent: kind.color(demo.text.accent, themed),
  accentStrong: kind.color(demo.text.accentStrong, themed),
  onButton: kind.color(demo.text.onButton, themed),
  onDanger: kind.color(demo.text.onDanger, themed),
  errorText: kind.color(demo.text.error, themed),
  successText: kind.color(demo.text.success, themed),
  panelBorder: kind.color(demo.border.panel, themed),
  subtleBorder: kind.color(demo.border.subtle, themed),
  inputBorder: kind.color(demo.border.input, themed),
  focusBorder: kind.color(demo.border.focus, themed),
  accentBorder: kind.color(demo.border.accent, themed),
  errorBorder: kind.color(demo.border.error, themed),
  navBorder: kind.color(demo.border.nav, themed),
  shadow: kind.color(demo.effect.shadow, themed),
  focusGlow: kind.color(demo.effect.focusGlow, themed),
});

craftGlobalStyles('serverDemo', {
  root: [
    when(scheme.dark, [
      set(tone.page, darkOf(demo.surface.page)),
      set(tone.panel, darkOf(demo.surface.panel)),
      set(tone.sunken, darkOf(demo.surface.sunken)),
      set(tone.nav, darkOf(demo.surface.nav)),
      set(tone.navHover, darkOf(demo.surface.navHover)),
      set(tone.accentSoft, darkOf(demo.surface.accentSoft)),
      set(tone.accentFaint, darkOf(demo.surface.accentFaint)),
      set(tone.button, darkOf(demo.surface.button)),
      set(tone.buttonHover, darkOf(demo.surface.buttonHover)),
      set(tone.danger, darkOf(demo.surface.danger)),
      set(tone.dangerHover, darkOf(demo.surface.dangerHover)),
      set(tone.errorSurface, darkOf(demo.surface.error)),
      set(tone.successDot, darkOf(demo.surface.success)),
      set(tone.strong, darkOf(demo.text.strong)),
      set(tone.body, darkOf(demo.text.body)),
      set(tone.copy, darkOf(demo.text.copy)),
      set(tone.muted, darkOf(demo.text.muted)),
      set(tone.accent, darkOf(demo.text.accent)),
      set(tone.accentStrong, darkOf(demo.text.accentStrong)),
      set(tone.onButton, darkOf(demo.text.onButton)),
      set(tone.errorText, darkOf(demo.text.error)),
      set(tone.successText, darkOf(demo.text.success)),
      set(tone.panelBorder, darkOf(demo.border.panel)),
      set(tone.subtleBorder, darkOf(demo.border.subtle)),
      set(tone.inputBorder, darkOf(demo.border.input)),
      set(tone.focusBorder, darkOf(demo.border.focus)),
      set(tone.accentBorder, darkOf(demo.border.accent)),
      set(tone.errorBorder, darkOf(demo.border.error)),
      set(tone.navBorder, darkOf(demo.border.nav)),
      set(tone.shadow, darkOf(demo.effect.shadow)),
      set(tone.focusGlow, darkOf(demo.effect.focusGlow)),
    ]),
  ],
  elements: {
    body: [
      minWidth(unit.px(320)),
      fontFamily(systemUiStack),
      bg(tone.page),
      color(tone.strong),
    ],
  },
});

/** `wide`: two columns. `roomy`: a panel wide enough for a row of controls. */
const bp = defineBreakpoints({
  roomy: at.minInlineSize(unit.rem(29.5)),
  wide: at.minInlineSize(unit.rem(48.75)),
});

const hairline = (tint: typeof tone.panelBorder) => [
  borderWidth(lineWidth.hairline),
  borderStyle.solid,
  borderColor(tint),
];

const kicker = [
  font(text.xs),
  fontWeight(num(800)),
  letterSpacing(unit.em(0.14)),
  textTransform.uppercase,
  color(tone.accent),
];

/** One column that may shrink below its content — the grid's `auto` may not. */
const shrinkableColumn = gridTemplateColumns(
  tracks.list(tracks.minmax(space(0), tracks.fr(1))),
);

const ellipsis = [
  display.block,
  clipOverflow.inline,
  textOverflow.ellipsis,
  whiteSpace.nowrap,
];

/** The top bar that links the demos. */
export const demoNav = craftStyles('serverDemoNav', {
  root: [display.block, minBlockSize(unit.vh(100))],
  bar: [
    display.flex,
    flexWrap.wrap,
    alignItems.center,
    gap(space(2)),
    py(space(3)),
    px(math.max(unit.px(20), unit.vw(4))),
    borderBlockEndWidth(lineWidth.hairline),
    borderBlockEndStyle.solid,
    borderBlockEndColor(tone.navBorder),
    bg(tone.nav),
    pseudo.before([
      pseudo.content.text(cssString('Server Functions')),
      inlineSize(unit.pct(100)),
      marginBlockEnd(space(1)),
      font(text.sm),
      fontWeight(num(800)),
      color(tone.strong),
      when(bp.roomy, [
        inlineSize.auto,
        marginBlockEnd(space(0)),
        marginInlineEnd(space(4)),
      ]),
    ]),
  ],
  link: [
    py(space(2)),
    px(space(3)),
    radius(radii.lg),
    font(text.xs),
    fontWeight(num(650)),
    color(tone.copy),
    textDecorationLine.none,
    when(interaction.hover, [color(tone.strong), bg(tone.navHover)]),
    when(ariaCurrent.page, [color(tone.accentStrong), bg(tone.accentSoft)]),
  ],
});

/** Which button: the default action, or one that triggers a failure. */
export const buttonTone = defineStateAxis('demoButton', ['danger']);

/** The layout and the pieces every demo page shares. */
export const demoPage = craftStyles('serverDemoPage', {
  shell: [
    maxInlineSize(unit.rem(66.25)),
    marginInline.auto,
    px(space(4)),
    py(space(10)),
    when(bp.wide, [px(space(5)), py(space(12))]),
  ],
  hero: [maxInlineSize(unit.rem(47.5))],
  eyebrow: [...kicker, display.flex, alignItems.center, gap(space(2))],
  pulse: [
    inlineSize(unit.px(8)),
    blockSize(unit.px(8)),
    radius(radii.full),
    bg(tone.successDot),
  ],
  title: [
    marginBlock(space(3)),
    fontSize(math.clamp(unit.rem(2.1), unit.vw(5), unit.rem(3.7))),
    fontWeight(num(700)),
    lineHeight(num(1.02)),
    letterSpacing(unit.em(-0.065)),
    color(tone.strong),
  ],
  heroCopy: [font(text.lg), color(tone.copy)],
  workspace: [
    display.grid,
    shrinkableColumn,
    gap(space(4)),
    marginBlockStart(space(10)),
    when(bp.wide, [
      gridTemplateColumns(
        tracks.list(
          tracks.minmax(space(0), tracks.fr(0.92)),
          tracks.minmax(space(0), tracks.fr(1.08)),
        ),
      ),
    ]),
  ],
  panel: [
    minBlockSize(unit.rem(20)),
    p(space(5)),
    ...hairline(tone.panelBorder),
    radius(unit.rem(1)),
    bg(tone.panel),
    shadow({ y: unit.px(10), blur: unit.px(28), color: tone.shadow }),
    when(bp.roomy, [p(space(6))]),
  ],
  panelHeading: [
    display.block,
    when(bp.roomy, [
      display.flex,
      alignItems.flexStart,
      justifyContent.spaceBetween,
      gap(space(4)),
    ]),
  ],
  kicker: [...kicker, display.block],
  panelTitle: [
    marginBlockStart(space(1)),
    font(text.lg),
    fontWeight(num(700)),
    letterSpacing(unit.em(-0.025)),
    color(tone.strong),
  ],
  mono: [
    display.inlineBlock,
    marginBlockStart(space(3)),
    py(space(1)),
    px(space(2)),
    ...hairline(tone.accentBorder),
    radius(radii.lg),
    fontSize(unit.rem(0.68)),
    fontFamily(monospaceStack),
    whiteSpace.nowrap,
    color(tone.accent),
    bg(tone.accentFaint),
    when(bp.roomy, [marginBlockStart(space(0))]),
  ],
  copy: [
    marginBlock(space(4)),
    font(text.sm),
    lineHeight(num(1.55)),
    color(tone.copy),
  ],
  label: [
    display.block,
    marginBlockEnd(space(2)),
    font(text.xs),
    fontWeight(num(700)),
    color(tone.body),
  ],
  spacedLabel: [marginBlockStart(space(6))],
  searchRow: [display.grid, gap(space(2)), when(bp.roomy, [display.flex])],
  input: [
    inlineSize(unit.pct(100)),
    minWidth(space(0)),
    py(space(3)),
    px(space(3)),
    ...hairline(tone.inputBorder),
    radius(radii.lg),
    color(tone.strong),
    bg(tone.panel),
    when(interaction.focus, [
      borderColor(tone.focusBorder),
      shadow({
        y: space(0),
        blur: space(0),
        spread: unit.px(3),
        color: tone.focusGlow,
      }),
    ]),
  ],
  button: [
    minBlockSize(unit.px(44)),
    px(space(4)),
    borderStyle.none,
    radius(radii.lg),
    fontWeight(num(800)),
    whiteSpace.nowrap,
    cursor.pointer,
    color(tone.onButton),
    bg(tone.button),
    when(interaction.hover, [bg(tone.buttonHover)]),
    when(buttonTone.danger, [
      color(tone.onDanger),
      bg(tone.danger),
      when(interaction.hover, [bg(tone.dangerHover)]),
    ]),
    when(interaction.disabled, [cursor.wait, opacity(num(0.6))]),
    when(bp.roomy, [minBlockSize(unit.px(38))]),
  ],
  actions: [
    display.flex,
    flexWrap.wrap,
    gap(space(2)),
    marginBlockStart(space(4)),
  ],
  requestCard: [
    display.flex,
    alignItems.flexStart,
    gap(space(3)),
    marginBlockStart(space(10)),
    p(space(3)),
    ...hairline(tone.subtleBorder),
    radius(radii.xl),
    bg(tone.sunken),
  ],
  requestDot: [
    flexShrink(num(0)),
    inlineSize(unit.px(8)),
    blockSize(unit.px(8)),
    marginBlockStart(unit.px(6)),
    radius(radii.full),
    bg(tone.successDot),
  ],
  requestTitle: [display.block, font(text.xs), color(tone.body)],
  requestDetail: [
    display.block,
    marginBlockStart(space(1)),
    font(text.xs),
    color(tone.muted),
  ],
  status: [
    marginBlockStart(space(6)),
    p(space(3)),
    ...hairline(tone.subtleBorder),
    radius(radii.xl),
    font(text.xs),
    color(tone.copy),
    bg(tone.sunken),
  ],
  error: [
    marginBlockStart(space(4)),
    p(space(3)),
    ...hairline(tone.errorBorder),
    radius(radii.xl),
    font(text.xs),
    fontFamily(monospaceStack),
    overflowWrap.anywhere,
    color(tone.errorText),
    bg(tone.errorSurface),
  ],
  loading: [
    marginBlockStart(space(6)),
    marginBlockEnd(space(2)),
    py(space(3)),
    px(space(3)),
    ...hairline(tone.accentBorder),
    radius(radii.lg),
    font(text.xs),
    color(tone.accent),
    bg(tone.accentFaint),
  ],
  countBadge: [
    minWidth(unit.px(27)),
    py(space(1)),
    px(space(2)),
    radius(radii.full),
    font(text.xs),
    fontFamily(monospaceStack),
    fontWeight(num(700)),
    textAlign.center,
    color(tone.accentStrong),
    bg(tone.accentSoft),
  ],
  results: [
    display.grid,
    shrinkableColumn,
    gap(space(2)),
    marginBlockStart(space(6)),
    p(space(0)),
    listStyleType.none,
  ],
  row: [
    display.flex,
    alignItems.center,
    gap(space(3)),
    p(space(3)),
    ...hairline(tone.subtleBorder),
    radius(radii.xl),
    bg(tone.panel),
  ],
  avatar: [
    display.grid,
    placeItems.center,
    inlineSize(unit.px(38)),
    blockSize(unit.px(38)),
    radius(radii.xl),
    fontWeight(num(900)),
    color(tone.accentStrong),
    bg(tone.accentSoft),
  ],
  rowInfo: [flex(num(1)), minWidth(space(0))],
  rowName: [...ellipsis, font(text.sm), color(tone.strong)],
  rowMeta: [
    ...ellipsis,
    marginBlockStart(unit.px(2)),
    font(text.xs),
    color(tone.muted),
  ],
  rowId: [font(text.xs), fontFamily(monospaceStack), color(tone.muted)],
  price: [
    font(text.xs),
    fontFamily(monospaceStack),
    fontWeight(num(700)),
    color(tone.successText),
  ],
  empty: [
    display.grid,
    placeItems.center,
    minBlockSize(unit.rem(11)),
    p(space(4)),
    borderWidth(lineWidth.hairline),
    borderStyle.dashed,
    borderColor(tone.inputBorder),
    radius(radii.xl),
    textAlign.center,
    color(tone.muted),
  ],
  emptyTitle: [display.block, font(text.sm), color(tone.body)],
  emptyText: [display.block, marginBlockStart(space(1)), font(text.xs)],
  payload: [
    display.grid,
    shrinkableColumn,
    gap(space(2)),
    marginBlockStart(space(6)),
    p(space(3)),
    ...hairline(tone.subtleBorder),
    radius(radii.xl),
    bg(tone.sunken),
  ],
  payloadStep: [
    display.grid,
    shrinkableColumn,
    gap(space(1)),
    alignItems.baseline,
    when(bp.roomy, [
      gridTemplateColumns(
        tracks.list(
          unit.rem(8.5),
          unit.rem(9.5),
          tracks.minmax(space(0), tracks.fr(1)),
        ),
      ),
      gap(space(3)),
    ]),
  ],
  payloadLayer: [
    fontSize(unit.rem(0.68)),
    fontFamily(monospaceStack),
    fontWeight(num(700)),
    color(tone.accent),
  ],
  payloadKey: [font(text.xs), fontFamily(monospaceStack), color(tone.muted)],
  payloadValue: [
    ...ellipsis,
    font(text.xs),
    fontFamily(monospaceStack),
    color(tone.body),
  ],
  footer: [
    display.block,
    marginBlockStart(space(6)),
    font(text.xs),
    color(tone.muted),
    when(bp.roomy, [display.flex, justifyContent.spaceBetween, gap(space(3))]),
  ],
  footerFile: [
    display.block,
    marginBlockStart(space(1)),
    fontFamily(monospaceStack),
    when(bp.roomy, [display.inline, marginBlockStart(space(0))]),
  ],
});

/** Which status-page link: the way forward, or the way back. */
export const linkTone = defineStateAxis('statusLink', ['secondary']);

/** The 404 / error pages of the demo. */
export const statusPage = craftStyles('serverDemoStatus', {
  root: [
    display.grid,
    placeItems.center,
    minBlockSize(unit.vh(70)),
    py(space(12)),
    px(space(5)),
  ],
  card: [
    inlineSize(math.min(unit.px(620), unit.pct(100))),
    p(space(8)),
    ...hairline(tone.panelBorder),
    radius(unit.rem(1.1)),
    bg(tone.panel),
    shadow({ y: unit.px(14), blur: unit.px(34), color: tone.shadow }),
  ],
  eyebrow: [...kicker, display.block, marginBlockEnd(space(3))],
  title: [
    fontSize(math.clamp(unit.rem(2), unit.vw(5), unit.rem(3.2))),
    fontWeight(num(700)),
    lineHeight(num(1.02)),
    letterSpacing(unit.em(-0.05)),
    color(tone.strong),
  ],
  message: [
    marginBlockStart(space(4)),
    font(text.base),
    lineHeight(num(1.6)),
    color(tone.copy),
  ],
  detail: [marginBlockStart(space(3)), font(text.sm), color(tone.muted)],
  actions: [
    display.flex,
    flexWrap.wrap,
    gap(space(3)),
    marginBlockStart(space(8)),
  ],
  link: [
    py(space(3)),
    px(space(4)),
    radius(radii.lg),
    font(text.sm),
    fontWeight(num(800)),
    textDecorationLine.none,
    color(tone.onButton),
    bg(tone.button),
    when(interaction.hover, [bg(tone.buttonHover)]),
    when(linkTone.secondary, [color(tone.accentStrong), bg(tone.accentSoft)]),
  ],
});
