// Generated. Do not edit.
export const architectureCatalog = {
  "version": 1,
  "graphHash": "0f15e4c567436960",
  "routes": [],
  "services": [
    "AiContextMenuController",
    "AppSnapshotRegistry",
    "BrowserCryptoService",
    "BrowserDocumentService",
    "BrowserHistoryService",
    "BrowserLocationService",
    "BrowserNavigatorService",
    "BrowserPerformanceService",
    "BrowserWindowService",
    "ComponentMonitoring",
    "ConsoleService",
    "CookiesService",
    "CorrelationIdService",
    "CraftA11yNavigationFocus",
    "CraftActivatedRoute",
    "CraftActiveRouteLoadError",
    "CraftBlankMs",
    "CraftChildMatch",
    "CraftCompiledRoutes",
    "CraftCspNonce",
    "CraftDomEventHooks",
    "CraftDynamicImport",
    "CraftErrorComponent",
    "CraftFieldCheckboxControl",
    "CraftFieldExceptionBoundary",
    "CraftFieldValueControl",
    "CraftGlobalError",
    "CraftGlobalErrorComponent",
    "CraftHistory",
    "CraftHttpTraces",
    "CraftHydrationRuntime",
    "CraftLazyLoadRetry",
    "CraftLoadingText",
    "CraftLocation",
    "CraftLogServerUrl",
    "CraftMatch",
    "CraftNodeEffectFactory",
    "CraftPendingComponent",
    "CraftPendingMinMs",
    "CraftPlatform",
    "CraftPrimitiveRegistry",
    "CraftRenderIdentity",
    "CraftRootComponent",
    "CraftRouteChainRunner",
    "CraftRouteLoadError",
    "CraftRouteLoadErrorComponent",
    "CraftRouteLoadErrorConfig",
    "CraftRouteLoadRecovery",
    "CraftRouteLoadRetry",
    "CraftRouteTarget",
    "CraftRoutedComponent",
    "CraftRouter",
    "CraftRouterRuntime",
    "CraftRouterTraces",
    "CraftRuntimeMode",
    "CraftSchemaValidationPolicy",
    "CraftSecurityPolicy",
    "CraftSsrPolicy",
    "CraftSsrRuntime",
    "CraftStartViewTransition",
    "CraftStayMs",
    "CraftStyleRegistry",
    "CraftSyncTemplateFlush",
    "CraftTitleStrategy",
    "CraftViewTransition",
    "CraftViewTransitionSkipBlank",
    "CraftViewTransitionsEnabled",
    "DynamicEffectRefInstance",
    "DynamicResourceInstance",
    "ForScheduler",
    "GlobalPersisterHandlerService",
    "HostName",
    "InsertionSnapshotRegistry",
    "LocalStoragePersister",
    "LocalStorageService",
    "MiddlewareExecutionScope",
    "PrimitiveMethodRuntimeContext",
    "PrimitiveResourceRuntimeObservers",
    "SendContextChatActions",
    "SendContextChatComponent",
    "SendContextChatSections",
    "SendContextContextMenuComponent",
    "SendContextEventEnrichers",
    "SendContextEventFilters",
    "SendContextEventSources",
    "SendContextExportSections",
    "SendContextLauncherComponent",
    "SendContextRecordController",
    "SendContextRedactor",
    "SendContextRetentionPolicy",
    "SendContextSession",
    "SendContextToAiBuffer",
    "SendContextUiRenderer",
    "SendContextValueSerializer",
    "ServerFunctionTransport",
    "SessionStoragePersister",
    "SessionStorageService",
    "StoragePersister",
    "StorageService",
    "TakeAppSnapshot",
    "TaskRepositoryService",
    "TemplateTraces",
    "api"
  ],
  "components": [
    "AiContextMenu",
    "AiSendContextChat",
    "AiSendContextLauncher",
    "AiSendDialog",
    "AnonymousComponent@setupCraftDirectiveTemplateTestImpl/synthetic",
    "CraftRouterOutlet",
    "QuickstartTaskPage",
    "craftPending"
  ],
  "primitives": [
    "busy",
    "captureError",
    "captureInProgress",
    "copied",
    "error",
    "exception",
    "exceptionTag",
    "hasTask",
    "hasTaskException",
    "instruction",
    "panelOffset",
    "promptOptions",
    "sendContextToAi",
    "setBusy",
    "setCaptureError",
    "setCaptureInProgress",
    "setCopied",
    "setError",
    "setPanelOffset",
    "setStatus",
    "status",
    "taskQuery",
    "title"
  ],
  "sources": [
    "signalSource (signalSource)",
    "source$ (source$)"
  ],
  "serverFunctionFamilies": [],
  "httpEndpoints": [
    {
      "method": "POST",
      "url": "<unresolved:ai-send-context-chat.ts:268>"
    }
  ],
  "uniques": [],
  "providers": [],
  "routeProviders": {},
  "componentProviders": {},
  "providedOn": {},
  "collisions": {
    "services": {
      "CraftPendingComponent": [
        "libs/component/src/lib/craft-host-tokens.ts",
        "libs/core/src/lib/craft-pending.ts"
      ],
      "MiddlewareExecutionScope": [
        "libs/core/src/lib/server-function-middleware.ts",
        "libs/core/src/lib/server-function-middleware.ts"
      ],
      "TaskRepositoryService": [
        "apps/quickstart-effect/src/app/task-domain.ts",
        "apps/quickstart-effect/src/app/task-domain.ts"
      ],
      "api": [
        "libs/core/src/lib/craft-register-for.ts",
        "libs/core/src/lib/craft-service.ts"
      ]
    },
    "components": {},
    "routes": {}
  },
  "browserBoundaryServices": [
    "BrowserCryptoService",
    "BrowserDocumentService",
    "BrowserHistoryService",
    "BrowserLocationService",
    "BrowserNavigatorService",
    "BrowserPerformanceService",
    "BrowserWindowService",
    "ConsoleService",
    "CookiesService",
    "LocalStorageService",
    "SessionStorageService"
  ],
  "scopes": {}
} as const;
export type ArchitectureCatalog = typeof architectureCatalog;
