// Generated by loadDemoArchitectureGraph(). Do not edit.
export const architectureCatalog = {
  "version": 1,
  "graphHash": "946847d5c26986c4",
  "routes": [
    "",
    ":photoId",
    "component-composition",
    "content-projection",
    "craft-service/counter",
    "craft-service/register-for",
    "craft-service/user-detail",
    "craft/full-demo",
    "craft/granular-mutation",
    "craft/lazy-layout/:teamId",
    "craft/list-with-pagination",
    "craft/mutation/:userId",
    "craft/query/:userId",
    "css-vars",
    "css-vars/forwarding",
    "css-vars/inheritance",
    "css-vars/property",
    "css-vars/required",
    "debounced-web-search",
    "demo-send-context",
    "exception-query-params",
    "exceptions",
    "full-demo",
    "granular-mutation",
    "guard-demo",
    "list-with-pagination",
    "login-form",
    "mutation/:userId",
    "pending-block",
    "pending-block/exception",
    "pixel-art",
    "pixel-art-matrix",
    "playground",
    "query-params",
    "query/:userId",
    "slow-page",
    "users/:userId",
    "view-transitions"
  ],
  "services": [
    "ApiService",
    "AppStartLog",
    "Auth",
    "BrowserCryptoService",
    "BrowserDocumentService",
    "BrowserHistoryService",
    "BrowserLocationService",
    "BrowserNavigatorService",
    "BrowserPerformanceService",
    "BrowserWindowService",
    "ConsoleService",
    "CookiesService",
    "Counter",
    "GlobalPersisterHandlerService",
    "GranularMutation",
    "HostName",
    "LocalStoragePersister",
    "LocalStorageService",
    "OtherService",
    "Playground",
    "SessionStoragePersister",
    "SessionStorageService",
    "SlowAccess",
    "SlowReport",
    "StoragePersister",
    "TodoStore",
    "User",
    "UserList",
    "UserMutation",
    "UserQuery",
    "UsersApi",
    "UsersApiOnError",
    "ViewTransitionAccess",
    "api",
    "restrictedData",
    "test2"
  ],
  "components": [
    "AiContextMenu",
    "AiSendDialog",
    "AnonymousComponent@752",
    "App",
    "CounterChild",
    "CraftGlobalQuery",
    "CraftRouterOutlet",
    "CraftServiceCounterComponent",
    "CraftServiceUserDetailComponent",
    "CssVarsDemo",
    "CssVarsForwardingDemo",
    "CssVarsInheritanceDemo",
    "CssVarsPageNav",
    "CssVarsPropertyDemo",
    "CssVarsRequiredDemo",
    "DebouncedWebSearch",
    "DemoSendContextComponent",
    "ExceptionQueryParamsComponent",
    "ExceptionsComponent",
    "ForwardingExample",
    "FullDemo",
    "FullDemoCraft",
    "GlobalQuery",
    "GranularMutation",
    "GranularMutationCraft",
    "GuardDemo",
    "InheritanceExample",
    "InheritedBadge",
    "LazyLayoutChildComponent",
    "LazyLayoutComponent",
    "ListWithPagination",
    "ListWithPaginationCraft",
    "LoginFormComponent",
    "MutationCraft",
    "MutationDemoComponent",
    "MyGlobalErrorScreen",
    "MyRouteLoadErrorScreen",
    "OtherComponent",
    "PixelArt",
    "PixelArtMatrix",
    "PlaygroundComponent",
    "QpListWithPagination",
    "RegisterForDemo",
    "RegisteredMeter",
    "SendContextCounterComponent",
    "SlowPageComponent",
    "StatusComponent",
    "TokenCard",
    "ViewTransitionsDetailComponent",
    "ViewTransitionsGalleryComponent",
    "ViewTransitionsSkeletonComponent",
    "card",
    "componentCompositionDemo",
    "componentDemo",
    "contentProjectionDemo",
    "dialog",
    "lazyMessage",
    "pendingBlockDemo",
    "pendingBlockExceptionDemo",
    "restrictedContent",
    "toolbar",
    "toolbarAction",
    "userBadge",
    "userCard"
  ],
  "primitives": [
    "activeColor",
    "add",
    "addTodo",
    "auth",
    "back",
    "canReadRestrictedData",
    "cell",
    "cells",
    "childTotal",
    "clearCache",
    "copied",
    "counter",
    "counterChildIds",
    "craftComputed",
    "currentPhoto",
    "currentTerm",
    "dataList",
    "debouncedSearch",
    "deleteTodo",
    "dialogOpen",
    "disabled",
    "goTo",
    "grid",
    "hasImage",
    "hasParseException",
    "hasPhoto",
    "hasResults",
    "hasSearchError",
    "hasUser",
    "hasValue",
    "imageSrc",
    "instruction",
    "isAdding",
    "isCurrentPageResolved",
    "isDebouncing",
    "isLoading",
    "issue",
    "lastAction",
    "lastActionLabel",
    "lastHandledException",
    "loginForm",
    "message",
    "modeQueryParams",
    "nameInput",
    "navOpen",
    "navigate",
    "navigateNext",
    "navigatePrevious",
    "nextId",
    "open",
    "openLibrarySearch",
    "pagination",
    "paintCell",
    "paintedCount",
    "query",
    "records",
    "refresh",
    "remove",
    "removeTodo",
    "restriction",
    "resultBooks",
    "resultCount",
    "scenario",
    "searchInput",
    "serviceTotal",
    "setCopied",
    "setInstruction",
    "showDebouncing",
    "showEmpty",
    "showResults",
    "showSuccess",
    "showToolbar",
    "slowAccess",
    "slowReport",
    "submitted",
    "summary",
    "teams",
    "throwError",
    "titleInput",
    "todos",
    "toggleNav",
    "toggleTodo",
    "tooShort",
    "total",
    "totalPaintActions",
    "ui",
    "update",
    "updateError",
    "updatePageSize",
    "updateUserName",
    "updateUserNameFn",
    "user",
    "userExceptionLoader",
    "userId",
    "userQuery",
    "users",
    "usersQuery",
    "viewTransitionAccess"
  ],
  "sources": [
    "signalSource (signalSource)",
    "source$ (source$)"
  ],
  "httpEndpoints": [
    {
      "method": "GET",
      "url": "users"
    }
  ],
  "uniques": [
    "{\"key\":\"granular\",\"storeName\":\"demo-app\"}",
    "{\"key\":\"granular\",\"storeName\":\"demo-app-craft\"}",
    "{\"key\":\"list-with-pagination\",\"storeName\":\"demo-app\"}",
    "{\"key\":\"list-with-pagination\",\"storeName\":\"demo-app-craft\"}",
    "{\"key\":\"mutation\",\"storeName\":\"demo-app\"}",
    "{\"key\":\"mutation\",\"storeName\":\"demo-app-craft\"}",
    "{\"key\":\"pixel-art-cells-state\",\"storeName\":\"pixel-art-cells\"}",
    "{\"key\":\"pixel-art-ui-state\",\"storeName\":\"pixel-art-ui\"}",
    "{\"key\":\"route-list-with-pagination\",\"storeName\":\"demo-app\"}",
    "{\"key\":\"user-query\",\"storeName\":\"demo-app\"}",
    "{\"key\":\"user-query\",\"storeName\":\"demo-app-craft\"}"
  ],
  "providers": [
    "Counter",
    "GranularMutation",
    "OtherService",
    "TodoStore",
    "User",
    "UserList",
    "UserMutation"
  ],
  "routeProviders": {},
  "componentProviders": {
    "CraftServiceCounterComponent": [
      "Counter"
    ],
    "CraftServiceUserDetailComponent": [
      "User"
    ],
    "CounterChild": [
      "Counter"
    ],
    "FullDemoCraft": [
      "TodoStore"
    ],
    "GranularMutationCraft": [
      "GranularMutation"
    ],
    "OtherComponent": [
      "OtherService"
    ],
    "ListWithPaginationCraft": [
      "UserList"
    ],
    "MutationCraft": [
      "UserMutation"
    ]
  },
  "providedOn": {
    "Counter": [
      {
        "kind": "component",
        "name": "CraftServiceCounterComponent",
        "file": "apps/demo/src/app/examples/craft-service/craft-service-counter.ts"
      },
      {
        "kind": "component",
        "name": "CounterChild",
        "file": "apps/demo/src/app/examples/craft-service/register-for.ts"
      }
    ],
    "User": [
      {
        "kind": "component",
        "name": "CraftServiceUserDetailComponent",
        "file": "apps/demo/src/app/examples/craft-service/craft-service-user-detail.ts"
      }
    ],
    "TodoStore": [
      {
        "kind": "component",
        "name": "FullDemoCraft",
        "file": "apps/demo/src/app/examples/craft/full-demo/full-demo.ts"
      }
    ],
    "GranularMutation": [
      {
        "kind": "component",
        "name": "GranularMutationCraft",
        "file": "apps/demo/src/app/examples/craft/granular-mutation/granular-mutation.ts"
      }
    ],
    "OtherService": [
      {
        "kind": "component",
        "name": "OtherComponent",
        "file": "apps/demo/src/app/examples/craft/lazy-layout/other.ts"
      }
    ],
    "UserList": [
      {
        "kind": "component",
        "name": "ListWithPaginationCraft",
        "file": "apps/demo/src/app/examples/craft/list-with-pagination/list-with-pagination.ts"
      }
    ],
    "UserMutation": [
      {
        "kind": "component",
        "name": "MutationCraft",
        "file": "apps/demo/src/app/examples/craft/mutation/mutation.ts"
      }
    ]
  },
  "collisions": {
    "services": {
      "ApiService": [
        "apps/demo/src/app/examples/craft/full-demo/api.service.ts",
        "apps/demo/src/app/examples/craft/granular-mutation/api.service.ts",
        "apps/demo/src/app/examples/craft/list-with-pagination/api.service.ts",
        "apps/demo/src/app/examples/craft/mutation/api.service.ts",
        "apps/demo/src/app/examples/craft/query/api.service.ts",
        "apps/demo/src/app/examples/playground/playground.ts",
        "apps/demo/src/app/examples/primitives/full-demo/api.service.ts",
        "apps/demo/src/app/examples/primitives/granular-mutation/api.service.ts",
        "apps/demo/src/app/examples/primitives/list-with-pagination/api.service.ts",
        "apps/demo/src/app/examples/primitives/mutation/api.service.ts",
        "apps/demo/src/app/examples/primitives/query/api.service.ts",
        "apps/demo/src/app/examples/routes/list-with-pagination/api.service.ts"
      ],
      "Counter": [
        "apps/demo/src/app/examples/craft-service/craft-service-counter.ts",
        "apps/demo/src/app/examples/craft-service/register-for.ts"
      ],
      "GranularMutation": [
        "apps/demo/src/app/examples/craft/granular-mutation/granular-mutation.ts",
        "apps/demo/src/app/examples/primitives/granular-mutation/granular-mutation.ts"
      ]
    },
    "components": {
      "GranularMutation": [
        "apps/demo/src/app/examples/craft/granular-mutation/granular-mutation.ts",
        "apps/demo/src/app/examples/primitives/granular-mutation/granular-mutation.ts"
      ]
    },
    "routes": {
      "": [
        "apps/demo/src/app/app.routes.ts",
        "apps/demo/src/app/examples/routes/slow-page/slow-page.routes.ts",
        "apps/demo/src/app/examples/routes/view-transitions/view-transitions.routes.ts"
      ]
    }
  },
  "browserBoundaryServices": [
    "BrowserCryptoService",
    "BrowserDocumentService",
    "BrowserHistoryService",
    "BrowserLocationService",
    "BrowserNavigatorService",
    "BrowserPerformanceService",
    "BrowserWindowService",
    "ConsoleService",
    "CookiesService",
    "LocalStorageService",
    "SessionStorageService"
  ],
  "scopes": {
    "restrictedData": "abstract",
    "Counter": "toProvide",
    "User": "toProvide",
    "UsersApi": "global",
    "ApiService": "global",
    "TodoStore": "toProvide",
    "GranularMutation": "toProvide",
    "test2": "global",
    "UsersApiOnError": "global",
    "OtherService": "toProvide",
    "UserList": "toProvide",
    "UserMutation": "toProvide",
    "UserQuery": "global",
    "Playground": "function",
    "SlowAccess": "global",
    "SlowReport": "global",
    "ViewTransitionAccess": "global",
    "Auth": "global",
    "AppStartLog": "toProvide",
    "BrowserCryptoService": "global",
    "BrowserDocumentService": "global",
    "BrowserHistoryService": "global",
    "BrowserLocationService": "global",
    "BrowserNavigatorService": "global",
    "BrowserPerformanceService": "global",
    "BrowserWindowService": "global",
    "ConsoleService": "global",
    "CookiesService": "global",
    "LocalStorageService": "global",
    "SessionStorageService": "global",
    "HostName": "manuallyProvidedAtRoot",
    "GlobalPersisterHandlerService": "toProvide",
    "LocalStoragePersister": "toProvide",
    "SessionStoragePersister": "toProvide",
    "StoragePersister": "abstract"
  }
} as const;
export type ArchitectureCatalog = typeof architectureCatalog;
