// Generated by loadDemoArchitectureGraph(). Do not edit.
export const architectureCatalog = {
  "version": 1,
  "graphHash": "79d277c4e849e8ca",
  "routes": [
    "",
    ":photoId",
    "component-composition",
    "content-projection",
    "craft-service/counter",
    "craft-service/register-for",
    "craft-service/user-detail",
    "craft/full-demo",
    "craft/granular-mutation",
    "craft/lazy-layout/:teamId",
    "craft/list-with-pagination",
    "craft/mutation/:userId",
    "craft/query/:userId",
    "css-vars",
    "css-vars/forwarding",
    "css-vars/inheritance",
    "css-vars/property",
    "css-vars/required",
    "debounced-web-search",
    "demo-send-context",
    "design-system",
    "design-system/scroll",
    "exception-query-params",
    "exceptions",
    "full-demo",
    "granular-mutation",
    "guard-demo",
    "i18n",
    "list-with-pagination",
    "login-form",
    "mutation/:userId",
    "pending-node",
    "pending-node/exception",
    "pixel-art",
    "pixel-art-matrix",
    "playground",
    "query-params",
    "query/:userId",
    "slow-page",
    "state-machine",
    "state-machine-list",
    "state-machine-text",
    "users/:userId",
    "view-transitions"
  ],
  "services": [
    "ApiService",
    "AppStartLog",
    "Auth",
    "ClientCurrency",
    "ClientUnits",
    "Counter",
    "CraftFieldCheckboxControl",
    "CraftFieldValueControl",
    "CraftLogServerUrl",
    "FunctionRegistryBridgeUrl",
    "FunctionRegistryClientId",
    "GlobalPersisterHandlerService",
    "GranularMutation",
    "I18n",
    "LogServerUrl",
    "MiddlewareExecutionScope",
    "OtherService",
    "Playground",
    "ProfilePermissions",
    "ServerFunctionTransport",
    "SlowAccess",
    "SlowReport",
    "StoragePersister",
    "StorageService",
    "TodoStore",
    "User",
    "UserList",
    "UserMutation",
    "UserQuery",
    "UsersApi",
    "UsersApiOnError",
    "ViewTransitionAccess",
    "aiContextMenuDismissal",
    "aiSendContextChatState",
    "aiSendDialogState",
    "appView",
    "cardView",
    "componentCompositionDemoView",
    "componentDemoView",
    "contentProjectionDemoView",
    "counterChildView",
    "craftGlobalQueryView",
    "craftRouterOutletState",
    "craftServiceCounterView",
    "craftServiceUserDetailView",
    "debouncedWebSearchView",
    "demoSendContextView",
    "designSystemDemoView",
    "dialogView",
    "dsAlertView",
    "dsButtonView",
    "dsGhostButtonView",
    "dsMeterView",
    "exceptionQueryParamsView",
    "exceptionsView",
    "fullDemoCraftView",
    "fullDemoView",
    "globalQueryView",
    "granularMutationCraftView",
    "granularMutationView",
    "lazyLayoutChildView",
    "lazyLayoutView",
    "listWithPaginationCraftView",
    "listWithPaginationView",
    "loginFormView",
    "mutationCraftView",
    "mutationDemoView",
    "myGlobalErrorScreenView",
    "myRouteLoadErrorScreenView",
    "otherView",
    "pendingNodeDemoView",
    "pendingNodeExceptionDemoView",
    "pixelArtMatrixView",
    "pixelArtView",
    "playgroundView",
    "profileEditorStateMachineView",
    "qpListWithPaginationView",
    "registerForDemoView",
    "restrictedContentView",
    "restrictedData",
    "sendContextCounterView",
    "statusView",
    "taskBoardStateMachineListView",
    "taskRowView",
    "test2",
    "textEditorStateMachineView",
    "toolbarActionView",
    "typeSafeI18nDemoView",
    "userBadgeView",
    "userCardView"
  ],
  "components": [
    "AiContextMenu",
    "AiSendContextChat",
    "AiSendContextLauncher",
    "AiSendDialog",
    "AnonymousComponent@setupCraftDirectiveTemplateTestImpl/synthetic",
    "App",
    "AssignedMeter",
    "BackToTop",
    "CounterChild",
    "CraftGlobalQuery",
    "CraftRouterOutlet",
    "CraftServiceCounterComponent",
    "CraftServiceUserDetailComponent",
    "CssVarsDemo",
    "CssVarsForwardingDemo",
    "CssVarsInheritanceDemo",
    "CssVarsPageNav",
    "CssVarsPropertyDemo",
    "CssVarsRequiredDemo",
    "DebouncedWebSearch",
    "DemoSendContextComponent",
    "DsAlert",
    "DsButton",
    "DsGhostButton",
    "DsMeter",
    "ExceptionQueryParamsComponent",
    "ExceptionsComponent",
    "ForwardingExample",
    "FullDemo",
    "FullDemoCraft",
    "GlobalQuery",
    "GranularMutation",
    "GranularMutationCraft",
    "GuardDemo",
    "InheritanceExample",
    "InheritedBadge",
    "LazyLayoutChildComponent",
    "LazyLayoutComponent",
    "ListWithPagination",
    "ListWithPaginationCraft",
    "LoginFormComponent",
    "MutationCraft",
    "MutationDemoComponent",
    "MyGlobalErrorScreen",
    "MyRouteLoadErrorScreen",
    "OtherComponent",
    "PixelArt",
    "PixelArtMatrix",
    "PlaygroundComponent",
    "ProfileEditorStateMachine",
    "QpListWithPagination",
    "RegisterForDemo",
    "RegisteredMeter",
    "ScrollDemo",
    "SendContextCounterComponent",
    "SlowPageComponent",
    "StatusComponent",
    "TaskBoardStateMachineList",
    "TaskRow",
    "TextEditorStateMachine",
    "TokenCard",
    "TypeSafeI18nDemo",
    "ViewTransitionsDetailComponent",
    "ViewTransitionsGalleryComponent",
    "ViewTransitionsSkeletonComponent",
    "card",
    "componentCompositionDemo",
    "componentDemo",
    "contentProjectionDemo",
    "craftPending",
    "designSystemDemo",
    "dialog",
    "lazyMessage",
    "pendingNodeDemo",
    "pendingNodeExceptionDemo",
    "restrictedContent",
    "toolbar",
    "toolbarAction",
    "userBadge",
    "userCard"
  ],
  "primitives": [
    "activeColor",
    "add",
    "addTodo",
    "auth",
    "backDisabled",
    "busy",
    "canReadRestrictedData",
    "captureError",
    "captureInProgress",
    "cell",
    "cells",
    "childTotal",
    "clearAllCache",
    "clearCache",
    "client",
    "computed",
    "copied",
    "counter",
    "counterChildIds",
    "currency",
    "currentArt",
    "currentPhoto",
    "currentPhotoTitle",
    "currentTerm",
    "currentTransitionName",
    "dataList",
    "debouncedSearch",
    "deleteTodo",
    "dialogOpen",
    "disabled",
    "draft",
    "draftEmail",
    "draftName",
    "editingStep",
    "error",
    "finishDisabled",
    "forwardDisabled",
    "goTo",
    "grid",
    "hasImage",
    "hasParseException",
    "hasPhoto",
    "hasResults",
    "hasSearchError",
    "hasUser",
    "hasValue",
    "heroArt",
    "heroEmoji",
    "heroTransitionName",
    "historyLabel",
    "imageSrc",
    "instruction",
    "isAdding",
    "isCurrentPageResolved",
    "isDebouncing",
    "isDoing",
    "isDone",
    "isEditing",
    "isReading",
    "isTodo",
    "isValid",
    "issue",
    "items",
    "label",
    "language",
    "lastAction",
    "lastActionLabel",
    "lastHandledException",
    "loginForm",
    "machine",
    "message",
    "meterValue",
    "modeQueryParams",
    "nameInput",
    "navOpen",
    "navToggleLabel",
    "navigate",
    "navigateNext",
    "navigatePrevious",
    "nextId",
    "note",
    "pagination",
    "paintCell",
    "paintedCount",
    "panelOffset",
    "parseExceptionMessage",
    "profileLabel",
    "profileQuery",
    "profileSource",
    "progress",
    "promptOptions",
    "query",
    "readOnly",
    "readingStep",
    "records",
    "remove",
    "removeTodo",
    "reopenDisabled",
    "replayJson",
    "replayStatus",
    "restriction",
    "resultBooks",
    "resultCount",
    "saveProfile",
    "searchInput",
    "searchQuery",
    "sendContextToAi",
    "serviceTotal",
    "setBusy",
    "setCaptureError",
    "setCaptureInProgress",
    "setCopied",
    "setError",
    "setPanelOffset",
    "setReplayStatus",
    "setStatus",
    "showDebouncing",
    "showEmpty",
    "showResults",
    "showSuccess",
    "showToolbar",
    "showcase",
    "size",
    "slowAccess",
    "slowReport",
    "startDisabled",
    "status",
    "statusEmoji",
    "statusLabel",
    "statusTone",
    "step",
    "stepHint",
    "submitBlocked",
    "submitted",
    "summary",
    "teams",
    "text",
    "throwError",
    "titleForm",
    "titleInput",
    "todos",
    "toggleTodo",
    "tone",
    "tooShort",
    "total",
    "totalPaintActions",
    "typedUserExceptionLoader",
    "ui",
    "update",
    "updateError",
    "updatePageSize",
    "updateUserName",
    "updateUserNameFn",
    "user",
    "userEmail",
    "userExceptionLoader",
    "userId",
    "userIdValue",
    "userIsLoading",
    "userName",
    "userQuery",
    "userStatusLabel",
    "userValueJson",
    "users",
    "usersQuery",
    "viewTransition",
    "viewTransitionAccess"
  ],
  "sources": [
    "cancel$ (source$)",
    "edit$ (source$)",
    "finish$ (source$)",
    "reopen$ (source$)",
    "restore$ (source$)",
    "saveRequest$ (source$)",
    "signalSource (signalSource)",
    "source$ (source$)",
    "start$ (source$)",
    "text.cancel (source$)",
    "text.commit (source$)",
    "text.edit (source$)"
  ],
  "serverFunctionFamilies": [],
  "httpEndpoints": [
    {
      "method": "GET",
      "url": "users"
    },
    {
      "method": "POST",
      "url": "<unresolved:ai-send-context-chat.ts:311>"
    }
  ],
  "uniques": [
    "{\"key\":\"granular\",\"storeName\":\"demo-app\"}",
    "{\"key\":\"granular\",\"storeName\":\"demo-app-craft\"}",
    "{\"key\":\"list-with-pagination\",\"storeName\":\"demo-app\"}",
    "{\"key\":\"list-with-pagination\",\"storeName\":\"demo-app-craft\"}",
    "{\"key\":\"mutation\",\"storeName\":\"demo-app\"}",
    "{\"key\":\"mutation\",\"storeName\":\"demo-app-craft\"}",
    "{\"key\":\"pixel-art-cells-state\",\"storeName\":\"pixel-art-cells\"}",
    "{\"key\":\"pixel-art-ui-state\",\"storeName\":\"pixel-art-ui\"}",
    "{\"key\":\"profile-editor\",\"storeName\":\"demo\"}",
    "{\"key\":\"route-list-with-pagination\",\"storeName\":\"demo-app\"}",
    "{\"key\":\"user-query\",\"storeName\":\"demo-app\"}",
    "{\"key\":\"user-query\",\"storeName\":\"demo-app-craft\"}"
  ],
  "providers": [
    "ClientCurrency",
    "ClientUnits",
    "Counter",
    "GranularMutation",
    "OtherService",
    "TodoStore",
    "User",
    "UserList",
    "UserMutation",
    "aiContextMenuDismissal",
    "aiSendContextChatState",
    "aiSendDialogState",
    "appView",
    "cardView",
    "componentCompositionDemoView",
    "componentDemoView",
    "contentProjectionDemoView",
    "counterChildView",
    "craftGlobalQueryView",
    "craftRouterOutletState",
    "craftServiceCounterView",
    "craftServiceUserDetailView",
    "debouncedWebSearchView",
    "demoSendContextView",
    "designSystemDemoView",
    "dialogView",
    "dsAlertView",
    "dsButtonView",
    "dsGhostButtonView",
    "dsMeterView",
    "exceptionQueryParamsView",
    "exceptionsView",
    "fullDemoCraftView",
    "fullDemoView",
    "globalQueryView",
    "granularMutationCraftView",
    "granularMutationView",
    "lazyLayoutChildView",
    "lazyLayoutView",
    "listWithPaginationCraftView",
    "listWithPaginationView",
    "loginFormView",
    "mutationCraftView",
    "mutationDemoView",
    "myGlobalErrorScreenView",
    "myRouteLoadErrorScreenView",
    "otherView",
    "pendingNodeDemoView",
    "pendingNodeExceptionDemoView",
    "pixelArtMatrixView",
    "pixelArtView",
    "playgroundView",
    "profileEditorStateMachineView",
    "qpListWithPaginationView",
    "registerForDemoView",
    "restrictedContentView",
    "sendContextCounterView",
    "statusView",
    "taskBoardStateMachineListView",
    "taskRowView",
    "textEditorStateMachineView",
    "toolbarActionView",
    "typeSafeI18nDemoView",
    "userBadgeView",
    "userCardView"
  ],
  "routeProviders": {},
  "componentProviders": {
    "App": [
      "appView"
    ],
    "componentCompositionDemo": [
      "componentCompositionDemoView"
    ],
    "restrictedContent": [
      "restrictedContentView"
    ],
    "componentDemo": [
      "componentDemoView"
    ],
    "userCard": [
      "userCardView"
    ],
    "toolbarAction": [
      "toolbarActionView"
    ],
    "userBadge": [
      "userBadgeView"
    ],
    "card": [
      "cardView"
    ],
    "contentProjectionDemo": [
      "contentProjectionDemoView"
    ],
    "dialog": [
      "dialogView"
    ],
    "pendingNodeDemo": [
      "pendingNodeDemoView"
    ],
    "pendingNodeExceptionDemo": [
      "pendingNodeExceptionDemoView"
    ],
    "CraftServiceCounterComponent": [
      "Counter",
      "craftServiceCounterView"
    ],
    "CraftServiceUserDetailComponent": [
      "User",
      "craftServiceUserDetailView"
    ],
    "CounterChild": [
      "Counter",
      "counterChildView"
    ],
    "RegisterForDemo": [
      "registerForDemoView"
    ],
    "FullDemoCraft": [
      "TodoStore",
      "fullDemoCraftView"
    ],
    "GranularMutationCraft": [
      "GranularMutation",
      "granularMutationCraftView"
    ],
    "LazyLayoutChildComponent": [
      "lazyLayoutChildView"
    ],
    "LazyLayoutComponent": [
      "lazyLayoutView"
    ],
    "OtherComponent": [
      "OtherService",
      "otherView"
    ],
    "ListWithPaginationCraft": [
      "UserList",
      "listWithPaginationCraftView"
    ],
    "MutationCraft": [
      "UserMutation",
      "mutationCraftView"
    ],
    "CraftGlobalQuery": [
      "craftGlobalQueryView"
    ],
    "designSystemDemo": [
      "designSystemDemoView"
    ],
    "DsAlert": [
      "dsAlertView"
    ],
    "DsMeter": [
      "dsMeterView"
    ],
    "DsButton": [
      "dsButtonView"
    ],
    "DsGhostButton": [
      "dsGhostButtonView"
    ],
    "TypeSafeI18nDemo": [
      "ClientCurrency",
      "ClientUnits",
      "typeSafeI18nDemoView"
    ],
    "SendContextCounterComponent": [
      "sendContextCounterView"
    ],
    "DemoSendContextComponent": [
      "demoSendContextView"
    ],
    "PlaygroundComponent": [
      "playgroundView"
    ],
    "DebouncedWebSearch": [
      "debouncedWebSearchView"
    ],
    "ExceptionQueryParamsComponent": [
      "exceptionQueryParamsView"
    ],
    "ExceptionsComponent": [
      "exceptionsView"
    ],
    "LoginFormComponent": [
      "loginFormView"
    ],
    "FullDemo": [
      "fullDemoView"
    ],
    "GranularMutation": [
      "granularMutationView"
    ],
    "ListWithPagination": [
      "listWithPaginationView"
    ],
    "MutationDemoComponent": [
      "mutationDemoView"
    ],
    "PixelArtMatrix": [
      "pixelArtMatrixView"
    ],
    "PixelArt": [
      "pixelArtView"
    ],
    "GlobalQuery": [
      "globalQueryView"
    ],
    "TaskBoardStateMachineList": [
      "taskBoardStateMachineListView"
    ],
    "TaskRow": [
      "taskRowView"
    ],
    "ProfileEditorStateMachine": [
      "profileEditorStateMachineView"
    ],
    "TextEditorStateMachine": [
      "textEditorStateMachineView"
    ],
    "QpListWithPagination": [
      "qpListWithPaginationView"
    ],
    "MyGlobalErrorScreen": [
      "myGlobalErrorScreenView"
    ],
    "MyRouteLoadErrorScreen": [
      "myRouteLoadErrorScreenView"
    ],
    "StatusComponent": [
      "statusView"
    ],
    "AiContextMenu": [
      "aiContextMenuDismissal"
    ],
    "AiSendContextChat": [
      "aiSendContextChatState"
    ],
    "AiSendDialog": [
      "aiSendDialogState"
    ],
    "CraftRouterOutlet": [
      "craftRouterOutletState"
    ]
  },
  "providedOn": {
    "appView": [
      {
        "kind": "component",
        "name": "App",
        "file": "apps/demo/src/app/app.ts"
      }
    ],
    "componentCompositionDemoView": [
      {
        "kind": "component",
        "name": "componentCompositionDemo",
        "file": "apps/demo/src/app/examples/component/component-composition-demo.ts"
      }
    ],
    "restrictedContentView": [
      {
        "kind": "component",
        "name": "restrictedContent",
        "file": "apps/demo/src/app/examples/component/component-composition-demo.ts"
      }
    ],
    "componentDemoView": [
      {
        "kind": "component",
        "name": "componentDemo",
        "file": "apps/demo/src/app/examples/component/component-demo.ts"
      }
    ],
    "userCardView": [
      {
        "kind": "component",
        "name": "userCard",
        "file": "apps/demo/src/app/examples/component/component-demo.ts"
      }
    ],
    "toolbarActionView": [
      {
        "kind": "component",
        "name": "toolbarAction",
        "file": "apps/demo/src/app/examples/component/content-projection-actions.ts"
      }
    ],
    "userBadgeView": [
      {
        "kind": "component",
        "name": "userBadge",
        "file": "apps/demo/src/app/examples/component/content-projection-actions.ts"
      }
    ],
    "cardView": [
      {
        "kind": "component",
        "name": "card",
        "file": "apps/demo/src/app/examples/component/content-projection-card.ts"
      }
    ],
    "contentProjectionDemoView": [
      {
        "kind": "component",
        "name": "contentProjectionDemo",
        "file": "apps/demo/src/app/examples/component/content-projection-demo.ts"
      }
    ],
    "dialogView": [
      {
        "kind": "component",
        "name": "dialog",
        "file": "apps/demo/src/app/examples/component/content-projection-overlays.ts"
      }
    ],
    "pendingNodeDemoView": [
      {
        "kind": "component",
        "name": "pendingNodeDemo",
        "file": "apps/demo/src/app/examples/component/pending-node-demo.ts"
      }
    ],
    "pendingNodeExceptionDemoView": [
      {
        "kind": "component",
        "name": "pendingNodeExceptionDemo",
        "file": "apps/demo/src/app/examples/component/pending-node-exception-demo.ts"
      }
    ],
    "Counter": [
      {
        "kind": "component",
        "name": "CraftServiceCounterComponent",
        "file": "apps/demo/src/app/examples/craft-service/craft-service-counter.ts"
      },
      {
        "kind": "component",
        "name": "CounterChild",
        "file": "apps/demo/src/app/examples/craft-service/register-for.ts"
      }
    ],
    "craftServiceCounterView": [
      {
        "kind": "component",
        "name": "CraftServiceCounterComponent",
        "file": "apps/demo/src/app/examples/craft-service/craft-service-counter.ts"
      }
    ],
    "User": [
      {
        "kind": "component",
        "name": "CraftServiceUserDetailComponent",
        "file": "apps/demo/src/app/examples/craft-service/craft-service-user-detail.ts"
      }
    ],
    "craftServiceUserDetailView": [
      {
        "kind": "component",
        "name": "CraftServiceUserDetailComponent",
        "file": "apps/demo/src/app/examples/craft-service/craft-service-user-detail.ts"
      }
    ],
    "counterChildView": [
      {
        "kind": "component",
        "name": "CounterChild",
        "file": "apps/demo/src/app/examples/craft-service/register-for.ts"
      }
    ],
    "registerForDemoView": [
      {
        "kind": "component",
        "name": "RegisterForDemo",
        "file": "apps/demo/src/app/examples/craft-service/register-for.ts"
      }
    ],
    "TodoStore": [
      {
        "kind": "component",
        "name": "FullDemoCraft",
        "file": "apps/demo/src/app/examples/craft/full-demo/full-demo.ts"
      }
    ],
    "fullDemoCraftView": [
      {
        "kind": "component",
        "name": "FullDemoCraft",
        "file": "apps/demo/src/app/examples/craft/full-demo/full-demo.ts"
      }
    ],
    "GranularMutation": [
      {
        "kind": "component",
        "name": "GranularMutationCraft",
        "file": "apps/demo/src/app/examples/craft/granular-mutation/granular-mutation.ts"
      }
    ],
    "granularMutationCraftView": [
      {
        "kind": "component",
        "name": "GranularMutationCraft",
        "file": "apps/demo/src/app/examples/craft/granular-mutation/granular-mutation.ts"
      }
    ],
    "lazyLayoutChildView": [
      {
        "kind": "component",
        "name": "LazyLayoutChildComponent",
        "file": "apps/demo/src/app/examples/craft/lazy-layout/lazy-layout-child.ts"
      }
    ],
    "lazyLayoutView": [
      {
        "kind": "component",
        "name": "LazyLayoutComponent",
        "file": "apps/demo/src/app/examples/craft/lazy-layout/lazy-layout.ts"
      }
    ],
    "OtherService": [
      {
        "kind": "component",
        "name": "OtherComponent",
        "file": "apps/demo/src/app/examples/craft/lazy-layout/other.ts"
      }
    ],
    "otherView": [
      {
        "kind": "component",
        "name": "OtherComponent",
        "file": "apps/demo/src/app/examples/craft/lazy-layout/other.ts"
      }
    ],
    "UserList": [
      {
        "kind": "component",
        "name": "ListWithPaginationCraft",
        "file": "apps/demo/src/app/examples/craft/list-with-pagination/list-with-pagination.ts"
      }
    ],
    "listWithPaginationCraftView": [
      {
        "kind": "component",
        "name": "ListWithPaginationCraft",
        "file": "apps/demo/src/app/examples/craft/list-with-pagination/list-with-pagination.ts"
      }
    ],
    "UserMutation": [
      {
        "kind": "component",
        "name": "MutationCraft",
        "file": "apps/demo/src/app/examples/craft/mutation/mutation.ts"
      }
    ],
    "mutationCraftView": [
      {
        "kind": "component",
        "name": "MutationCraft",
        "file": "apps/demo/src/app/examples/craft/mutation/mutation.ts"
      }
    ],
    "craftGlobalQueryView": [
      {
        "kind": "component",
        "name": "CraftGlobalQuery",
        "file": "apps/demo/src/app/examples/craft/query/query.ts"
      }
    ],
    "designSystemDemoView": [
      {
        "kind": "component",
        "name": "designSystemDemo",
        "file": "apps/demo/src/app/examples/design-system/design-system-demo.ts"
      }
    ],
    "dsAlertView": [
      {
        "kind": "component",
        "name": "DsAlert",
        "file": "apps/demo/src/app/examples/design-system/ds-components.alert-meter.ts"
      }
    ],
    "dsMeterView": [
      {
        "kind": "component",
        "name": "DsMeter",
        "file": "apps/demo/src/app/examples/design-system/ds-components.alert-meter.ts"
      }
    ],
    "dsButtonView": [
      {
        "kind": "component",
        "name": "DsButton",
        "file": "apps/demo/src/app/examples/design-system/ds-components.ts"
      }
    ],
    "dsGhostButtonView": [
      {
        "kind": "component",
        "name": "DsGhostButton",
        "file": "apps/demo/src/app/examples/design-system/ds-components.ts"
      }
    ],
    "ClientCurrency": [
      {
        "kind": "component",
        "name": "TypeSafeI18nDemo",
        "file": "apps/demo/src/app/examples/i18n/type-safe-i18n-demo.ts"
      }
    ],
    "ClientUnits": [
      {
        "kind": "component",
        "name": "TypeSafeI18nDemo",
        "file": "apps/demo/src/app/examples/i18n/type-safe-i18n-demo.ts"
      }
    ],
    "typeSafeI18nDemoView": [
      {
        "kind": "component",
        "name": "TypeSafeI18nDemo",
        "file": "apps/demo/src/app/examples/i18n/type-safe-i18n-demo.ts"
      }
    ],
    "sendContextCounterView": [
      {
        "kind": "component",
        "name": "SendContextCounterComponent",
        "file": "apps/demo/src/app/examples/ia/demo-send-context/counter.ts"
      }
    ],
    "demoSendContextView": [
      {
        "kind": "component",
        "name": "DemoSendContextComponent",
        "file": "apps/demo/src/app/examples/ia/demo-send-context/demo-send-context.ts"
      }
    ],
    "playgroundView": [
      {
        "kind": "component",
        "name": "PlaygroundComponent",
        "file": "apps/demo/src/app/examples/playground/playground.ts"
      }
    ],
    "debouncedWebSearchView": [
      {
        "kind": "component",
        "name": "DebouncedWebSearch",
        "file": "apps/demo/src/app/examples/primitives/debounced-web-search/debounced-web-search.ts"
      }
    ],
    "exceptionQueryParamsView": [
      {
        "kind": "component",
        "name": "ExceptionQueryParamsComponent",
        "file": "apps/demo/src/app/examples/primitives/exceptions/exception-query-params.ts"
      }
    ],
    "exceptionsView": [
      {
        "kind": "component",
        "name": "ExceptionsComponent",
        "file": "apps/demo/src/app/examples/primitives/exceptions/exceptions.ts"
      }
    ],
    "loginFormView": [
      {
        "kind": "component",
        "name": "LoginFormComponent",
        "file": "apps/demo/src/app/examples/primitives/forms/login-form.ts"
      }
    ],
    "fullDemoView": [
      {
        "kind": "component",
        "name": "FullDemo",
        "file": "apps/demo/src/app/examples/primitives/full-demo/full-demo.ts"
      }
    ],
    "granularMutationView": [
      {
        "kind": "component",
        "name": "GranularMutation",
        "file": "apps/demo/src/app/examples/primitives/granular-mutation/granular-mutation.ts"
      }
    ],
    "listWithPaginationView": [
      {
        "kind": "component",
        "name": "ListWithPagination",
        "file": "apps/demo/src/app/examples/primitives/list-with-pagination/list-with-pagination.ts"
      }
    ],
    "mutationDemoView": [
      {
        "kind": "component",
        "name": "MutationDemoComponent",
        "file": "apps/demo/src/app/examples/primitives/mutation/mutation.ts"
      }
    ],
    "pixelArtMatrixView": [
      {
        "kind": "component",
        "name": "PixelArtMatrix",
        "file": "apps/demo/src/app/examples/primitives/pixel-art-matrix/pixel-art-matrix.ts"
      }
    ],
    "pixelArtView": [
      {
        "kind": "component",
        "name": "PixelArt",
        "file": "apps/demo/src/app/examples/primitives/pixel-art/pixel-art.ts"
      }
    ],
    "globalQueryView": [
      {
        "kind": "component",
        "name": "GlobalQuery",
        "file": "apps/demo/src/app/examples/primitives/query/query.ts"
      }
    ],
    "taskBoardStateMachineListView": [
      {
        "kind": "component",
        "name": "TaskBoardStateMachineList",
        "file": "apps/demo/src/app/examples/primitives/state-machine-list/task-board.ts"
      }
    ],
    "taskRowView": [
      {
        "kind": "component",
        "name": "TaskRow",
        "file": "apps/demo/src/app/examples/primitives/state-machine-list/task-board.ts"
      }
    ],
    "profileEditorStateMachineView": [
      {
        "kind": "component",
        "name": "ProfileEditorStateMachine",
        "file": "apps/demo/src/app/examples/primitives/state-machine/profile-editor.ts"
      }
    ],
    "textEditorStateMachineView": [
      {
        "kind": "component",
        "name": "TextEditorStateMachine",
        "file": "apps/demo/src/app/examples/primitives/state-machine/text-editor.ts"
      }
    ],
    "qpListWithPaginationView": [
      {
        "kind": "component",
        "name": "QpListWithPagination",
        "file": "apps/demo/src/app/examples/routes/list-with-pagination/qp-list-with-pagination.ts"
      }
    ],
    "myGlobalErrorScreenView": [
      {
        "kind": "component",
        "name": "MyGlobalErrorScreen",
        "file": "apps/demo/src/app/my-global-error-screen.ts"
      }
    ],
    "myRouteLoadErrorScreenView": [
      {
        "kind": "component",
        "name": "MyRouteLoadErrorScreen",
        "file": "apps/demo/src/app/my-route-load-error-screen.ts"
      }
    ],
    "statusView": [
      {
        "kind": "component",
        "name": "StatusComponent",
        "file": "apps/demo/src/app/ui/status.component.ts"
      }
    ],
    "aiContextMenuDismissal": [
      {
        "kind": "component",
        "name": "AiContextMenu",
        "file": "libs/component/src/lib/ai/ai-context-menu.ts"
      }
    ],
    "aiSendContextChatState": [
      {
        "kind": "component",
        "name": "AiSendContextChat",
        "file": "libs/component/src/lib/ai/ai-send-context-chat.ts"
      }
    ],
    "aiSendDialogState": [
      {
        "kind": "component",
        "name": "AiSendDialog",
        "file": "libs/component/src/lib/ai/ai-send-dialog.ts"
      }
    ],
    "craftRouterOutletState": [
      {
        "kind": "component",
        "name": "CraftRouterOutlet",
        "file": "libs/component/src/lib/craft-router-outlet.ts"
      }
    ]
  },
  "collisions": {
    "services": {
      "ApiService": [
        "apps/demo/src/app/examples/craft/full-demo/api.service.ts",
        "apps/demo/src/app/examples/craft/granular-mutation/api.service.ts",
        "apps/demo/src/app/examples/craft/list-with-pagination/api.service.ts",
        "apps/demo/src/app/examples/craft/mutation/api.service.ts",
        "apps/demo/src/app/examples/craft/query/api.service.ts",
        "apps/demo/src/app/examples/playground/playground.ts",
        "apps/demo/src/app/examples/primitives/full-demo/api.service.ts",
        "apps/demo/src/app/examples/primitives/granular-mutation/api.service.ts",
        "apps/demo/src/app/examples/primitives/list-with-pagination/api.service.ts",
        "apps/demo/src/app/examples/primitives/mutation/api.service.ts",
        "apps/demo/src/app/examples/primitives/query/api.service.ts",
        "apps/demo/src/app/examples/routes/list-with-pagination/api.service.ts"
      ],
      "Counter": [
        "apps/demo/src/app/examples/craft-service/craft-service-counter.ts",
        "apps/demo/src/app/examples/craft-service/register-for.ts"
      ],
      "GranularMutation": [
        "apps/demo/src/app/examples/craft/granular-mutation/granular-mutation.ts",
        "apps/demo/src/app/examples/primitives/granular-mutation/granular-mutation.ts"
      ],
      "MiddlewareExecutionScope": [
        "libs/core/src/lib/server-function-middleware.ts",
        "libs/core/src/lib/server-function-middleware.ts"
      ]
    },
    "components": {
      "GranularMutation": [
        "apps/demo/src/app/examples/craft/granular-mutation/granular-mutation.ts",
        "apps/demo/src/app/examples/primitives/granular-mutation/granular-mutation.ts"
      ],
      "dialog": [
        "apps/demo/src/app/examples/component/content-projection-overlays.ts",
        "libs/component/src/lib/ai/ai-send-dialog.ts"
      ]
    },
    "routes": {
      "": [
        "apps/demo/src/app/app.routes.runtime.ts",
        "apps/demo/src/app/app.routes.ts",
        "apps/demo/src/app/examples/routes/slow-page/slow-page.routes.ts",
        "apps/demo/src/app/examples/routes/view-transitions/view-transitions.routes.ts"
      ],
      "component-composition": [
        "apps/demo/src/app/app.routes.runtime.ts",
        "apps/demo/src/app/app.routes.ts"
      ],
      "content-projection": [
        "apps/demo/src/app/app.routes.runtime.ts",
        "apps/demo/src/app/app.routes.ts"
      ],
      "craft-service/counter": [
        "apps/demo/src/app/app.routes.runtime.ts",
        "apps/demo/src/app/app.routes.ts"
      ],
      "craft-service/register-for": [
        "apps/demo/src/app/app.routes.runtime.ts",
        "apps/demo/src/app/app.routes.ts"
      ],
      "craft-service/user-detail": [
        "apps/demo/src/app/app.routes.runtime.ts",
        "apps/demo/src/app/app.routes.ts"
      ],
      "craft/full-demo": [
        "apps/demo/src/app/app.routes.runtime.ts",
        "apps/demo/src/app/app.routes.ts"
      ],
      "craft/granular-mutation": [
        "apps/demo/src/app/app.routes.runtime.ts",
        "apps/demo/src/app/app.routes.ts"
      ],
      "craft/lazy-layout/:teamId": [
        "apps/demo/src/app/app.routes.runtime.ts",
        "apps/demo/src/app/app.routes.ts"
      ],
      "craft/list-with-pagination": [
        "apps/demo/src/app/app.routes.runtime.ts",
        "apps/demo/src/app/app.routes.ts"
      ],
      "craft/mutation/:userId": [
        "apps/demo/src/app/app.routes.runtime.ts",
        "apps/demo/src/app/app.routes.ts"
      ],
      "craft/query/:userId": [
        "apps/demo/src/app/app.routes.runtime.ts",
        "apps/demo/src/app/app.routes.ts"
      ],
      "css-vars": [
        "apps/demo/src/app/app.routes.runtime.ts",
        "apps/demo/src/app/app.routes.ts"
      ],
      "css-vars/forwarding": [
        "apps/demo/src/app/app.routes.runtime.ts",
        "apps/demo/src/app/app.routes.ts"
      ],
      "css-vars/inheritance": [
        "apps/demo/src/app/app.routes.runtime.ts",
        "apps/demo/src/app/app.routes.ts"
      ],
      "css-vars/property": [
        "apps/demo/src/app/app.routes.runtime.ts",
        "apps/demo/src/app/app.routes.ts"
      ],
      "css-vars/required": [
        "apps/demo/src/app/app.routes.runtime.ts",
        "apps/demo/src/app/app.routes.ts"
      ],
      "debounced-web-search": [
        "apps/demo/src/app/app.routes.runtime.ts",
        "apps/demo/src/app/app.routes.ts"
      ],
      "demo-send-context": [
        "apps/demo/src/app/app.routes.runtime.ts",
        "apps/demo/src/app/app.routes.ts"
      ],
      "design-system": [
        "apps/demo/src/app/app.routes.runtime.ts",
        "apps/demo/src/app/app.routes.ts"
      ],
      "design-system/scroll": [
        "apps/demo/src/app/app.routes.runtime.ts",
        "apps/demo/src/app/app.routes.ts"
      ],
      "exception-query-params": [
        "apps/demo/src/app/app.routes.runtime.ts",
        "apps/demo/src/app/app.routes.ts"
      ],
      "exceptions": [
        "apps/demo/src/app/app.routes.runtime.ts",
        "apps/demo/src/app/app.routes.ts"
      ],
      "full-demo": [
        "apps/demo/src/app/app.routes.runtime.ts",
        "apps/demo/src/app/app.routes.ts"
      ],
      "granular-mutation": [
        "apps/demo/src/app/app.routes.runtime.ts",
        "apps/demo/src/app/app.routes.ts"
      ],
      "guard-demo": [
        "apps/demo/src/app/app.routes.runtime.ts",
        "apps/demo/src/app/app.routes.ts"
      ],
      "i18n": [
        "apps/demo/src/app/app.routes.runtime.ts",
        "apps/demo/src/app/app.routes.ts"
      ],
      "list-with-pagination": [
        "apps/demo/src/app/app.routes.runtime.ts",
        "apps/demo/src/app/app.routes.ts"
      ],
      "login-form": [
        "apps/demo/src/app/app.routes.runtime.ts",
        "apps/demo/src/app/app.routes.ts"
      ],
      "mutation/:userId": [
        "apps/demo/src/app/app.routes.runtime.ts",
        "apps/demo/src/app/app.routes.ts"
      ],
      "pending-node": [
        "apps/demo/src/app/app.routes.runtime.ts",
        "apps/demo/src/app/app.routes.ts"
      ],
      "pending-node/exception": [
        "apps/demo/src/app/app.routes.runtime.ts",
        "apps/demo/src/app/app.routes.ts"
      ],
      "pixel-art": [
        "apps/demo/src/app/app.routes.runtime.ts",
        "apps/demo/src/app/app.routes.ts"
      ],
      "pixel-art-matrix": [
        "apps/demo/src/app/app.routes.runtime.ts",
        "apps/demo/src/app/app.routes.ts"
      ],
      "playground": [
        "apps/demo/src/app/app.routes.runtime.ts",
        "apps/demo/src/app/app.routes.ts"
      ],
      "query-params": [
        "apps/demo/src/app/app.routes.runtime.ts",
        "apps/demo/src/app/app.routes.ts"
      ],
      "query/:userId": [
        "apps/demo/src/app/app.routes.runtime.ts",
        "apps/demo/src/app/app.routes.ts"
      ],
      "slow-page": [
        "apps/demo/src/app/app.routes.runtime.ts",
        "apps/demo/src/app/app.routes.ts"
      ],
      "state-machine": [
        "apps/demo/src/app/app.routes.runtime.ts",
        "apps/demo/src/app/app.routes.ts"
      ],
      "state-machine-list": [
        "apps/demo/src/app/app.routes.runtime.ts",
        "apps/demo/src/app/app.routes.ts"
      ],
      "state-machine-text": [
        "apps/demo/src/app/app.routes.runtime.ts",
        "apps/demo/src/app/app.routes.ts"
      ],
      "view-transitions": [
        "apps/demo/src/app/app.routes.runtime.ts",
        "apps/demo/src/app/app.routes.ts"
      ]
    }
  },
  "browserBoundaryServices": [],
  "scopes": {}
} as const;
export type ArchitectureCatalog = typeof architectureCatalog;
