import { renameSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import {
  analyzeDependencyGraph,
  architectureCatalogToTypeScript,
  buildArchitectureCatalog,
  createArchitectureGraph,
} from '@craft-ts/dev-tools';
import { architectureCatalog } from './catalog';

const workspaceRoot = resolve(import.meta.dirname, '../../..');
const catalogPath = join(import.meta.dirname, 'catalog.ts');

let cached: ReturnType<typeof createArchitectureGraph> | undefined;

export function loadDemoArchitectureGraph() {
  if (cached) return cached;
  const graph = analyzeDependencyGraph({
    rootDir: workspaceRoot,
    tsConfigFilePath: 'apps/demo/tsconfig.graph.json',
  });
  const generatedCatalog =
    `// Generated by loadDemoArchitectureGraph(). Do not edit.\n${architectureCatalogToTypeScript(buildArchitectureCatalog(graph))}`;
  const temporaryCatalogPath = `${catalogPath}.${process.pid}.tmp`;
  writeFileSync(temporaryCatalogPath, generatedCatalog);
  renameSync(temporaryCatalogPath, catalogPath);
  cached = createArchitectureGraph(graph, architectureCatalog);
  return cached;
}
