export const architectureCatalog = {
  "version": 1,
  "graphHash": "0d7ac44e5622be80",
  "routes": [
    "",
    "access",
    "effect-function",
    "i18n",
    "playground",
    "sync-members",
    "team"
  ],
  "services": [
    "AccessPolicyService",
    "AiContextMenuController",
    "AppSnapshotRegistry",
    "BrowserCryptoService",
    "BrowserDocumentService",
    "BrowserHistoryService",
    "BrowserLocationService",
    "BrowserNavigatorService",
    "BrowserPerformanceService",
    "BrowserWindowService",
    "CartPricing",
    "ComponentMonitoring",
    "ConsoleService",
    "CookiesService",
    "CorrelationIdService",
    "CraftA11yNavigationFocus",
    "CraftActivatedRoute",
    "CraftActiveRouteLoadError",
    "CraftBlankMs",
    "CraftChildMatch",
    "CraftCompiledRoutes",
    "CraftCspNonce",
    "CraftDomEventHooks",
    "CraftDynamicImport",
    "CraftErrorComponent",
    "CraftFieldCheckboxControl",
    "CraftFieldExceptionBoundary",
    "CraftFieldValueControl",
    "CraftGlobalError",
    "CraftGlobalErrorComponent",
    "CraftHistory",
    "CraftHttpTraces",
    "CraftHydrationRuntime",
    "CraftLazyLoadRetry",
    "CraftLoadingText",
    "CraftLocation",
    "CraftLogServerUrl",
    "CraftMatch",
    "CraftNodeEffectFactory",
    "CraftPendingComponent",
    "CraftPendingMinMs",
    "CraftPlatform",
    "CraftPrimitiveRegistry",
    "CraftRenderIdentity",
    "CraftRootComponent",
    "CraftRouteChainRunner",
    "CraftRouteLoadError",
    "CraftRouteLoadErrorComponent",
    "CraftRouteLoadErrorConfig",
    "CraftRouteLoadRecovery",
    "CraftRouteLoadRetry",
    "CraftRouteTarget",
    "CraftRoutedComponent",
    "CraftRouter",
    "CraftRouterRuntime",
    "CraftRouterTraces",
    "CraftRuntimeMode",
    "CraftSchemaValidationPolicy",
    "CraftSecurityPolicy",
    "CraftSsrPolicy",
    "CraftSsrRuntime",
    "CraftStartViewTransition",
    "CraftStayMs",
    "CraftStyleRegistry",
    "CraftSyncTemplateFlush",
    "CraftTitleStrategy",
    "CraftViewTransition",
    "CraftViewTransitionSkipBlank",
    "CraftViewTransitionsEnabled",
    "Database",
    "DynamicEffectRefInstance",
    "DynamicResourceInstance",
    "ForScheduler",
    "GlobalPersisterHandlerService",
    "HostName",
    "I18nEffectService",
    "InsertionSnapshotRegistry",
    "LocalStoragePersister",
    "LocalStorageService",
    "MiddlewareExecutionScope",
    "PrimitiveMethodRuntimeContext",
    "PrimitiveResourceRuntimeObservers",
    "SendContextChatActions",
    "SendContextChatComponent",
    "SendContextChatSections",
    "SendContextContextMenuComponent",
    "SendContextEventEnrichers",
    "SendContextEventFilters",
    "SendContextEventSources",
    "SendContextExportSections",
    "SendContextLauncherComponent",
    "SendContextRecordController",
    "SendContextRedactor",
    "SendContextRetentionPolicy",
    "SendContextSession",
    "SendContextToAiBuffer",
    "SendContextUiRenderer",
    "SendContextValueSerializer",
    "ServerFunctionTransport",
    "SessionService",
    "SessionStoragePersister",
    "SessionStorageService",
    "StoragePersister",
    "StorageService",
    "TakeAppSnapshot",
    "TeamContextService",
    "TemplateTraces",
    "TodoStore",
    "api"
  ],
  "components": [
    "AiContextMenu",
    "AiSendContextChat",
    "AiSendContextLauncher",
    "AiSendDialog",
    "AnonymousComponent@setupCraftDirectiveTemplateTestImpl/synthetic",
    "App",
    "CraftRouterOutlet",
    "EffectFunctionComponent",
    "EffectI18nComponent",
    "EffectLayerScopeComponent",
    "EffectPlaygroundComponent",
    "EffectSharedServiceComponent",
    "EffectSyncMembersComponent",
    "EffectYieldComponent",
    "craftPending"
  ],
  "primitives": [
    "accessLabel",
    "accessQuery",
    "accessReason",
    "add",
    "addTodo",
    "busy",
    "captureError",
    "captureInProgress",
    "copied",
    "effectFunctionQuery",
    "englishPressed",
    "error",
    "formattedPreview",
    "frenchPressed",
    "hasData",
    "hasDecision",
    "hasProfile",
    "heading",
    "headingText",
    "instruction",
    "lines",
    "locale",
    "memberNames",
    "panelOffset",
    "placed",
    "profileName",
    "profileQuery",
    "promptOptions",
    "qty",
    "quoteLabel",
    "receiptQuery",
    "removeTodo",
    "sendContextToAi",
    "setBusy",
    "setCaptureError",
    "setCaptureInProgress",
    "setCopied",
    "setError",
    "setPanelOffset",
    "setStatus",
    "shippingQuery",
    "showUnknown",
    "status",
    "summary",
    "teamName",
    "teamOverviewQuery",
    "titleInput",
    "todos",
    "toggleTodo",
    "total",
    "totalLabel",
    "userName",
    "viewerAccess",
    "viewerName",
    "weightLabel"
  ],
  "sources": [
    "signalSource (signalSource)",
    "source$ (source$)"
  ],
  "serverFunctionFamilies": [],
  "httpEndpoints": [
    {
      "method": "POST",
      "url": "<unresolved:ai-send-context-chat.ts:508>"
    }
  ],
  "uniques": [],
  "providers": [],
  "routeProviders": {},
  "componentProviders": {},
  "providedOn": {},
  "collisions": {
    "services": {
      "AccessPolicyService": [
        "apps/demo-effect/src/app/shared/access-domain.ts",
        "apps/demo-effect/src/app/shared/access-domain.ts"
      ],
      "CartPricing": [
        "apps/demo-effect/src/app/examples/effect/effect-pricing-domain.ts",
        "apps/demo-effect/src/app/examples/effect/effect-pricing-domain.ts"
      ],
      "CraftPendingComponent": [
        "libs/component/src/lib/craft-host-tokens.ts",
        "libs/core/src/lib/craft-pending.ts"
      ],
      "Database": [
        "apps/demo-effect/src/app/examples/effect/effect-database.ts",
        "apps/demo-effect/src/app/examples/effect/effect-database.ts"
      ],
      "I18nEffectService": [
        "libs/i18n-effect/src/lib/i18n-effect.ts",
        "libs/i18n-effect/src/lib/i18n-effect.ts"
      ],
      "MiddlewareExecutionScope": [
        "libs/core/src/lib/server-function-middleware.ts",
        "libs/core/src/lib/server-function-middleware.ts"
      ],
      "SessionService": [
        "apps/demo-effect/src/app/shared/access-domain.ts",
        "apps/demo-effect/src/app/shared/access-domain.ts"
      ],
      "TeamContextService": [
        "apps/demo-effect/src/app/shared/access-domain.ts",
        "apps/demo-effect/src/app/shared/access-domain.ts"
      ],
      "TodoStore": [
        "apps/demo-effect/src/app/examples/effect/effect-playground-domain.ts",
        "apps/demo-effect/src/app/examples/effect/effect-playground-domain.ts"
      ],
      "api": [
        "libs/core/src/lib/craft-register-for.ts",
        "libs/core/src/lib/craft-service.ts"
      ]
    },
    "components": {},
    "routes": {}
  },
  "browserBoundaryServices": [
    "BrowserCryptoService",
    "BrowserDocumentService",
    "BrowserHistoryService",
    "BrowserLocationService",
    "BrowserNavigatorService",
    "BrowserPerformanceService",
    "BrowserWindowService",
    "ConsoleService",
    "CookiesService",
    "LocalStorageService",
    "SessionStorageService"
  ],
  "scopes": {}
} as const;
export type ArchitectureCatalog = typeof architectureCatalog;
