export {
  type CraftTrackTags,
  ɵHOST_NAME_META_DATA as HOST_NAME_META_DATA,
  ɵHOST_TAG_LIST as HOST_TAG_LIST,
  ɵTRACK_TAGS_LIST as TRACK_TAGS_LIST,
  ɵHostNameToProvide as HostNameToProvide,
  ɵHostNameToYield as HostNameToYield,
  ɵHostTagToYield as HostTagToYield,
  ɵTrackTagsToYield as TrackTagsToYield,
  type TrackTag,
  ɵinjectHostName as injectHostName,
  ɵinjectTrackTags as injectTrackTags,
  ɵprovideHostName as provideHostName,
  ɵprovideTrackTags as provideTrackTags,
} from './craft-service';
