// Generated. Do not edit.
export const architectureCatalog = {
  "version": 1,
  "graphHash": "bf6d5cf4ac1df166",
  "routes": [],
  "services": [
    "BrowserCryptoService",
    "BrowserDocumentService",
    "BrowserHistoryService",
    "BrowserLocationService",
    "BrowserNavigatorService",
    "BrowserPerformanceService",
    "BrowserWindowService",
    "CloseReview",
    "ConsoleService",
    "CookiesService",
    "CraftLogServerUrl",
    "GlobalPersisterHandlerService",
    "HostName",
    "LocalStoragePersister",
    "LocalStorageService",
    "MiddlewareExecutionScope",
    "RetirementReasonChoice",
    "ReviewFilters",
    "ReviewPreferences",
    "ServerFunctionTransport",
    "SessionStoragePersister",
    "SessionStorageService",
    "StoragePersister",
    "StorageService",
    "api"
  ],
  "components": [
    "AiContextMenu",
    "AiSendDialog",
    "AnonymousComponent@setupCraftDirectiveTemplateTestImpl/synthetic",
    "AssetsInventoryList",
    "CraftRouterOutlet",
    "FilterBarActions",
    "FilterBarFields",
    "RetirementReasonPicker",
    "ReviewApp",
    "ThemeLocalePicker",
    "TierLegend",
    "ViewTabs",
    "craftPending"
  ],
  "primitives": [
    "activeFilterCount",
    "activeIndex",
    "activeMentions",
    "band",
    "canReplay",
    "cards",
    "changedHidden",
    "changedLabel",
    "chooseDevtoolView",
    "chooseLocale",
    "chooseRetirementReason",
    "chooseTheme",
    "chooseZoom",
    "chrome",
    "clearFilters",
    "closeIterationDialog",
    "closeRegenerationDialog",
    "closeReview",
    "closeReviewSession",
    "componentFilter",
    "confirmIterationHandoff",
    "confirmRegeneration",
    "copied",
    "copyIterationPrompt",
    "coveredCount",
    "craftComputed",
    "current",
    "decide",
    "decisionFailed",
    "degraded",
    "devtoolView",
    "directionFilter",
    "evidenceView",
    "fellBack",
    "fidelitySentence",
    "findings",
    "hasNote",
    "hiddenLegend",
    "hideChrome",
    "inspectFrame",
    "inspectReplay",
    "instruction",
    "iterationDialogOpen",
    "iterationHandoff",
    "iterationHandoffAvailable",
    "iterationHandoffFailed",
    "iterationHandoffReady",
    "iterationPreparationNotStarted",
    "iterationPreparationStarted",
    "iterationPromptCopied",
    "kindFilter",
    "locale",
    "member",
    "mentions",
    "moveNext",
    "movePrevious",
    "noFiltersActive",
    "note",
    "occludedHidden",
    "occludedLabel",
    "openIterationDialog",
    "openRegenerationDialog",
    "openVisualReview",
    "overlayHint",
    "overlayLabel",
    "pickedLabel",
    "previewMention",
    "previousRegenerationDecisions",
    "regenerateEvidence",
    "regenerationAvailable",
    "regenerationDialogOpen",
    "regenerationFailed",
    "rejectionAttempted",
    "rejectionReasonMissing",
    "reopenDecision",
    "reopenFailed",
    "reopenReviewDecision",
    "replay",
    "replayTarget",
    "retire",
    "retirementReason",
    "reviewDecision",
    "reviewFailed",
    "reviewNavigation",
    "reviewPressed",
    "reviewQueue",
    "selectCard",
    "selectNodes",
    "selectVisualTest",
    "selectedVisualAsset",
    "selectedVisualTest",
    "selection",
    "sessionHistory",
    "setCopied",
    "setInstruction",
    "showBand",
    "showingReplay",
    "stateFilter",
    "statusText",
    "subjectLabel",
    "t",
    "templateObligations",
    "templatePressed",
    "textFilter",
    "theme",
    "toggleChrome",
    "trackSelection",
    "visualAssets",
    "visualEvidence",
    "visualPressed",
    "visualReviewCard",
    "visualTests",
    "zoom"
  ],
  "sources": [
    "clearFilters$ (source$)",
    "closeReviewRequested$ (source$)",
    "decisionReopened$ (source$)",
    "decisionSubmitted$ (source$)",
    "iterationDialogClosed$ (source$)",
    "iterationDialogRequested$ (source$)",
    "iterationHandoffRequested$ (source$)",
    "mentionEdited$ (source$)",
    "navigation$ (source$)",
    "regenerationConfirmed$ (source$)",
    "regenerationDialogClosed$ (source$)",
    "regenerationDialogRequested$ (source$)",
    "signalSource (signalSource)",
    "source$ (source$)"
  ],
  "serverFunctionFamilies": [],
  "httpEndpoints": [
    {
      "method": "GET",
      "url": "/api/digest/*"
    },
    {
      "method": "GET",
      "url": "/api/review"
    },
    {
      "method": "POST",
      "url": "/api/close-review"
    },
    {
      "method": "POST",
      "url": "/api/decisions"
    },
    {
      "method": "POST",
      "url": "/api/decisions/reopen"
    },
    {
      "method": "POST",
      "url": "/api/iteration-handoff"
    },
    {
      "method": "POST",
      "url": "/api/regenerate"
    }
  ],
  "uniques": [],
  "providers": [],
  "routeProviders": {},
  "componentProviders": {},
  "providedOn": {},
  "collisions": {
    "services": {
      "CloseReview": [
        "libs/style-testing/attestation-app/src/close-review.service.ts",
        "libs/style-testing/attestation-app/src/review-app.ts"
      ],
      "MiddlewareExecutionScope": [
        "libs/core/src/lib/server-function-middleware.ts",
        "libs/core/src/lib/server-function-middleware.ts"
      ]
    },
    "components": {},
    "routes": {}
  },
  "browserBoundaryServices": [
    "BrowserCryptoService",
    "BrowserDocumentService",
    "BrowserHistoryService",
    "BrowserLocationService",
    "BrowserNavigatorService",
    "BrowserPerformanceService",
    "BrowserWindowService",
    "ConsoleService",
    "CookiesService",
    "LocalStorageService",
    "SessionStorageService"
  ],
  "scopes": {}
} as const;
export type ArchitectureCatalog = typeof architectureCatalog;
