"""
Builds `src/logo/logo.art.style.ts` from the craft-ts logo (`apps/docs/public/assets/craft-ts-logo.png`).

The logo is a continuous gradient (indigo, violet, magenta, pink, orange) with folds and
shadows. It cannot be one flat mask per colour, so it is taken apart:

* `sil`   — its silhouette (alpha), the mask of the whole mark;
* `r0..r7` — eight bands along the gradient. Each pixel is placed on a ramp by its hue, and
  the bands are alphas chosen so that painting them one over the other, in order, gives the
  exact interpolation between eight colours. Repaint the eight colours and the gradient
  follows, fold for fold;
* `shade` — how much darker than the gradient a pixel is (the overlaps and folds), painted in
  a dark colour;
* `light` — the pale edge, painted in a light colour.

Run it again if the logo changes:  python3 libs/docs-ui/scripts/logo-masks.py
Needs Pillow and numpy.
"""
import base64, io, os, sys
from PIL import Image
import numpy as np
HERE=os.path.dirname(os.path.abspath(__file__))
SRC=os.path.join(HERE,'../../../apps/docs/public/assets/craft-ts-logo.png')
OUT=os.path.join(HERE,'../src/logo/logo.art.style.ts')
S=192
im=Image.open(SRC).convert('RGBa').resize((S,S),Image.LANCZOS).convert('RGBA')
a=np.asarray(im).astype(float)/255
A=a[...,3]; rgb=a[...,:3]
# hsv
mx=rgb.max(-1); mn=rgb.min(-1); d=mx-mn+1e-9
r,g,b=rgb[...,0],rgb[...,1],rgb[...,2]
h=np.where(mx==r,((g-b)/d)%6,np.where(mx==g,(b-r)/d+2,(r-g)/d+4))*60
s=np.where(mx>0,(mx-mn)/(mx+1e-9),0); v=mx
hp=np.where(h<200,h+360,h)
u=np.clip((hp-232)/(398-232),0,1)
conf=(A>0.9)&(s>0.30)
# nearest-neighbour fill of u into pixels that are not confident (edges, highlights):
# averaging would mix the colours of two bars at a border and leave a fringe.
conf=(A>0.97)&(s>0.30)
filled=conf.copy(); uf=np.where(conf,u,0.0)
shifts=[(-1,0),(1,0),(0,-1),(0,1),(-1,-1),(-1,1),(1,-1),(1,1)]
for _ in range(14):
    nu=uf.copy(); nf=filled.copy()
    for dy,dx in shifts:
        sh_u=np.roll(uf,(dy,dx),(0,1)); sh_f=np.roll(filled,(dy,dx),(0,1))
        take=(~nf)&sh_f
        nu=np.where(take,sh_u,nu); nf=nf|take
    uf=nu; filled=nf
u=np.where(conf,u,uf)
knots=np.array([0,.1,.2,.47,.6,.73,.86,1.0])
N=len(knots)
w=np.zeros((N,S,S))
for i in range(N):
    x=np.zeros_like(u)
    if i>0:
        m=(u>=knots[i-1])&(u<=knots[i]); x[m]=(u[m]-knots[i-1])/(knots[i]-knots[i-1])
    if i<N-1:
        m=(u>knots[i])&(u<=knots[i+1]); x[m]=(knots[i+1]-u[m])/(knots[i+1]-knots[i])
    if i==0: x[u<=knots[0]]=1
    if i==N-1: x[u>=knots[-1]]=1
    w[i]=x
w/=np.maximum(w.sum(0),1e-9)
cum=np.cumsum(w,axis=0)
alphas=[w[i]/np.maximum(cum[i],1e-9) for i in range(N)]
shade=np.clip((1-v)/0.45,0,0.75)
light=np.clip((0.50-s)/0.18,0,0.9)
layers={'sil':A,**{f'r{i}':alphas[i] for i in range(N)},'shade':shade,'light':light}
out={}
for k,arr in layers.items():
    rgba=np.zeros((S,S,4),dtype=np.uint8); rgba[...,3]=np.round(np.clip(arr,0,1)*255).astype(np.uint8)
    buf=io.BytesIO(); Image.fromarray(rgba,'RGBA').save(buf,'PNG',optimize=True)
    out[k]='data:image/png;base64,'+base64.b64encode(buf.getvalue()).decode()
lines=['/**',' * GENERATED by `libs/docs-ui/scripts/logo-masks.py` from the craft-ts logo. Do not edit.',' *',' * Eleven alpha masks of %d x %d pixels: the silhouette of the mark, eight bands along its'%(S,S),' * gradient, its shade and its light. See the script for what each one is.',' */','export const LOGO_MASKS = {']
for k in layers: lines.append("  %s: '%s',"%(k,out[k]))
lines+=['} as const;','','export type LogoMask = keyof typeof LOGO_MASKS;','']
open(OUT,'w').write('\n'.join(lines))
print('written',OUT,sum(len(v) for v in out.values()),'bytes')
