// <auto-generated by tools/generate-stream-pipe.mjs — do not edit by hand>
import type { CraftStream, StreamOperator } from './craft-stream';

/**
 * The `.pipe(...)` method of a {@link CraftStream}: applies operators
 * left-to-right, each slot inferred from the previous one (arities 1..14).
 * Beyond 14 operators, nest `.pipe(...).pipe(...)`.
 */
export interface CraftStreamPipe<A, Y> {
  <A1, Y1>(
    op1: StreamOperator<A, Y, A1, Y1>,
  ): CraftStream<A1, Y1>;
  <A1, Y1, A2, Y2>(
    op1: StreamOperator<A, Y, A1, Y1>,
    op2: StreamOperator<A1, Y1, A2, Y2>,
  ): CraftStream<A2, Y2>;
  <A1, Y1, A2, Y2, A3, Y3>(
    op1: StreamOperator<A, Y, A1, Y1>,
    op2: StreamOperator<A1, Y1, A2, Y2>,
    op3: StreamOperator<A2, Y2, A3, Y3>,
  ): CraftStream<A3, Y3>;
  <A1, Y1, A2, Y2, A3, Y3, A4, Y4>(
    op1: StreamOperator<A, Y, A1, Y1>,
    op2: StreamOperator<A1, Y1, A2, Y2>,
    op3: StreamOperator<A2, Y2, A3, Y3>,
    op4: StreamOperator<A3, Y3, A4, Y4>,
  ): CraftStream<A4, Y4>;
  <A1, Y1, A2, Y2, A3, Y3, A4, Y4, A5, Y5>(
    op1: StreamOperator<A, Y, A1, Y1>,
    op2: StreamOperator<A1, Y1, A2, Y2>,
    op3: StreamOperator<A2, Y2, A3, Y3>,
    op4: StreamOperator<A3, Y3, A4, Y4>,
    op5: StreamOperator<A4, Y4, A5, Y5>,
  ): CraftStream<A5, Y5>;
  <A1, Y1, A2, Y2, A3, Y3, A4, Y4, A5, Y5, A6, Y6>(
    op1: StreamOperator<A, Y, A1, Y1>,
    op2: StreamOperator<A1, Y1, A2, Y2>,
    op3: StreamOperator<A2, Y2, A3, Y3>,
    op4: StreamOperator<A3, Y3, A4, Y4>,
    op5: StreamOperator<A4, Y4, A5, Y5>,
    op6: StreamOperator<A5, Y5, A6, Y6>,
  ): CraftStream<A6, Y6>;
  <A1, Y1, A2, Y2, A3, Y3, A4, Y4, A5, Y5, A6, Y6, A7, Y7>(
    op1: StreamOperator<A, Y, A1, Y1>,
    op2: StreamOperator<A1, Y1, A2, Y2>,
    op3: StreamOperator<A2, Y2, A3, Y3>,
    op4: StreamOperator<A3, Y3, A4, Y4>,
    op5: StreamOperator<A4, Y4, A5, Y5>,
    op6: StreamOperator<A5, Y5, A6, Y6>,
    op7: StreamOperator<A6, Y6, A7, Y7>,
  ): CraftStream<A7, Y7>;
  <A1, Y1, A2, Y2, A3, Y3, A4, Y4, A5, Y5, A6, Y6, A7, Y7, A8, Y8>(
    op1: StreamOperator<A, Y, A1, Y1>,
    op2: StreamOperator<A1, Y1, A2, Y2>,
    op3: StreamOperator<A2, Y2, A3, Y3>,
    op4: StreamOperator<A3, Y3, A4, Y4>,
    op5: StreamOperator<A4, Y4, A5, Y5>,
    op6: StreamOperator<A5, Y5, A6, Y6>,
    op7: StreamOperator<A6, Y6, A7, Y7>,
    op8: StreamOperator<A7, Y7, A8, Y8>,
  ): CraftStream<A8, Y8>;
  <A1, Y1, A2, Y2, A3, Y3, A4, Y4, A5, Y5, A6, Y6, A7, Y7, A8, Y8, A9, Y9>(
    op1: StreamOperator<A, Y, A1, Y1>,
    op2: StreamOperator<A1, Y1, A2, Y2>,
    op3: StreamOperator<A2, Y2, A3, Y3>,
    op4: StreamOperator<A3, Y3, A4, Y4>,
    op5: StreamOperator<A4, Y4, A5, Y5>,
    op6: StreamOperator<A5, Y5, A6, Y6>,
    op7: StreamOperator<A6, Y6, A7, Y7>,
    op8: StreamOperator<A7, Y7, A8, Y8>,
    op9: StreamOperator<A8, Y8, A9, Y9>,
  ): CraftStream<A9, Y9>;
  <A1, Y1, A2, Y2, A3, Y3, A4, Y4, A5, Y5, A6, Y6, A7, Y7, A8, Y8, A9, Y9, A10, Y10>(
    op1: StreamOperator<A, Y, A1, Y1>,
    op2: StreamOperator<A1, Y1, A2, Y2>,
    op3: StreamOperator<A2, Y2, A3, Y3>,
    op4: StreamOperator<A3, Y3, A4, Y4>,
    op5: StreamOperator<A4, Y4, A5, Y5>,
    op6: StreamOperator<A5, Y5, A6, Y6>,
    op7: StreamOperator<A6, Y6, A7, Y7>,
    op8: StreamOperator<A7, Y7, A8, Y8>,
    op9: StreamOperator<A8, Y8, A9, Y9>,
    op10: StreamOperator<A9, Y9, A10, Y10>,
  ): CraftStream<A10, Y10>;
  <A1, Y1, A2, Y2, A3, Y3, A4, Y4, A5, Y5, A6, Y6, A7, Y7, A8, Y8, A9, Y9, A10, Y10, A11, Y11>(
    op1: StreamOperator<A, Y, A1, Y1>,
    op2: StreamOperator<A1, Y1, A2, Y2>,
    op3: StreamOperator<A2, Y2, A3, Y3>,
    op4: StreamOperator<A3, Y3, A4, Y4>,
    op5: StreamOperator<A4, Y4, A5, Y5>,
    op6: StreamOperator<A5, Y5, A6, Y6>,
    op7: StreamOperator<A6, Y6, A7, Y7>,
    op8: StreamOperator<A7, Y7, A8, Y8>,
    op9: StreamOperator<A8, Y8, A9, Y9>,
    op10: StreamOperator<A9, Y9, A10, Y10>,
    op11: StreamOperator<A10, Y10, A11, Y11>,
  ): CraftStream<A11, Y11>;
  <A1, Y1, A2, Y2, A3, Y3, A4, Y4, A5, Y5, A6, Y6, A7, Y7, A8, Y8, A9, Y9, A10, Y10, A11, Y11, A12, Y12>(
    op1: StreamOperator<A, Y, A1, Y1>,
    op2: StreamOperator<A1, Y1, A2, Y2>,
    op3: StreamOperator<A2, Y2, A3, Y3>,
    op4: StreamOperator<A3, Y3, A4, Y4>,
    op5: StreamOperator<A4, Y4, A5, Y5>,
    op6: StreamOperator<A5, Y5, A6, Y6>,
    op7: StreamOperator<A6, Y6, A7, Y7>,
    op8: StreamOperator<A7, Y7, A8, Y8>,
    op9: StreamOperator<A8, Y8, A9, Y9>,
    op10: StreamOperator<A9, Y9, A10, Y10>,
    op11: StreamOperator<A10, Y10, A11, Y11>,
    op12: StreamOperator<A11, Y11, A12, Y12>,
  ): CraftStream<A12, Y12>;
  <A1, Y1, A2, Y2, A3, Y3, A4, Y4, A5, Y5, A6, Y6, A7, Y7, A8, Y8, A9, Y9, A10, Y10, A11, Y11, A12, Y12, A13, Y13>(
    op1: StreamOperator<A, Y, A1, Y1>,
    op2: StreamOperator<A1, Y1, A2, Y2>,
    op3: StreamOperator<A2, Y2, A3, Y3>,
    op4: StreamOperator<A3, Y3, A4, Y4>,
    op5: StreamOperator<A4, Y4, A5, Y5>,
    op6: StreamOperator<A5, Y5, A6, Y6>,
    op7: StreamOperator<A6, Y6, A7, Y7>,
    op8: StreamOperator<A7, Y7, A8, Y8>,
    op9: StreamOperator<A8, Y8, A9, Y9>,
    op10: StreamOperator<A9, Y9, A10, Y10>,
    op11: StreamOperator<A10, Y10, A11, Y11>,
    op12: StreamOperator<A11, Y11, A12, Y12>,
    op13: StreamOperator<A12, Y12, A13, Y13>,
  ): CraftStream<A13, Y13>;
  <A1, Y1, A2, Y2, A3, Y3, A4, Y4, A5, Y5, A6, Y6, A7, Y7, A8, Y8, A9, Y9, A10, Y10, A11, Y11, A12, Y12, A13, Y13, A14, Y14>(
    op1: StreamOperator<A, Y, A1, Y1>,
    op2: StreamOperator<A1, Y1, A2, Y2>,
    op3: StreamOperator<A2, Y2, A3, Y3>,
    op4: StreamOperator<A3, Y3, A4, Y4>,
    op5: StreamOperator<A4, Y4, A5, Y5>,
    op6: StreamOperator<A5, Y5, A6, Y6>,
    op7: StreamOperator<A6, Y6, A7, Y7>,
    op8: StreamOperator<A7, Y7, A8, Y8>,
    op9: StreamOperator<A8, Y8, A9, Y9>,
    op10: StreamOperator<A9, Y9, A10, Y10>,
    op11: StreamOperator<A10, Y10, A11, Y11>,
    op12: StreamOperator<A11, Y11, A12, Y12>,
    op13: StreamOperator<A12, Y12, A13, Y13>,
    op14: StreamOperator<A13, Y13, A14, Y14>,
  ): CraftStream<A14, Y14>;
  (
    ...operators: ReadonlyArray<StreamOperator<any, any, any, any>>
  ): CraftStream<unknown, unknown>;
}
