// Generated by loadArchitectureGraph(). Do not edit.
export const architectureCatalog = {
  "version": 1,
  "graphHash": "208518c748d42837",
  "routes": [
    "",
    "**",
    "client-only",
    "data",
    "fallback",
    "request",
    "static"
  ],
  "services": [
    "BrowserCryptoService",
    "BrowserDocumentService",
    "BrowserHistoryService",
    "BrowserLocationService",
    "BrowserNavigatorService",
    "BrowserPerformanceService",
    "BrowserWindowService",
    "ConsoleService",
    "CookiesService",
    "CraftLogServerUrl",
    "GlobalPersisterHandlerService",
    "HostName",
    "LocalStoragePersister",
    "LocalStorageService",
    "ServerFunctionTransport",
    "SessionStoragePersister",
    "SessionStorageService",
    "StoragePersister",
    "StorageService",
    "api"
  ],
  "components": [
    "AiContextMenu",
    "AiSendDialog",
    "AnonymousComponent@800",
    "CraftRouterOutlet",
    "SsrClientOnlyPage",
    "SsrDataPage",
    "SsrFallbackPage",
    "SsrLabApp",
    "SsrNotFoundPage",
    "SsrOverviewPage",
    "SsrPipeline",
    "SsrRequestPage",
    "SsrStaticPage",
    "craftPending"
  ],
  "primitives": [
    "clientOnlyData",
    "copied",
    "counter",
    "deferredData",
    "instruction",
    "resolvedClientOnlyData",
    "resolvedDeferredData",
    "resolvedServerFunctionProducts",
    "resolvedSsrData",
    "serverFunctionProducts",
    "setCopied",
    "setInstruction",
    "ssrData"
  ],
  "sources": [
    "signalSource (signalSource)",
    "source$ (source$)"
  ],
  "serverFunctionFamilies": [
    "demo.products.list"
  ],
  "httpEndpoints": [],
  "uniques": [
    "\"demo.products.list\""
  ],
  "providers": [],
  "routeProviders": {},
  "componentProviders": {},
  "providedOn": {},
  "collisions": {
    "services": {},
    "components": {},
    "routes": {}
  },
  "browserBoundaryServices": [
    "BrowserCryptoService",
    "BrowserDocumentService",
    "BrowserHistoryService",
    "BrowserLocationService",
    "BrowserNavigatorService",
    "BrowserPerformanceService",
    "BrowserWindowService",
    "ConsoleService",
    "CookiesService",
    "LocalStorageService",
    "SessionStorageService"
  ],
  "scopes": {}
} as const;
export type ArchitectureCatalog = typeof architectureCatalog;
