// Generated by loadArchitectureGraph(). Do not edit.
export const architectureCatalog = {
  "version": 1,
  "graphHash": "f7a92cf1de2fead0",
  "routes": [
    "",
    "**",
    "client-only",
    "data",
    "fallback",
    "request",
    "static"
  ],
  "services": [
    "BrowserCryptoService",
    "BrowserDocumentService",
    "BrowserHistoryService",
    "BrowserLocationService",
    "BrowserNavigatorService",
    "BrowserPerformanceService",
    "BrowserWindowService",
    "ConsoleService",
    "CookiesService",
    "CraftLogServerUrl",
    "GlobalPersisterHandlerService",
    "HostName",
    "LocalStoragePersister",
    "LocalStorageService",
    "MiddlewareExecutionScope",
    "ServerFunctionTransport",
    "SessionStoragePersister",
    "SessionStorageService",
    "StoragePersister",
    "StorageService",
    "api"
  ],
  "components": [
    "AiContextMenu",
    "AiSendContextChat",
    "AiSendContextLauncher",
    "AiSendDialog",
    "AnonymousComponent@setupCraftDirectiveTemplateTestImpl/synthetic",
    "CraftRouterOutlet",
    "SsrClientOnlyPage",
    "SsrDataPage",
    "SsrFallbackPage",
    "SsrLabApp",
    "SsrNotFoundPage",
    "SsrOverviewPage",
    "SsrPipeline",
    "SsrRequestPage",
    "SsrStaticPage",
    "craftPending"
  ],
  "primitives": [
    "busy",
    "captureError",
    "captureInProgress",
    "clientOnlyData",
    "copied",
    "counter",
    "deferredData",
    "error",
    "instruction",
    "panelOffset",
    "promptOptions",
    "resolvedClientOnlyData",
    "resolvedDeferredData",
    "resolvedServerFunctionProducts",
    "resolvedSsrData",
    "serverFunctionProducts",
    "setBusy",
    "setCaptureError",
    "setCaptureInProgress",
    "setCopied",
    "setError",
    "setPanelOffset",
    "setStatus",
    "ssrData",
    "status"
  ],
  "sources": [
    "signalSource (signalSource)",
    "source$ (source$)"
  ],
  "serverFunctionFamilies": [
    "demo.products.list"
  ],
  "httpEndpoints": [
    {
      "method": "GET",
      "url": "/api/deferred"
    }
  ],
  "uniques": [
    "\"demo.products.list\""
  ],
  "providers": [],
  "routeProviders": {},
  "componentProviders": {},
  "providedOn": {},
  "collisions": {
    "services": {
      "MiddlewareExecutionScope": [
        "libs/core/src/lib/server-function-middleware.ts",
        "libs/core/src/lib/server-function-middleware.ts"
      ]
    },
    "components": {},
    "routes": {}
  },
  "browserBoundaryServices": [
    "BrowserCryptoService",
    "BrowserDocumentService",
    "BrowserHistoryService",
    "BrowserLocationService",
    "BrowserNavigatorService",
    "BrowserPerformanceService",
    "BrowserWindowService",
    "ConsoleService",
    "CookiesService",
    "LocalStorageService",
    "SessionStorageService"
  ],
  "scopes": {}
} as const;
export type ArchitectureCatalog = typeof architectureCatalog;
