/**
 * The "send context to AI" dialog.
 *
 * A visibility toggle is not a style: the success and warning notices use the
 * `hidden` attribute, and only the copy button's "done" state is an axis.
 */
import {
  accentColor,
  alignItems,
  bg,
  borderColor,
  borderStyle,
  borderWidth,
  boxSizing,
  caretColor,
  color,
  craftBase,
  craftStyles,
  cursor,
  defineStateAxis,
  display,
  flexDirection,
  fontFamily,
  fontSize,
  fontWeight,
  gap,
  global,
  height,
  inlineSize,
  inset,
  interaction,
  justifyContent,
  lineHeight,
  margin,
  marginInlineEnd,
  math,
  maxHeight,
  maxWidth,
  minHeight,
  monospaceStack,
  num,
  opacity,
  p,
  position,
  prop,
  provides,
  pseudo,
  px,
  py,
  radii,
  radius,
  resize,
  scrollPort,
  set,
  shadow,
  space,
  transitions,
  unit,
  when,
  easing,
} from '@craft-ts/style';
import { ai, craftAi, overlayText } from './ai-overlay.style';

/** Drives `data-craftAiCopy` on the copy button. */
export const copyState = defineStateAxis('craftAiCopy', ['done']);

const notice = [
  fontSize(unit.px(12)),
  py(unit.px(6)),
  px(space(2)),
  borderWidth(unit.px(1)),
  borderStyle.solid,
  radius(radii.sm),
];

export const aiDialog = craftStyles(
  'craftAiDialog',
  {
    overlay: [
      ...overlayText,
      position.fixed,
      inset(space(0)),
      inlineSize(unit.pct(100)),
      maxWidth.none,
      height(unit.pct(100)),
      maxHeight.none,
      boxSizing.borderBox,
      margin(space(0)),
      borderStyle.none,
      bg(craftAi.surface.transparent),
      p(space(6)),
      display.flex,
      alignItems.center,
      justifyContent.center,
      pseudo.backdrop([bg(ai['overlay-backdrop'])]),
    ],
    card: [
      bg(ai.bg),
      radius(radii.lg),
      shadow({ y: unit.px(20), blur: unit.px(50), color: ai.shadow }),
      inlineSize(math.min(unit.px(560), unit.pct(100))),
      maxHeight(unit.vh(90)),
      provides(scrollPort.block),
      py(space(4)),
      px(space(5)),
      display.flex,
      flexDirection.column,
      gap(space(3)),
    ],
    header: [
      display.flex,
      alignItems.center,
      justifyContent.spaceBetween,
      fontSize(unit.px(14)),
    ],
    close: [
      bg(craftAi.surface.transparent),
      borderStyle.none,
      fontSize(unit.px(20)),
      lineHeight(num(1)),
      cursor.pointer,
      color(ai['text-muted']),
    ],
    context: [
      bg(ai.surface),
      borderWidth(unit.px(1)),
      borderStyle.solid,
      borderColor(ai['border-subtle']),
      radius(radii.md),
      py(space(2)),
      px(unit.px(10)),
      fontFamily(monospaceStack),
      fontSize(unit.px(12)),
      display.grid,
      gap(space(1)),
    ],
    contextLabel: [color(ai['text-muted']), marginInlineEnd(space(1))],
    label: [fontWeight(num(600))],
    options: [
      display.grid,
      gap(unit.px(7)),
      margin(space(0)),
      p(unit.px(10)),
      borderWidth(unit.px(1)),
      borderStyle.solid,
      borderColor(ai['border-subtle']),
      radius(radii.md),
    ],
    legend: [px(space(1)), fontWeight(num(600))],
    option: [
      display.flex,
      alignItems.flexStart,
      gap(space(2)),
      lineHeight(num(1.35)),
      cursor.pointer,
    ],
    checkbox: [margin(space(0)), accentColor(ai.accent)],
    warning: [
      ...notice,
      color(ai.warning),
      bg(ai['warning-bg']),
      borderColor(ai['warning-border']),
    ],
    textarea: [
      inlineSize(unit.pct(100)),
      boxSizing.borderBox,
      global.inherit(prop.fontFamily),
      fontSize(unit.px(13)),
      py(space(2)),
      px(unit.px(10)),
      borderWidth(unit.px(1)),
      borderStyle.solid,
      borderColor(ai.border),
      radius(radii.md),
      resize.vertical,
      minHeight(unit.px(96)),
      color(ai.text),
      bg(ai['control-bg']),
      caretColor(ai.text),
      // The ring the foundation draws, pulled inside the field's border.
      set(craftBase.focusOffset, unit.px(-1)),
      pseudo.placeholder([color(ai['text-muted']), opacity(num(1))]),
    ],
    success: [
      bg(ai['success-bg']),
      borderWidth(unit.px(1)),
      borderStyle.solid,
      borderColor(ai['success-border']),
      color(ai['success-text']),
      py(space(2)),
      px(unit.px(10)),
      radius(radii.md),
    ],
    footer: [display.flex, justifyContent.flexEnd, gap(space(2))],
    cancel: [
      bg(ai['control-bg']),
      borderWidth(unit.px(1)),
      borderStyle.solid,
      borderColor(ai.border),
      py(unit.px(6)),
      px(space(3)),
      radius(radii.md),
      color(ai.text),
      cursor.pointer,
    ],
    copy: [
      display.flex,
      alignItems.center,
      gap(unit.px(6)),
      bg(ai.accent),
      color(ai['on-accent']),
      borderStyle.none,
      py(unit.px(6)),
      px(unit.px(14)),
      radius(radii.md),
      cursor.pointer,
      fontWeight(num(500)),
      ...transitions([prop.backgroundColor], {
        duration: unit.ms(150),
        easing: easing.ease,
      }),
      when(copyState.done, [bg(ai['success-fill'])]),
      when(interaction.disabled, [opacity(num(0.6)), cursor.notAllowed]),
    ],
  },
  { axes: [copyState, interaction], isolated: true },
);
