/**
 * The session chat: targets, timeline, instruction and the prompt options.
 *
 * Every variation the template used to assemble as a class string is an axis
 * here: a button's tone (`data-craftAiButton`) and an event's phase
 * (`data-craftAiPhase`). Where the panel was dragged is a typed variable the
 * template writes with `assign(...)`.
 */
import {
  accentColor,
  alignItems,
  bg,
  borderColor,
  borderStyle,
  borderWidth,
  boxSizing,
  caretColor,
  clipOverflow,
  color,
  columnGap,
  craftBase,
  craftStyles,
  cssVars,
  cursor,
  defineStateAxis,
  display,
  flexDirection,
  flexGrow,
  flexWrap,
  fontFamily,
  fontSize,
  fontWeight,
  gap,
  global,
  gridTemplateColumns,
  inlineSize,
  inset,
  interaction,
  justifyContent,
  kind,
  left,
  letterSpacing,
  lineHeight,
  listStyleType,
  margin,
  math,
  maxHeight,
  maxWidth,
  monospaceStack,
  num,
  opacity,
  p,
  pointerEvents,
  position,
  prop,
  provides,
  pseudo,
  px,
  py,
  radii,
  radius,
  resize,
  rowGap,
  scrollPort,
  set,
  shadow,
  space,
  textOverflow,
  textTransform,
  top,
  touchAction,
  tracks,
  unit,
  userSelect,
  when,
  whiteSpace,
} from '@craft-ts/style';
import { ai, craftAi, overlayText } from './ai-overlay.style';

/** Where the reviewer dragged the panel, written with `assign(...)`. */
export const chatOffset = cssVars('craftAiChat', {
  x: kind.length(unit.px(0)),
  y: kind.length(unit.px(0)),
});

/** A chat button's tone. Drives `data-craftAiButton`. */
export const buttonTone = defineStateAxis('craftAiButton', [
  'primary',
  'recording',
]);

/** A timeline event's phase. Drives `data-craftAiPhase`. */
export const eventPhase = defineStateAxis('craftAiPhase', [
  'failed',
  'succeeded',
  'started',
  'emitted',
]);

const heading = [
  fontSize(unit.px(11)),
  fontWeight(num(600)),
  letterSpacing(unit.em(0.04)),
  textTransform.uppercase,
  color(ai['text-muted']),
];

const ellipsis = [
  clipOverflow.inline,
  textOverflow.ellipsis,
  whiteSpace.nowrap,
];

export const aiChat = craftStyles(
  'craftAiChat',
  {
    overlay: [
      ...overlayText,
      position.fixed,
      inset(space(0)),
      display.flex,
      alignItems.flexEnd,
      justifyContent.flexEnd,
      p(space(5)),
      pointerEvents.none,
    ],
    panel: [
      position.relative,
      left(chatOffset.x),
      top(chatOffset.y),
      pointerEvents.auto,
      display.flex,
      flexDirection.column,
      gap(space(3)),
      inlineSize(math.min(unit.px(460), unit.pct(100))),
      maxHeight(math.min(unit.px(760), unit.vh(88))),
      provides(scrollPort.block),
      bg(ai.bg),
      borderWidth(unit.px(1)),
      borderStyle.solid,
      borderColor(ai['border-subtle']),
      radius(radii.xl),
      shadow({ y: unit.px(20), blur: unit.px(60), color: ai.shadow }),
      p(space(4)),
    ],
    header: [
      display.flex,
      justifyContent.spaceBetween,
      alignItems.center,
      gap(space(2)),
      cursor.grab,
      // Let the pointer handlers own touch drags instead of scrolling.
      touchAction.none,
      userSelect.none,
      when(interaction.active, [cursor.grabbing]),
    ],
    title: [fontSize(unit.px(14)), fontWeight(num(600))],
    close: [
      bg(craftAi.surface.transparent),
      borderStyle.none,
      fontSize(unit.px(20)),
      lineHeight(num(1)),
      py(space(0)),
      px(space(1)),
      color(ai['text-muted']),
      cursor.pointer,
    ],
    section: [display.flex, flexDirection.column, gap(unit.px(6))],
    sectionHead: [
      display.flex,
      alignItems.center,
      justifyContent.spaceBetween,
      gap(space(2)),
      ...heading,
    ],
    targets: [
      display.flex,
      flexWrap.wrap,
      gap(unit.px(6)),
      margin(space(0)),
      p(space(0)),
      listStyleType.none,
    ],
    target: [
      display.inlineFlex,
      alignItems.center,
      gap(unit.px(6)),
      maxWidth(unit.pct(100)),
      bg(ai['surface-accent']),
      color(ai['accent-text']),
      radius(radii.full),
      py(unit.px(3)),
      px(unit.px(10)),
      fontFamily(monospaceStack),
      fontSize(unit.px(11)),
    ],
    targetLabel: [...ellipsis],
    targetRemove: [
      borderStyle.none,
      bg(craftAi.surface.transparent),
      global.inherit(prop.color),
      cursor.pointer,
      fontSize(unit.px(13)),
      lineHeight(num(1)),
      py(unit.px(2)),
      px(space(1)),
      radius(radii.full),
      when(interaction.hover, [bg(ai['accent-soft'])]),
    ],
    empty: [margin(space(0)), color(ai['text-muted']), fontSize(unit.px(12))],
    timeline: [
      margin(space(0)),
      py(unit.px(6)),
      px(space(2)),
      listStyleType.none,
      maxHeight(unit.px(190)),
      provides(scrollPort.block),
      bg(ai.surface),
      borderWidth(unit.px(1)),
      borderStyle.solid,
      borderColor(ai['border-subtle']),
      radius(radii.md),
      fontFamily(monospaceStack),
      fontSize(unit.px(11)),
      lineHeight(num(1.6)),
    ],
    event: [display.flex, gap(unit.px(6)), whiteSpace.nowrap],
    eventTime: [color(ai['text-muted'])],
    eventName: [clipOverflow.inline, textOverflow.ellipsis],
    phase: [
      textTransform.uppercase,
      fontSize(unit.px(10)),
      letterSpacing(unit.em(0.03)),
      when(eventPhase.failed, [color(ai.danger)]),
      when(eventPhase.succeeded, [color(ai.success)]),
      when(eventPhase.started, [color(ai.warning)]),
      when(eventPhase.emitted, [color(ai['phase-emitted'])]),
    ],
    textarea: [
      inlineSize(unit.pct(100)),
      boxSizing.borderBox,
      resize.vertical,
      global.inherit(prop.font),
      borderWidth(unit.px(1)),
      borderStyle.solid,
      borderColor(ai.border),
      radius(radii.md),
      py(space(2)),
      px(unit.px(10)),
      color(ai.text),
      bg(ai['control-bg']),
      caretColor(ai.text),
      set(craftBase.focusOffset, unit.px(-1)),
      pseudo.placeholder([color(ai['text-muted']), opacity(num(1))]),
    ],
    options: [
      display.grid,
      gridTemplateColumns(tracks.autoFit(unit.px(170))),
      rowGap(unit.px(6)),
      columnGap(space(3)),
      margin(space(0)),
      p(unit.px(10)),
      borderWidth(unit.px(1)),
      borderStyle.solid,
      borderColor(ai['border-subtle']),
      radius(radii.md),
    ],
    legend: [...heading, px(space(1))],
    option: [
      display.flex,
      alignItems.center,
      gap(unit.px(6)),
      fontSize(unit.px(12)),
    ],
    checkbox: [accentColor(ai.accent)],
    actions: [display.flex, gap(space(2)), flexWrap.wrap, alignItems.center],
    spacer: [flexGrow(num(1))],
    button: [
      global.inherit(prop.font),
      fontSize(unit.px(12)),
      borderWidth(unit.px(1)),
      borderStyle.solid,
      borderColor(ai.border),
      bg(ai['control-bg']),
      color(ai.text),
      radius(radii.md),
      py(unit.px(7)),
      px(unit.px(11)),
      cursor.pointer,
      when(interaction.hover, [bg(ai.surface)]),
      when(buttonTone.primary, [
        bg(ai.accent),
        borderColor(ai.accent),
        color(ai['on-accent']),
        when(interaction.hover, [bg(ai['accent-hover'])]),
      ]),
      when(buttonTone.recording, [
        bg(ai['danger-fill']),
        borderColor(ai['danger-fill']),
        color(ai['on-accent']),
      ]),
      when(interaction.disabled, [opacity(num(0.55)), cursor.notAllowed]),
    ],
    success: [margin(space(0)), color(ai.success), fontSize(unit.px(12))],
    warning: [margin(space(0)), color(ai.warning), fontSize(unit.px(12))],
  },
  { axes: [buttonTone, eventPhase, interaction], isolated: true },
);
