/**
 * The typography of a page: what a Markdown paragraph, heading, list, link,
 * table and inline code look like. Written once, as sheets; the renderer only
 * ever picks a class, it never assembles one.
 */
import {
  bg,
  borderBlockStartColor,
  borderBlockStartStyle,
  borderBlockStartWidth,
  borderCollapse,
  borderColor,
  borderInlineStartColor,
  borderInlineStartStyle,
  borderInlineStartWidth,
  borderStyle,
  borderWidth,
  color,
  craftStyles,
  cursor,
  defineStateAxis,
  display,
  flexWrap,
  font,
  fontFamily,
  fontSize,
  fontWeight,
  gap,
  ident,
  inlineSize,
  interaction,
  justifyContent,
  letterSpacing,
  lineHeight,
  lineWidth,
  listStyleType,
  marginBlock,
  marginBlockEnd,
  marginBlockStart,
  marginInline,
  marginInlineStart,
  maxInlineSize,
  num,
  p,
  paddingInlineStart,
  provides,
  px,
  py,
  radii,
  radius,
  scrollPort,
  space,
  text,
  textAlign,
  textDecoration,
  unit,
  when,
} from '@craft-ts/style';
import { arriving, display as displayFont, mono, theme } from '../foundation/herbier.style.ts';

/** How a row of blocks lays its children out. A plain row is `start`. */
export const layout = defineStateAxis('layout', ['between', 'end'] as const);

const heading = (size: ReturnType<typeof unit.rem>) => [
  fontFamily(displayFont),
  fontSize(size),
  lineHeight(num(1.2)),
  fontWeight.bold,
  letterSpacing(unit.em(-0.01)),
  color(theme.inkStrong),
];

export const proseUi = craftStyles('docProse', {
  page: [
    display.block,
    maxInlineSize(unit.rem(48)),
    marginInline.auto,
    p(space(6)),
    color(theme.ink),
    ...font(text.base),
    lineHeight(num(1.7)),
  ],
  h1: [...heading(unit.rem(2.25)), marginBlockEnd(space(6))],
  h2: [
    ...heading(unit.rem(1.5)),
    marginBlockStart(space(12)),
    marginBlockEnd(space(4)),
    py(space(2)),
    borderBlockStartWidth(lineWidth.hairline),
    borderBlockStartStyle.solid,
    borderBlockStartColor(theme.line),
  ],
  h3: [
    ...heading(unit.rem(1.25)),
    marginBlockStart(space(8)),
    marginBlockEnd(space(3)),
  ],
  h4: [
    ...heading(unit.rem(1.0625)),
    marginBlockStart(space(6)),
    marginBlockEnd(space(2)),
  ],
  anchor: [
    marginInlineStart(space(2)),
    color(theme.inkMuted),
    textDecoration.none,
    when(interaction.hover, [color(theme.link)]),
  ],
  paragraph: [marginBlock(space(4))],
  link: [
    color(theme.link),
    textDecoration.underline,
    when(interaction.hover, [color(theme.inkStrong)]),
  ],
  inlineCode: [
    fontFamily(mono),
    fontSize(unit.em(0.875)),
    px(space(1)),
    bg(theme.sunken),
    color(theme.inkStrong),
    radius(radii.sm),
  ],
  kbd: [
    fontFamily(mono),
    fontSize(unit.em(0.8125)),
    px(space(2)),
    bg(theme.raised),
    color(theme.inkStrong),
    borderWidth(lineWidth.hairline),
    borderStyle.solid,
    borderColor(theme.lineStrong),
    radius(radii.md),
  ],
  list: [
    marginBlock(space(4)),
    paddingInlineStart(space(6)),
    listStyleType(ident('disc')),
  ],
  orderedList: [
    marginBlock(space(4)),
    paddingInlineStart(space(6)),
    listStyleType(ident('decimal')),
  ],
  item: [marginBlock(space(1))],
  quote: [
    marginBlock(space(4)),
    paddingInlineStart(space(4)),
    borderInlineStartWidth(lineWidth.thick),
    borderInlineStartStyle.solid,
    borderInlineStartColor(theme.lineStrong),
    color(theme.inkMuted),
  ],
  rule: [
    marginBlock(space(8)),
    borderBlockStartWidth(lineWidth.hairline),
    borderBlockStartStyle.solid,
    borderBlockStartColor(theme.line),
  ],
  tableWrap: [
    display.block,
    marginBlock(space(4)),
    provides(scrollPort.inline),
  ],
  table: [
    inlineSize(unit.pct(100)),
    borderCollapse.collapse,
    ...font(text.sm),
  ],
  th: [
    py(space(2)),
    px(space(3)),
    textAlign.start,
    fontWeight.bold,
    color(theme.inkStrong),
    bg(theme.sunken),
    borderBlockStartWidth(lineWidth.hairline),
    borderBlockStartStyle.solid,
    borderBlockStartColor(theme.line),
  ],
  td: [
    py(space(2)),
    px(space(3)),
    borderBlockStartWidth(lineWidth.hairline),
    borderBlockStartStyle.solid,
    borderBlockStartColor(theme.line),
  ],
  row: [
    display.flex,
    flexWrap.wrap,
    gap(space(4)),
    marginBlockStart(space(8)),
    when(layout.between, [justifyContent.spaceBetween]),
    when(layout.end, [justifyContent.flexEnd]),
  ],
  figure: [display.block, maxInlineSize(unit.pct(100)), marginBlock(space(6))],
  details: [
    marginBlock(space(4)),
    borderWidth(lineWidth.hairline),
    borderStyle.solid,
    borderColor(theme.line),
    radius(radii.xl),
    bg(theme.raised),
    ...arriving,
  ],
  summary: [
    display.block,
    py(space(3)),
    px(space(4)),
    cursor.pointer,
    fontWeight.bold,
    color(theme.inkStrong),
  ],
  detailsBody: [px(space(4)), color(theme.ink)],
  raw: [display.block],
});
