/**
 * The typography of a page: what a Markdown paragraph, heading, list, link,
 * table and inline code look like. Written once, as sheets; the renderer only
 * ever picks a class, it never assembles one.
 *
 * Newsreader sets the headings, the captions and the pull quote; Hanken
 * Grotesk sets the body; Geist Mono sets what is code. A quotation is closed by
 * a hairline above and below — there is no rule down its side.
 */
import {
  bg,
  borderBlockEndColor,
  borderBlockEndStyle,
  borderBlockEndWidth,
  borderBlockStartColor,
  borderBlockStartStyle,
  borderBlockStartWidth,
  borderCollapse,
  borderColor,
  borderStyle,
  borderWidth,
  color,
  craftStyles,
  cursor,
  defineStateAxis,
  display,
  flexWrap,
  font,
  fontFamily,
  fontSize,
  fontStyle,
  fontWeight,
  gap,
  ident,
  inlineSize,
  interaction,
  justifyContent,
  letterSpacing,
  lineHeight,
  lineWidth,
  listStyleType,
  marginBlock,
  marginBlockEnd,
  marginBlockStart,
  marginInline,
  marginInlineStart,
  maxInlineSize,
  num,
  paddingInlineStart,
  provides,
  px,
  py,
  radii,
  radius,
  scrollPort,
  space,
  text,
  textAlign,
  textDecoration,
  textDecorationThickness,
  textTransform,
  textUnderlineOffset,
  unit,
  when,
} from '@craft-ts/style';
import {
  arriving,
  displayFont,
  displaySize,
  monoFont,
  sansFont,
  theme,
  weight,
} from '../foundation/herbier.style.ts';

/** How a row of blocks lays its children out. A plain row is `start`. */
export const layout = defineStateAxis('layout', ['between', 'end'] as const);

const headingStyle = (size: ReturnType<typeof unit.rem>, height: number) => [
  fontFamily(displayFont),
  fontSize(size),
  lineHeight(num(height)),
  fontWeight(weight.medium),
  color(theme.ink),
];

/** The small capitals of a label: spaced, semibold, quiet. */
const label = [
  fontFamily(sansFont),
  ...font(text.xs),
  fontWeight(weight.semibold),
  letterSpacing(unit.em(0.18)),
  textTransform.uppercase,
];

export const proseUi = craftStyles('docProse', {
  page: [
    display.block,
    maxInlineSize(unit.rem(48)),
    marginInline.auto,
    // The frame owns the sides; the page only owns its own top and bottom.
    py(space(2)),
    fontFamily(sansFont),
    color(theme.ink),
    ...font(text.base),
    lineHeight(num(1.65)),
  ],
  h1: [
    ...headingStyle(displaySize.lead, 0.98),
    letterSpacing(unit.em(-0.035)),
    marginBlockEnd(space(6)),
  ],
  h2: [
    ...headingStyle(unit.rem(2.125), 1.1),
    letterSpacing(unit.em(-0.02)),
    marginBlockStart(space(12)),
    marginBlockEnd(space(4)),
  ],
  h3: [
    ...headingStyle(unit.rem(1.4375), 1.2),
    marginBlockStart(space(8)),
    marginBlockEnd(space(3)),
  ],
  h4: [
    fontFamily(sansFont),
    fontSize(unit.rem(1.0625)),
    lineHeight(num(1.3)),
    fontWeight(weight.semibold),
    color(theme.ink),
    marginBlockStart(space(6)),
    marginBlockEnd(space(2)),
  ],
  anchor: [
    marginInlineStart(space(2)),
    fontFamily(sansFont),
    fontSize(unit.em(0.55)),
    fontWeight(weight.regular),
    color(theme.inkSubtle),
    textDecoration.none,
    when(interaction.hover, [color(theme.link)]),
  ],
  paragraph: [marginBlock(space(4))],
  link: [
    color(theme.link),
    textDecoration.underline,
    textUnderlineOffset(unit.px(4)),
    textDecorationThickness(unit.px(1)),
    when(interaction.hover, [
      color(theme.ink),
      textDecorationThickness(unit.px(2)),
    ]),
  ],
  inlineCode: [
    fontFamily(monoFont),
    fontSize(unit.em(0.88)),
    px(unit.rem(0.375)),
    bg(theme.selected),
    color(theme.link),
    radius(radii.sm),
  ],
  kbd: [
    display.inlineFlex,
    fontFamily(monoFont),
    fontSize(unit.rem(0.75)),
    fontWeight(weight.medium),
    px(unit.rem(0.4375)),
    bg(theme.raised),
    color(theme.ink),
    borderWidth(lineWidth.hairline),
    borderStyle.solid,
    borderColor(theme.inkSubtle),
    borderBlockEndWidth(lineWidth.thick),
    radius(radii.sm),
  ],
  list: [
    marginBlock(space(4)),
    paddingInlineStart(space(6)),
    listStyleType(ident('disc')),
  ],
  orderedList: [
    marginBlock(space(4)),
    paddingInlineStart(space(6)),
    listStyleType(ident('decimal')),
  ],
  item: [marginBlock(space(1))],
  quote: [
    marginBlock(space(6)),
    py(space(4)),
    fontFamily(displayFont),
    fontStyle.italic,
    fontSize(unit.rem(1.3125)),
    lineHeight(num(1.4)),
    color(theme.ink),
    borderBlockStartWidth(lineWidth.hairline),
    borderBlockStartStyle.solid,
    borderBlockStartColor(theme.lineStrong),
    borderBlockEndWidth(lineWidth.hairline),
    borderBlockEndStyle.solid,
    borderBlockEndColor(theme.lineStrong),
  ],
  rule: [
    marginBlock(space(8)),
    borderBlockStartWidth(lineWidth.hairline),
    borderBlockStartStyle.solid,
    borderBlockStartColor(theme.line),
  ],
  tableWrap: [
    display.block,
    marginBlock(space(5)),
    bg(theme.raised),
    borderWidth(lineWidth.hairline),
    borderStyle.solid,
    borderColor(theme.line),
    radius(radii.md),
    provides(scrollPort.inline),
  ],
  table: [
    inlineSize(unit.pct(100)),
    borderCollapse.collapse,
    ...font(text.sm),
  ],
  th: [
    py(space(2)),
    px(space(5)),
    textAlign.start,
    ...label,
    color(theme.inkSubtle),
    borderBlockEndWidth(lineWidth.hairline),
    borderBlockEndStyle.solid,
    borderBlockEndColor(theme.inkSubtle),
  ],
  td: [
    py(space(3)),
    px(space(5)),
    borderBlockStartWidth(lineWidth.hairline),
    borderBlockStartStyle.solid,
    borderBlockStartColor(theme.line),
  ],
  row: [
    display.flex,
    flexWrap.wrap,
    gap(space(4)),
    marginBlockStart(space(8)),
    when(layout.between, [justifyContent.spaceBetween]),
    when(layout.end, [justifyContent.flexEnd]),
  ],
  figure: [display.block, maxInlineSize(unit.pct(100)), marginBlock(space(6))],
  caption: [
    display.block,
    marginBlockStart(space(2)),
    fontFamily(displayFont),
    fontStyle.italic,
    ...font(text.sm),
    color(theme.inkSubtle),
  ],
  details: [
    marginBlock(space(4)),
    borderWidth(lineWidth.hairline),
    borderStyle.solid,
    borderColor(theme.line),
    radius(radii.md),
    bg(theme.raised),
    ...arriving,
  ],
  summary: [
    display.block,
    py(space(3)),
    px(space(4)),
    cursor.pointer,
    fontWeight(weight.semibold),
    color(theme.ink),
  ],
  detailsBody: [px(space(4)), color(theme.ink)],
  raw: [display.block],
});
