/**
 * The folder-layout proposal: two trees side by side, one row per file or
 * folder, coloured by what the proposal does to it.
 *
 * A row's kind, status and collision are attributes (`data-rowKind`,
 * `data-rowStatus`, `data-rowCollision`), bound on the row and on the pieces
 * whose look depends on them. `data-rowLinked` and `data-rowLocated` are
 * written by the browser adapter on hover and on click. The depth is a
 * variable, so the indent and the vertical guides follow it.
 */
import {
  alignItems,
  at,
  bg,
  bgImage,
  bgPosition,
  bgSize,
  backgroundRepeat,
  blockSize,
  borderBlockEndColor,
  borderBlockEndStyle,
  borderBlockEndWidth,
  borderColor,
  borderStyle,
  borderWidth,
  clipOverflow,
  color,
  craftStyles,
  cssVars,
  cursor,
  defineBreakpoints,
  defineStateAxis,
  display,
  flex,
  flexDirection,
  flexWrap,
  fontFamily,
  fontSize,
  fontWeight,
  gap,
  gradient,
  gridTemplateColumns,
  inlineSize,
  interaction,
  justifyContent,
  kind,
  lineWidth,
  listStyleType,
  marginBlock,
  marginInline,
  marginInlineStart,
  math,
  maxBlockSize,
  minBlockSize,
  minWidth,
  monospaceStack,
  num,
  overflowWrap,
  overscrollBehavior,
  p,
  paddingBlockEnd,
  paddingBlockStart,
  paddingInlineEnd,
  paddingInlineStart,
  placeItems,
  provides,
  px,
  py,
  radii,
  radius,
  scrollPort,
  shadow,
  space,
  textAlign,
  textDecorationColor,
  textDecorationLine,
  textOverflow,
  tracks,
  unit,
  when,
  whiteSpace,
} from '@craft-ts/style';
import { reviewFont, reviewUi, theme } from './review-app.style';

export const rowKind = defineStateAxis('rowKind', ['folder', 'file']);
export const rowStatus = defineStateAxis('rowStatus', [
  'unchanged',
  'moved',
  'created',
  'deleted',
]);
export const rowCollision = defineStateAxis('rowCollision', ['true']);
export const rowLinked = defineStateAxis('rowLinked', ['true']);
export const rowLocated = defineStateAxis('rowLocated', ['true']);
export const legendTone = defineStateAxis('legendTone', [
  'moved',
  'deleted',
  'created',
  'collision',
]);

/** One level of indent. The guides and the padding are multiples of it. */
export const TREE_INDENT_PX = 14;

/** The depth of a row, written with `assign(...)` as two lengths. */
export const treeVars = cssVars('folderTree', {
  indent: kind.length(unit.px(8)),
  guides: kind.length(unit.px(1)),
});

const bp = defineBreakpoints({ wide: at.minInlineSize(unit.px(901)) });
const transparent = reviewUi.surface.transparent;

const pill = [radius(radii.full), fontSize(unit.px(11)), whiteSpace.nowrap];

export const folderLayout = craftStyles('folderLayout', {
  view: [
    display.grid,
    gap(unit.px(14)),
    p(unit.px(18)),
    borderWidth(lineWidth.hairline),
    borderStyle.solid,
    borderColor(theme.line),
    radius(unit.px(12)),
    bg(theme.surfaceSunken),
  ],
  summary: [
    display.flex,
    flexWrap.wrap,
    alignItems.baseline,
    justifyContent.spaceBetween,
    gap(unit.px(4)),
    color(theme.textBright),
  ],
  muted: [color(theme.textMuted)],
  legend: [display.flex, flexWrap.wrap, alignItems.center, gap(unit.px(6))],
  legendItem: [
    ...pill,
    py(unit.px(2)),
    px(unit.px(8)),
    fontWeight(num(600)),
    when(legendTone.moved, [color(theme.accentLink), bg(theme.accentBg)]),
    when(legendTone.deleted, [color(theme.dangerText), bg(theme.dangerBg)]),
    when(legendTone.created, [color(theme.createdText), bg(theme.createdBg)]),
    when(legendTone.collision, [color(theme.warnText), bg(theme.warnBg)]),
  ],
  hint: [marginInlineStart.auto, fontSize(unit.px(11)), color(theme.textMuted)],
  trees: [
    display.grid,
    gap(unit.px(12)),
    when(bp.wide, [gridTemplateColumns(tracks.equal(2))]),
  ],
  tree: [
    display.flex,
    flexDirection.column,
    minWidth(unit.px(0)),
    clipOverflow.block,
    clipOverflow.inline,
    borderWidth(lineWidth.hairline),
    borderStyle.solid,
    borderColor(theme.line),
    radius(unit.px(10)),
    bg(theme.surface),
  ],
  treeHeading: [
    display.flex,
    alignItems.center,
    justifyContent.spaceBetween,
    gap(unit.px(8)),
    paddingBlockStart(unit.px(8)),
    paddingBlockEnd(unit.px(8)),
    paddingInlineStart(unit.px(12)),
    paddingInlineEnd(unit.px(10)),
    borderBlockEndWidth(lineWidth.hairline),
    borderBlockEndStyle.solid,
    borderBlockEndColor(theme.line),
    color(theme.textBright),
  ],
  treeTitle: [display.grid, gap(unit.px(1)), minWidth(unit.px(0))],
  treeName: [whiteSpace.nowrap],
  treeRoot: [
    minWidth(unit.px(0)),
    clipOverflow.inline,
    textOverflow.ellipsis,
    whiteSpace.nowrap,
    fontFamily(monospaceStack),
    fontSize(unit.px(11)),
    color(theme.textDim),
  ],
  treeActions: [display.flex, flex.none, gap(unit.px(2))],
  treeAction: [
    py(unit.px(3)),
    px(unit.px(7)),
    borderWidth(lineWidth.hairline),
    borderStyle.solid,
    borderColor(transparent),
    radius(unit.px(6)),
    fontSize(unit.px(11)),
    whiteSpace.nowrap,
    cursor.pointer,
    color(theme.textMuted),
    bg(transparent),
    when(interaction.hover, [
      borderColor(theme.lineStrong),
      bg(theme.surfaceRaised),
      color(theme.textBright),
    ]),
  ],
  treeList: [
    maxBlockSize(math.min(unit.vh(68), unit.px(640))),
    paddingBlockStart(unit.px(6)),
    paddingBlockEnd(unit.px(10)),
    provides(scrollPort.block),
    overscrollBehavior.contain,
    listStyleType.none,
    fontFamily(monospaceStack),
    fontSize(unit.px(12)),
  ],
  row: [
    display.grid,
    gridTemplateColumns(
      tracks.list(unit.px(18), tracks.minmax(unit.px(0), tracks.fr(1))),
    ),
    alignItems.center,
    gap(unit.px(4)),
    marginInline(unit.px(6)),
    paddingInlineStart(treeVars.indent),
    radius(unit.px(5)),
    color(theme.text),
    // One vertical guide per ancestor level, drawn up to the row's depth.
    bgImage(
      gradient.repeatingLinear(unit.deg(90), [
        [transparent, unit.px(0), unit.px(TREE_INDENT_PX + 5)],
        [theme.guide, unit.px(TREE_INDENT_PX + 5), unit.px(TREE_INDENT_PX + 6)],
      ]),
    ),
    bgSize(treeVars.guides, unit.pct(100)),
    bgPosition(unit.px(1), unit.px(0)),
    backgroundRepeat.noRepeat,
    when(interaction.hover, [bg(theme.surfaceRaised)]),
    when(rowKind.folder, [fontWeight(num(600)), color(theme.textMuted)]),
    when(rowStatus.unchanged, [color(theme.textDim)]),
    when(rowStatus.moved, [color(theme.accentLink)]),
    when(rowStatus.created, [color(theme.createdText)]),
    when(rowLinked.true, [
      bg(theme.accentBg),
      shadow({
        y: unit.px(0),
        blur: unit.px(0),
        spread: unit.px(1),
        color: theme.accentBorder,
        inset: true,
      }),
    ]),
    when(rowLocated.true, [
      bg(theme.accentBg),
      shadow({
        x: unit.px(3),
        y: unit.px(0),
        blur: unit.px(0),
        color: theme.accent,
        inset: true,
      }),
    ]),
  ],
  icon: [
    display.grid,
    placeItems.center,
    inlineSize(unit.px(18)),
    blockSize(unit.px(20)),
    p(space(0)),
    borderStyle.none,
    radius(unit.px(4)),
    color(theme.textDim),
    bg(transparent),
    when(interaction.disabled, [cursor.default]),
    when(rowKind.folder, [
      cursor.pointer,
      when(interaction.hover, [bg(theme.line), color(theme.textBright)]),
    ]),
    when(rowStatus.moved, [color(theme.accentLink)]),
    when(rowStatus.created, [color(theme.createdText)]),
    when(rowStatus.deleted, [color(theme.dangerText)]),
  ],
  rowButton: [
    display.grid,
    gridTemplateColumns(
      tracks.list(tracks.minmax(unit.px(0), tracks.fr(1)), 'auto'),
    ),
    alignItems.center,
    gap(unit.px(6)),
    inlineSize(unit.pct(100)),
    minBlockSize(unit.px(24)),
    paddingBlockStart(unit.px(1)),
    paddingBlockEnd(unit.px(1)),
    paddingInlineEnd(unit.px(8)),
    borderStyle.none,
    radius(unit.px(5)),
    textAlign.start,
    cursor.pointer,
    bg(transparent),
  ],
  label: [
    clipOverflow.inline,
    textOverflow.ellipsis,
    whiteSpace.nowrap,
    when(rowStatus.deleted, [
      color(theme.dangerText),
      textDecorationLine.lineThrough,
      textDecorationColor(theme.danger),
    ]),
  ],
  status: [
    ...pill,
    px(unit.px(6)),
    fontFamily(reviewFont),
    fontWeight(num(500)),
    color(theme.textDim),
    when(rowStatus.unchanged, [display.none]),
    when(rowKind.file, [
      when(rowStatus.moved, [color(theme.accentLink), bg(theme.accentBg)]),
      when(rowStatus.created, [color(theme.createdText), bg(theme.createdBg)]),
      when(rowStatus.deleted, [color(theme.dangerText), bg(theme.dangerBg)]),
      when(rowCollision.true, [color(theme.warnText), bg(theme.warnBg)]),
    ]),
  ],
  hash: [
    marginBlock(space(0)),
    fontFamily(monospaceStack),
    fontSize(unit.px(11)),
    overflowWrap.anywhere,
    color(theme.textMuted),
  ],
});
