/**
 * The front page and the page that was not found.
 *
 * The hero is a plate: contour lines across the whole of it, a title in the
 * display size, a short promise, two or three calls to action, and the
 * botanical plate on the right. The forest stands along its foot. Below it,
 * the features sit in cards that lift a little under the pointer.
 */
import {
  alignItems,
  bg,
  borderColor,
  borderRadius,
  borderStyle,
  borderWidth,
  color,
  craftStyles,
  display,
  flexDirection,
  flexWrap,
  font,
  fontFamily,
  fontSize,
  fontStyle,
  fontWeight,
  gap,
  gridTemplateColumns,
  inlineSize,
  insetBlockStart,
  interaction,
  letterSpacing,
  lineHeight,
  lineWidth,
  marginBlock,
  marginBlockEnd,
  marginBlockStart,
  marginInline,
  maxInlineSize,
  num,
  p,
  position,
  prop,
  px,
  py,
  radii,
  shadow,
  space,
  text,
  textDecoration,
  textTransform,
  tracks,
  transitions,
  unit,
  when,
  zIndex,
  int,
  justifyContent,
  paddingBlockEnd,
} from '@craft-ts/style';
import {
  arriving,
  arrivingAfter,
  bp,
  displayFont,
  displaySize,
  duration,
  ease,
  sansFont,
  theme,
  weight,
} from '../foundation/herbier.style.ts';

export const homeUi = craftStyles('docHome', {
  hero: [
    display.block,
    position.relative,
    px(space(4)),
    py(space(12)),
    when(bp.medium, [px(space(8)), py(space(16))]),
    when(bp.wide, [px(unit.rem(2.75))]),
  ],
  heroGrid: [
    display.grid,
    position.relative,
    zIndex(int(1)),
    gap(space(8)),
    maxInlineSize(unit.rem(72)),
    marginInline.auto,
    alignItems.center,
    when(bp.wide, [
      gridTemplateColumns(
        tracks.list(tracks.minmax(space(0), tracks.fr(1)), unit.rem(16.375)),
      ),
      gap(space(12)),
    ]),
  ],
  eyebrow: [
    display.flex,
    alignItems.center,
    gap(space(3)),
    fontFamily(sansFont),
    ...font(text.xs),
    fontWeight(weight.semibold),
    letterSpacing(unit.em(0.2)),
    textTransform.uppercase,
    color(theme.link),
  ],
  title: [
    marginBlockStart(space(2)),
    fontFamily(displayFont),
    fontSize(displaySize.lead),
    lineHeight(num(0.98)),
    fontWeight(weight.medium),
    letterSpacing(unit.em(-0.035)),
    color(theme.ink),
    ...arriving,
  ],
  tagline: [
    marginBlockStart(space(5)),
    maxInlineSize(unit.rem(32)),
    fontFamily(sansFont),
    fontSize(unit.rem(1.0625)),
    lineHeight(num(1.55)),
    color(theme.inkMuted),
  ],
  actions: [
    display.flex,
    flexWrap.wrap,
    gap(space(3)),
    marginBlockStart(space(8)),
  ],
  figure: [display.block, maxInlineSize(unit.rem(16.375)), inlineSize(unit.pct(100))],
  extra: [display.block, marginBlockStart(space(5))],
  caption: [
    display.block,
    marginBlockStart(space(2)),
    fontFamily(displayFont),
    fontStyle.italic,
    ...font(text.sm),
    color(theme.inkSubtle),
  ],
  features: [
    display.grid,
    gap(space(5)),
    maxInlineSize(unit.rem(72)),
    marginInline.auto,
    px(space(4)),
    paddingBlockEnd(space(8)),
    gridTemplateColumns(tracks.autoFill(unit.rem(17.5))),
    when(bp.medium, [px(space(8))]),
    when(bp.wide, [px(unit.rem(2.75))]),
  ],
  card: [
    display.flex,
    flexDirection.column,
    gap(space(2)),
    position.relative,
    px(space(5)),
    py(space(5)),
    borderRadius(radii.md),
    borderWidth(lineWidth.hairline),
    borderStyle.solid,
    borderColor(theme.line),
    bg(theme.raised),
    color(theme.ink),
    textDecoration.none,
    ...transitions([prop.boxShadow, prop.insetBlockStart], {
      duration: duration.slow,
      easing: ease,
    }),
    ...arrivingAfter(unit.ms(150)),
    when(interaction.hover, [
      insetBlockStart(unit.px(-2)),
      shadow({ y: unit.px(14), blur: unit.px(30), color: theme.shadow }),
    ]),
  ],
  cardTitle: [
    fontFamily(displayFont),
    fontSize(unit.rem(1.3125)),
    lineHeight(num(1.2)),
    fontWeight(weight.medium),
    color(theme.ink),
  ],
  cardText: [
    p(space(0)),
    fontFamily(sansFont),
    ...font(text.sm),
    lineHeight(num(1.55)),
    color(theme.inkMuted),
  ],
  // The page that was not found: the same plate, with less to say.
  lost: [
    display.block,
    position.relative,
    px(space(4)),
    py(space(16)),
    when(bp.medium, [px(space(8)), py(space(20))]),
    justifyContent.center,
  ],
  lostBody: [
    position.relative,
    zIndex(int(1)),
    maxInlineSize(unit.rem(36)),
    marginInline.auto,
    marginBlock(space(0)),
  ],
  lostTitle: [
    marginBlockStart(space(2)),
    marginBlockEnd(space(4)),
    fontFamily(displayFont),
    fontSize(displaySize.title),
    lineHeight(num(0.98)),
    fontWeight(weight.medium),
    letterSpacing(unit.em(-0.03)),
    color(theme.ink),
  ],
  // The forest along the foot of a plate: decoration, behind the words.
  forest: [display.block, position.relative, marginBlockStart(space(8))],
});
