/**
 * The bar across the top: the name, the sections, the search, the mode switch.
 *
 * It sticks to the top while a page scrolls under it, on the page's own colour
 * so nothing shows through. Below `md` the sections leave the bar (the drawer
 * carries them) and the search shrinks to its glyph.
 */
import {
  alignItems,
  ariaCurrent,
  bg,
  blockSize,
  borderBlockEndColor,
  borderBlockEndStyle,
  borderBlockEndWidth,
  borderColor,
  borderRadius,
  borderStyle,
  borderWidth,
  color,
  craftStyles,
  cursor,
  display,
  flexGrow,
  font,
  fontFamily,
  fontWeight,
  gap,
  inlineSize,
  insetBlockEnd,
  insetBlockStart,
  insetInlineEnd,
  insetInlineStart,
  int,
  interaction,
  justifyContent,
  letterSpacing,
  lineWidth,
  marginInlineStart,
  maxInlineSize,
  num,
  paddingInlineEnd,
  paddingInlineStart,
  position,
  prop,
  pseudo,
  px,
  radii,
  set,
  space,
  text,
  textDecoration,
  transitions,
  unit,
  when,
  zIndex,
  fontSize,
  flexShrink,
} from '@craft-ts/style';
import {
  bp,
  displayFont,
  duration,
  ease,
  sansFont,
  theme,
  weight,
} from '../foundation/herbier.style.ts';

export const navbarUi = craftStyles('docNavbar', {
  root: [
    display.flex,
    alignItems.center,
    gap(space(4)),
    position.sticky,
    insetBlockStart(space(0)),
    zIndex(int(30)),
    blockSize(unit.rem(4.5)),
    px(space(4)),
    bg(theme.surface),
    borderBlockEndWidth(lineWidth.hairline),
    borderBlockEndStyle.solid,
    borderBlockEndColor(theme.line),
    when(bp.md, [px(space(8)), gap(space(8))]),
    when(bp.lg, [px(unit.rem(2.75)), gap(space(10))]),
  ],
  brand: [
    display.flex,
    alignItems.center,
    gap(space(3)),
    flexShrink(num(0)),
    color(theme.ink),
    textDecoration.none,
  ],
  mark: [
    display.flex,
    alignItems.center,
    justifyContent.center,
    inlineSize(unit.rem(2.125)),
    blockSize(unit.rem(2.125)),
    borderRadius(radii.lg),
    bg(theme.action),
    set(theme.glyph, theme.onAction),
  ],
  name: [
    fontFamily(displayFont),
    fontSize(unit.rem(1.5625)),
    fontWeight(weight.semibold),
    letterSpacing(unit.em(-0.015)),
    color(theme.ink),
  ],
  // The sections: only from `md` up. The drawer carries them below.
  links: [
    display.none,
    alignItems.center,
    gap(space(8)),
    when(bp.md, [display.flex]),
  ],
  link: [
    display.inlineBlock,
    position.relative,
    fontFamily(sansFont),
    ...font(text.sm),
    fontWeight(weight.medium),
    color(theme.inkMuted),
    textDecoration.none,
    ...transitions([prop.color], { duration: duration.fast, easing: ease }),
    when(interaction.hover, [color(theme.ink)]),
    when(ariaCurrent.page, [
      color(theme.ink),
      fontWeight(weight.semibold),
      // The mark under the current section: a second signal beside the weight.
      pseudo.after([
        pseudo.content.empty,
        position.absolute,
        insetInlineStart(space(0)),
        insetInlineEnd(space(0)),
        insetBlockEnd(unit.px(-26)),
        blockSize(lineWidth.thick),
        bg(theme.action),
      ]),
    ]),
  ],
  tools: [
    display.flex,
    alignItems.center,
    gap(space(3)),
    marginInlineStart(unit.px(0)),
    flexGrow(num(1)),
    justifyContent.flexEnd,
  ],
  // The field-shaped button that opens the search.
  search: [
    display.flex,
    alignItems.center,
    justifyContent.spaceBetween,
    gap(space(3)),
    inlineSize(unit.rem(2.375)),
    blockSize(unit.rem(2.375)),
    px(unit.rem(0.625)),
    borderRadius(radii.md),
    borderWidth(lineWidth.hairline),
    borderStyle.solid,
    borderColor(theme.lineStrong),
    bg(theme.raised),
    color(theme.inkMuted),
    fontFamily(sansFont),
    ...font(text.sm),
    cursor.pointer,
    set(theme.glyph, theme.inkMuted),
    ...transitions([prop.borderColor, prop.backgroundColor], {
      duration: duration.normal,
      easing: ease,
    }),
    when(interaction.hover, [borderColor(theme.action), bg(theme.selected)]),
    when(bp.md, [
      inlineSize(unit.rem(15.625)),
      maxInlineSize(unit.pct(100)),
      paddingInlineStart(space(4)),
      paddingInlineEnd(unit.rem(0.625)),
    ]),
  ],
  searchText: [display.none, when(bp.md, [display.inline])],
  searchKeys: [display.none, when(bp.md, [display.inline])],
  // The drawer button: only below `md`.
  menu: [display.block, when(bp.md, [display.none])],
});
