// This file is generated by tools/serve-demo.mjs. Edit app.routes.source.ts instead.
/* eslint-disable @typescript-eslint/no-unused-vars */
import { loadCraftComponent } from '@craft-ng/component';
import {
  assertExhaustiveRouteExceptions,
  craftExceptionHandler,
  craftRoute,
  craftRoutes,
  queryParams,
  type CanRun,
  type ComponentDepsOf,
  type CraftRouteExceptionType,
  type RouteCheckedDI,
} from '@craft-ng/core';
import { authGuard } from './guard/auth.guard';
import { paginationQueryParams } from './query-params.utils';

export const { demoRoutes } = craftRoutes('demo', [
  {
    path: 'craft/full-demo',
    ...loadCraftComponent(({ withRetry }) =>
      withRetry(import('./examples/craft/full-demo/full-demo')).then(
        ({ default: component }) => component,
      ),
    ),
  },
]);

export const demoEnabledRoutePaths: ReadonlySet<string> = new Set(
  demoRoutes.META_PATHS.map(({ path }) => path),
);

// Keep navigation links type-safe even when the serve prompt excludes some
// routes from the build. This slim registry is intentionally independent from
// the selected runtime collection.
type DemoRoutePath =
  | ''
  | 'query/:userId'
  | 'debounced-web-search'
  | 'slow-page'
  | 'view-transitions'
  | 'component-composition'
  | 'content-projection'
  | 'mutation/:userId'
  | 'list-with-pagination'
  | 'granular-mutation'
  | 'full-demo'
  | 'pixel-art'
  | 'pixel-art-matrix'
  | 'exceptions'
  | 'exception-query-params'
  | 'craft/query/:userId'
  | 'craft/mutation/:userId'
  | 'craft/list-with-pagination'
  | 'craft/granular-mutation'
  | 'craft/full-demo'
  | 'craft/lazy-layout/:teamId/users/:userId'
  | 'login-form'
  | 'craft-service/counter'
  | 'craft-service/register-for'
  | 'craft-service/user-detail'
  | 'demo-send-context'
  | 'playground'
  | 'query-params'
  | 'guard-demo';
type DemoRoutePaths = readonly {
  [Path in DemoRoutePath]: { path: Path };
}[DemoRoutePath][];

declare module '@craft-ng/core' {
  interface CraftRouterRoutesRegistry {
    Demo: DemoRoutePaths;
  }
}

assertExhaustiveRouteExceptions(demoRoutes);
type DemoRouteCheckedDI<
  Component,
  RouteInputs extends string = never,
  Context extends string = 'demo route component',
> = RouteCheckedDI<
  ComponentDepsOf<Component>,
  'CraftRouter' | 'CraftActivatedRoute',
  never,
  Context,
  RouteInputs
>;
type _CanRunCraftFullDemo = CanRun<
  DemoRouteCheckedDI<
    (typeof import('./examples/craft/full-demo/full-demo'))['default'],
    never,
    'path: "craft/full-demo"'
  >
>;
