/**
 * The note from the author at the foot of the home page: a portrait, a short
 * statement, a signature.
 */
import {
  alignItems,
  bg,
  blockSize,
  borderColor,
  borderRadius,
  borderStyle,
  borderWidth,
  color,
  craftStyles,
  display,
  flexShrink,
  font,
  fontFamily,
  fontSize,
  fontStyle,
  fontWeight,
  gap,
  gridTemplateColumns,
  inlineSize,
  lineHeight,
  lineWidth,
  marginBlock,
  marginInline,
  maxInlineSize,
  num,
  objectFit,
  p,
  px,
  py,
  radii,
  space,
  text,
  tracks,
  unit,
  when,
} from '@craft-ts/style';
import {
  bp,
  displayFont,
  sansFont,
  theme,
  weight,
} from '@craft-ts/docs-ui/style';

export const authorNoteUi = craftStyles('authorNote', {
  root: [
    display.grid,
    alignItems.center,
    gap(space(6)),
    maxInlineSize(unit.rem(48)),
    marginInline.auto,
    marginBlock(space(12)),
    px(space(5)),
    py(space(6)),
    borderRadius(radii.md),
    borderWidth(lineWidth.hairline),
    borderStyle.solid,
    borderColor(theme.line),
    bg(theme.raised),
    when(bp.compact, [
      gridTemplateColumns(tracks.list(unit.rem(8.25), tracks.minmax(space(0), tracks.fr(1)))),
    ]),
  ],
  frame: [
    display.block,
    flexShrink(num(0)),
    inlineSize(unit.rem(8.25)),
    blockSize(unit.rem(8.25)),
    borderRadius(radii.full),
    bg(theme.selected),
  ],
  photo: [
    display.block,
    inlineSize(unit.pct(100)),
    blockSize(unit.pct(100)),
    objectFit.cover,
    borderRadius(radii.full),
  ],
  body: [display.block, p(space(0))],
  quote: [
    display.block,
    p(space(0)),
    fontFamily(displayFont),
    fontStyle.italic,
    fontSize(unit.rem(1.1875)),
    lineHeight(num(1.45)),
    color(theme.ink),
  ],
  caption: [
    display.flex,
    gap(space(2)),
    marginBlock(space(3)),
    fontFamily(sansFont),
    ...font(text.sm),
    color(theme.inkMuted),
  ],
  name: [fontWeight(weight.semibold), color(theme.ink)],
});

