/** The template migrator of the guide: two text areas and a button between them. */
import {
  alignItems,
  bg,
  borderColor,
  borderRadius,
  borderStyle,
  borderWidth,
  color,
  craftStyles,
  cursor,
  display,
  flexDirection,
  font,
  fontFamily,
  fontWeight,
  gap,
  inlineSize,
  interaction,
  justifyContent,
  lineWidth,
  listStyleType,
  ident,
  marginBlock,
  p,
  paddingInlineStart,
  radii,
  resize,
  space,
  text,
  unit,
  when,
  px,
  py,
} from '@craft-ts/style';
import {
  monoFont,
  sansFont,
  theme,
  weight,
} from '@craft-ts/docs-ui/style';

const surface = [
  display.block,
  inlineSize(unit.pct(100)),
  px(space(3)),
  py(space(3)),
  borderRadius(radii.md),
  borderWidth(lineWidth.hairline),
  borderStyle.solid,
  borderColor(theme.lineStrong),
  bg(theme.raised),
  color(theme.ink),
  ...font(text.sm),
] as const;

export const migratorUi = craftStyles('templateMigrator', {
  root: [
    display.flex,
    flexDirection.column,
    gap(space(3)),
    marginBlock(space(6)),
    px(space(4)),
    py(space(4)),
    borderRadius(radii.md),
    borderWidth(lineWidth.hairline),
    borderStyle.solid,
    borderColor(theme.line),
    bg(theme.selected),
  ],
  label: [
    display.block,
    fontFamily(sansFont),
    ...font(text.sm),
    fontWeight(weight.semibold),
    color(theme.ink),
  ],
  area: [...surface, fontFamily(monoFont), resize.vertical],
  field: [...surface, fontFamily(sansFont)],
  toolbar: [
    display.flex,
    alignItems.center,
    justifyContent.spaceBetween,
    gap(space(4)),
  ],
  warning: [...font(text.sm), color(theme.warningInk)],
  copy: [
    px(space(4)),
    py(space(2)),
    borderRadius(radii.md),
    borderWidth(lineWidth.hairline),
    borderStyle.solid,
    borderColor(theme.action),
    bg(theme.action),
    color(theme.onAction),
    fontFamily(sansFont),
    ...font(text.sm),
    fontWeight(weight.semibold),
    cursor.pointer,
    when(interaction.hover, [bg(theme.actionHover), borderColor(theme.actionHover)]),
  ],
  diagnostics: [
    ...font(text.sm),
    color(theme.warningInk),
    paddingInlineStart(space(5)),
    listStyleType(ident('disc')),
    p(space(0)),
  ],
});
