// Generated. Do not edit.
export const architectureCatalog = {
  "version": 1,
  "graphHash": "69dffc6b188421f9",
  "routes": [],
  "services": [
    "AiContextMenuController",
    "AppSnapshotRegistry",
    "BrowserCryptoService",
    "BrowserDocumentService",
    "BrowserHistoryService",
    "BrowserLocationService",
    "BrowserNavigatorService",
    "BrowserPerformanceService",
    "BrowserWindowService",
    "CloseReview",
    "ComponentMonitoring",
    "ConsoleService",
    "CookiesService",
    "CorrelationIdService",
    "CraftA11yNavigationFocus",
    "CraftActivatedRoute",
    "CraftActiveRouteLoadError",
    "CraftBlankMs",
    "CraftChildMatch",
    "CraftCompiledRoutes",
    "CraftCspNonce",
    "CraftDomEventHooks",
    "CraftDynamicImport",
    "CraftErrorComponent",
    "CraftFieldCheckboxControl",
    "CraftFieldExceptionBoundary",
    "CraftFieldValueControl",
    "CraftGlobalError",
    "CraftGlobalErrorComponent",
    "CraftHistory",
    "CraftHttpTraces",
    "CraftHydrationRuntime",
    "CraftLazyLoadRetry",
    "CraftLoadingText",
    "CraftLocation",
    "CraftLogServerUrl",
    "CraftMatch",
    "CraftNodeEffectFactory",
    "CraftPendingComponent",
    "CraftPendingMinMs",
    "CraftPlatform",
    "CraftPrimitiveRegistry",
    "CraftRenderIdentity",
    "CraftRootComponent",
    "CraftRouteChainRunner",
    "CraftRouteLoadError",
    "CraftRouteLoadErrorComponent",
    "CraftRouteLoadErrorConfig",
    "CraftRouteLoadRecovery",
    "CraftRouteLoadRetry",
    "CraftRouteTarget",
    "CraftRoutedComponent",
    "CraftRouter",
    "CraftRouterRuntime",
    "CraftRouterTraces",
    "CraftRuntimeMode",
    "CraftSchemaValidationPolicy",
    "CraftSecurityPolicy",
    "CraftSsrPolicy",
    "CraftSsrRuntime",
    "CraftStartViewTransition",
    "CraftStayMs",
    "CraftStyleRegistry",
    "CraftSyncTemplateFlush",
    "CraftTitleStrategy",
    "CraftViewTransition",
    "CraftViewTransitionSkipBlank",
    "CraftViewTransitionsEnabled",
    "DynamicEffectRefInstance",
    "DynamicResourceInstance",
    "ForScheduler",
    "GlobalPersisterHandlerService",
    "HostName",
    "InsertionSnapshotRegistry",
    "LocalStoragePersister",
    "LocalStorageService",
    "MiddlewareExecutionScope",
    "PrimitiveMethodRuntimeContext",
    "PrimitiveResourceRuntimeObservers",
    "RetirementReasonChoice",
    "ReviewFilters",
    "ReviewPreferences",
    "SendContextChatActions",
    "SendContextChatComponent",
    "SendContextChatSections",
    "SendContextContextMenuComponent",
    "SendContextEventEnrichers",
    "SendContextEventFilters",
    "SendContextEventSources",
    "SendContextExportSections",
    "SendContextLauncherComponent",
    "SendContextRecordController",
    "SendContextRedactor",
    "SendContextRetentionPolicy",
    "SendContextSession",
    "SendContextToAiBuffer",
    "SendContextUiRenderer",
    "SendContextValueSerializer",
    "ServerFunctionTransport",
    "SessionStoragePersister",
    "SessionStorageService",
    "StoragePersister",
    "StorageService",
    "TakeAppSnapshot",
    "TemplateTraces",
    "api"
  ],
  "components": [
    "AiContextMenu",
    "AiSendContextChat",
    "AiSendContextLauncher",
    "AiSendDialog",
    "AnonymousComponent@setupCraftDirectiveTemplateTestImpl/synthetic",
    "ApplicationOverview",
    "AssetsInventoryList",
    "BypassCardEvidence",
    "BypassesView",
    "CraftRouterOutlet",
    "FilterBarActions",
    "FilterBarFields",
    "FolderLayoutView",
    "RetirementReasonPicker",
    "ReviewApp",
    "TemplateReviewGroupView",
    "ThemeLocalePicker",
    "TierLegend",
    "ViewTabs",
    "craftPending"
  ],
  "primitives": [
    "actionDisabled",
    "actions",
    "activeFilterCount",
    "activeIndex",
    "activeMentions",
    "adoptionComposition",
    "adoptionKnown",
    "adoptionRemaining",
    "adoptionSummary",
    "allSelected",
    "applicationCaptures",
    "applicationCategory",
    "applicationImage",
    "applicationNote",
    "applicationPage",
    "applicationPressed",
    "applicationScenario",
    "applicationSelection",
    "applicationStatus",
    "applicationViewport",
    "applicationZoom",
    "applyFolderLayout",
    "band",
    "busy",
    "bypassEvidence",
    "bypassRuleFilter",
    "bypasses",
    "bypassesPressed",
    "canReplay",
    "captureError",
    "captureInProgress",
    "cards",
    "changedHidden",
    "changedLabel",
    "chooseDevtoolView",
    "chooseIde",
    "chooseLocale",
    "chooseRetirementReason",
    "chooseRule",
    "chooseTheme",
    "chooseZoom",
    "chrome",
    "clearFilters",
    "closeIterationDialog",
    "closeRegenerationDialog",
    "closeReview",
    "closeReviewSession",
    "collapsedFolders",
    "componentFilter",
    "confirmFolderLayoutApply",
    "confirmIterationHandoff",
    "confirmRegeneration",
    "copied",
    "copyFolderLayoutCommand",
    "copyIterationPrompt",
    "coveredCount",
    "craftComputed",
    "current",
    "decide",
    "decideApplicationCaptures",
    "decisionFailed",
    "degraded",
    "devtoolView",
    "directionFilter",
    "dismissFolderLayoutApply",
    "error",
    "evidenceView",
    "fellBack",
    "fidelitySentence",
    "findings",
    "folderIds",
    "folderLayoutApplyCopied",
    "folderLayoutApplyDialogDismissed",
    "folderLayoutApplyDialogOpen",
    "folderLayoutEvidence",
    "folderLayoutPressed",
    "folderLayouts",
    "hasNote",
    "hiddenLegend",
    "hideChrome",
    "ide",
    "inspectApplicationCapture",
    "inspectFailed",
    "inspectFrame",
    "inspectReplay",
    "instruction",
    "iterationDialogOpen",
    "iterationHandoff",
    "iterationHandoffAvailable",
    "iterationHandoffFailed",
    "iterationHandoffReady",
    "iterationPreparationNotStarted",
    "iterationPreparationStarted",
    "iterationPromptCopied",
    "kindFilter",
    "locale",
    "member",
    "mentions",
    "moveNext",
    "movePrevious",
    "next",
    "noAgent",
    "noFiltersActive",
    "note",
    "noteState",
    "occludedHidden",
    "occludedLabel",
    "openIterationDialog",
    "openRegenerationDialog",
    "openVisualReview",
    "overlayHint",
    "overlayLabel",
    "pageProgress",
    "pages",
    "panelOffset",
    "pickedLabel",
    "previewMention",
    "previousRegenerationDecisions",
    "previousText",
    "progress",
    "promptOptions",
    "proposedRows",
    "reasonState",
    "reasonText",
    "regenerateEvidence",
    "regenerationAvailable",
    "regenerationDialogOpen",
    "regenerationFailed",
    "rejectionAttempted",
    "rejectionReasonMissing",
    "reopenDecision",
    "reopenFailed",
    "reopenReviewDecision",
    "replay",
    "replayTarget",
    "retire",
    "retirementReason",
    "reviewCards",
    "reviewDecision",
    "reviewFailed",
    "reviewNavigation",
    "reviewPressed",
    "reviewQueue",
    "root",
    "rows",
    "rules",
    "scenarios",
    "selectCard",
    "selectNodes",
    "selectVisualTest",
    "selectedCount",
    "selectedVisualAsset",
    "selectedVisualTest",
    "selection",
    "sendContextToAi",
    "sessionHistory",
    "setBusy",
    "setCaptureError",
    "setCaptureInProgress",
    "setCopied",
    "setError",
    "setPanelOffset",
    "setStatus",
    "showActions",
    "showAgentBusy",
    "showAgentFailed",
    "showBand",
    "showReject",
    "showingReplay",
    "shown",
    "sourceRows",
    "stateFilter",
    "status",
    "statusText",
    "styleAdoption",
    "subjectLabel",
    "submit",
    "summary",
    "t",
    "templateObligations",
    "templatePressed",
    "templateSource",
    "textFilter",
    "theme",
    "themeAttribute",
    "toggleChrome",
    "trackSelection",
    "trees",
    "view",
    "viewTitle",
    "viewports",
    "visible",
    "visibleSelection",
    "visualAssets",
    "visualEvidence",
    "visualPressed",
    "visualReviewCard",
    "visualTests",
    "zoom"
  ],
  "sources": [
    "clearFilters$ (source$)",
    "closeReviewRequested$ (source$)",
    "decisionReopened$ (source$)",
    "decisionSubmitted$ (source$)",
    "folderLayoutApplyRequested$ (source$)",
    "iterationDialogClosed$ (source$)",
    "iterationDialogRequested$ (source$)",
    "iterationHandoffRequested$ (source$)",
    "mentionEdited$ (source$)",
    "navigation$ (source$)",
    "regenerationConfirmed$ (source$)",
    "regenerationDialogClosed$ (source$)",
    "regenerationDialogRequested$ (source$)",
    "signalSource (signalSource)",
    "source$ (source$)"
  ],
  "serverFunctionFamilies": [],
  "httpEndpoints": [
    {
      "method": "GET",
      "url": "/api/digest/*"
    },
    {
      "method": "GET",
      "url": "/api/review"
    },
    {
      "method": "GET",
      "url": "/api/template-detail?subject=*"
    },
    {
      "method": "POST",
      "url": "/api/close-review"
    },
    {
      "method": "POST",
      "url": "/api/decisions"
    },
    {
      "method": "POST",
      "url": "/api/decisions/reopen"
    },
    {
      "method": "POST",
      "url": "/api/folder-layout/apply"
    },
    {
      "method": "POST",
      "url": "/api/iteration-handoff"
    },
    {
      "method": "POST",
      "url": "/api/regenerate"
    },
    {
      "method": "POST",
      "url": "<unresolved:ai-send-context-chat.ts:267>"
    }
  ],
  "uniques": [],
  "providers": [],
  "routeProviders": {},
  "componentProviders": {},
  "providedOn": {},
  "collisions": {
    "services": {
      "CloseReview": [
        "libs/review-attestation/attestation-app/src/close-review.service.ts",
        "libs/review-attestation/attestation-app/src/review-app.ts"
      ],
      "CraftPendingComponent": [
        "libs/component/src/lib/craft-host-tokens.ts",
        "libs/core/src/lib/craft-pending.ts"
      ],
      "MiddlewareExecutionScope": [
        "libs/core/src/lib/server-function-middleware.ts",
        "libs/core/src/lib/server-function-middleware.ts"
      ],
      "api": [
        "libs/core/src/lib/craft-register-for.ts",
        "libs/core/src/lib/craft-service.ts"
      ]
    },
    "components": {},
    "routes": {}
  },
  "browserBoundaryServices": [
    "BrowserCryptoService",
    "BrowserDocumentService",
    "BrowserHistoryService",
    "BrowserLocationService",
    "BrowserNavigatorService",
    "BrowserPerformanceService",
    "BrowserWindowService",
    "ConsoleService",
    "CookiesService",
    "LocalStorageService",
    "SessionStorageService"
  ],
  "scopes": {}
} as const;
export type ArchitectureCatalog = typeof architectureCatalog;
