// Generated. Do not edit.
export const architectureCatalog = {
  "version": 1,
  "graphHash": "7940fed70d2019c5",
  "routes": [
    "",
    "access-denied",
    "authenticated-list",
    "effect-middleware",
    "portable",
    "session-required",
    "session-revoked",
    "simple-list",
    "users-not-found"
  ],
  "services": [
    "AiContextMenuController",
    "AppSnapshotRegistry",
    "BrowserCryptoService",
    "BrowserDocumentService",
    "BrowserHistoryService",
    "BrowserLocationService",
    "BrowserNavigatorService",
    "BrowserPerformanceService",
    "BrowserWindowService",
    "ClaimedUserId",
    "ClientSession",
    "ComponentMonitoring",
    "ConsoleService",
    "CookiesService",
    "CorrelationIdService",
    "CraftA11yNavigationFocus",
    "CraftActivatedRoute",
    "CraftActiveRouteLoadError",
    "CraftBlankMs",
    "CraftChildMatch",
    "CraftCompiledRoutes",
    "CraftCspNonce",
    "CraftDomEventHooks",
    "CraftDynamicImport",
    "CraftErrorComponent",
    "CraftFieldCheckboxControl",
    "CraftFieldExceptionBoundary",
    "CraftFieldValueControl",
    "CraftGlobalError",
    "CraftGlobalErrorComponent",
    "CraftHistory",
    "CraftHttpTraces",
    "CraftHydrationRuntime",
    "CraftLazyLoadRetry",
    "CraftLoadingText",
    "CraftLocation",
    "CraftLogServerUrl",
    "CraftMatch",
    "CraftNodeEffectFactory",
    "CraftPendingComponent",
    "CraftPendingMinMs",
    "CraftPlatform",
    "CraftPrimitiveRegistry",
    "CraftRenderIdentity",
    "CraftRootComponent",
    "CraftRouteChainRunner",
    "CraftRouteLoadError",
    "CraftRouteLoadErrorComponent",
    "CraftRouteLoadErrorConfig",
    "CraftRouteLoadRecovery",
    "CraftRouteLoadRetry",
    "CraftRouteTarget",
    "CraftRoutedComponent",
    "CraftRouter",
    "CraftRouterRuntime",
    "CraftRouterTraces",
    "CraftRuntimeMode",
    "CraftSchemaValidationPolicy",
    "CraftSecurityPolicy",
    "CraftSsrPolicy",
    "CraftSsrRuntime",
    "CraftStartViewTransition",
    "CraftStayMs",
    "CraftStyleRegistry",
    "CraftSyncTemplateFlush",
    "CraftTitleStrategy",
    "CraftViewTransition",
    "CraftViewTransitionSkipBlank",
    "CraftViewTransitionsEnabled",
    "CurrentSession",
    "CurrentUser",
    "DynamicEffectRefInstance",
    "DynamicResourceInstance",
    "ForScheduler",
    "GlobalPersisterHandlerService",
    "HostName",
    "InsertionSnapshotRegistry",
    "LocalStoragePersister",
    "LocalStorageService",
    "MiddlewareExecutionScope",
    "PrimitiveMethodRuntimeContext",
    "PrimitiveResourceRuntimeObservers",
    "SendContextChatActions",
    "SendContextChatComponent",
    "SendContextChatSections",
    "SendContextContextMenuComponent",
    "SendContextEventEnrichers",
    "SendContextEventFilters",
    "SendContextEventSources",
    "SendContextExportSections",
    "SendContextLauncherComponent",
    "SendContextRecordController",
    "SendContextRedactor",
    "SendContextRetentionPolicy",
    "SendContextSession",
    "SendContextToAiBuffer",
    "SendContextUiRenderer",
    "SendContextValueSerializer",
    "ServerFunctionTransport",
    "SessionStoragePersister",
    "SessionStorageService",
    "StoragePersister",
    "StorageService",
    "TakeAppSnapshot",
    "TemplateTraces",
    "UserRepository",
    "api"
  ],
  "components": [
    "AiContextMenu",
    "AiSendContextChat",
    "AiSendContextLauncher",
    "AiSendDialog",
    "AnonymousComponent@setupCraftDirectiveTemplateTestImpl/synthetic",
    "AnonymousComponent@statusPage",
    "AppShell",
    "CraftRouterOutlet",
    "EffectServerMiddlewareDemo",
    "PortableServerFunctionDemo",
    "PublicProductsDemo",
    "ServerFunctionDemo",
    "SimpleListDemo",
    "craftPending"
  ],
  "primitives": [
    "busy",
    "captureError",
    "captureInProgress",
    "copied",
    "craftComputed",
    "currentUser",
    "currentUserQuery",
    "effectMiddlewareFilter",
    "effectMiddlewareHasServerError",
    "effectMiddlewareHasUsers",
    "effectMiddlewareIsEmpty",
    "effectMiddlewareServerError",
    "effectMiddlewareServerErrorText",
    "effectMiddlewareUsersQuery",
    "error",
    "hasProducts",
    "hasUsers",
    "instruction",
    "isAdmin",
    "isEmpty",
    "notFound",
    "notFoundMessage",
    "panelOffset",
    "portableAuditId",
    "portableHasUsers",
    "portableIsEmpty",
    "portableNormalizedFilter",
    "portableResultCount",
    "portableScannedCount",
    "portableSearchInput",
    "portableUsers",
    "portableUsersQuery",
    "productsIsEmpty",
    "productsRequestDetail",
    "productsRequestTitle",
    "productsResultCount",
    "promptOptions",
    "publicProductsQuery",
    "requestDetail",
    "requestTitle",
    "resultCount",
    "searchInput",
    "sendContextToAi",
    "setBusy",
    "setCaptureError",
    "setCaptureInProgress",
    "setCopied",
    "setError",
    "setPanelOffset",
    "setStatus",
    "status",
    "submitPortableSearch",
    "submitSearch",
    "users",
    "usersFilter",
    "usersQuery"
  ],
  "sources": [
    "signalSource (signalSource)",
    "source$ (source$)"
  ],
  "serverFunctionFamilies": [
    "demo.products.list",
    "demo.users.authenticated-list",
    "demo.users.effect-middleware-list",
    "demo.users.list",
    "demo.users.portable-list"
  ],
  "httpEndpoints": [
    {
      "method": "POST",
      "url": "<unresolved:ai-send-context-chat.ts:267>"
    }
  ],
  "uniques": [
    "\"demo.products.list\"",
    "\"demo.users.effect-middleware-list\"",
    "\"demo.users.list\"",
    "\"demo.users.portable-list\""
  ],
  "providers": [],
  "routeProviders": {},
  "componentProviders": {},
  "providedOn": {},
  "collisions": {
    "services": {
      "CraftPendingComponent": [
        "libs/component/src/lib/craft-host-tokens.ts",
        "libs/core/src/lib/craft-pending.ts"
      ],
      "CurrentSession": [
        "apps/demo-with-server-function/src/shared/authenticated-user.ts",
        "apps/demo-with-server-function/src/shared/authenticated-user.ts"
      ],
      "CurrentUser": [
        "apps/demo-with-server-function/src/shared/authenticated-user.ts",
        "apps/demo-with-server-function/src/shared/authenticated-user.ts"
      ],
      "MiddlewareExecutionScope": [
        "libs/core/src/lib/server-function-middleware.ts",
        "libs/core/src/lib/server-function-middleware.ts"
      ],
      "UserRepository": [
        "apps/demo-with-server-function/src/server/database.ts",
        "apps/demo-with-server-function/src/server/database.ts"
      ],
      "api": [
        "libs/core/src/lib/craft-register-for.ts",
        "libs/core/src/lib/craft-service.ts"
      ]
    },
    "components": {},
    "routes": {}
  },
  "browserBoundaryServices": [
    "BrowserCryptoService",
    "BrowserDocumentService",
    "BrowserHistoryService",
    "BrowserLocationService",
    "BrowserNavigatorService",
    "BrowserPerformanceService",
    "BrowserWindowService",
    "ConsoleService",
    "CookiesService",
    "LocalStorageService",
    "SessionStorageService"
  ],
  "scopes": {}
} as const;
export type ArchitectureCatalog = typeof architectureCatalog;
