/**
 * The SSR lab's whole styling: its palette, the theme on `:root`, and the
 * sheets of the shell and the pages.
 *
 * Every colour is a theme variable whose initial value is the light side of
 * the palette; dark mode is the one `when(scheme.dark)` block on `:root`, and
 * no sheet below mentions it. The reset and the good defaults (focus ring,
 * reduced motion) come from craft-ts — see `craftStyle()` in `vite.config.ts`.
 */
import {
  alignContent,
  alignItems,
  ariaCurrent,
  at,
  bg,
  blockSize,
  borderBlockEndColor,
  borderBlockEndStyle,
  borderBlockEndWidth,
  borderColor,
  borderInlineStartColor,
  borderInlineStartStyle,
  borderInlineStartWidth,
  borderStyle,
  borderWidth,
  color,
  craftGlobalStyles,
  craftStyles,
  cssVars,
  cursor,
  darkOf,
  defineBreakpoints,
  definePalette,
  defineStateAxis,
  display,
  flex,
  flexBasis,
  flexDirection,
  flexWrap,
  font,
  fontFamily,
  fontSize,
  fontStyle,
  fontWeight,
  gap,
  gridTemplateColumns,
  ident,
  inlineSize,
  interaction,
  justifyContent,
  justifyItems,
  keyframes,
  kind,
  animate,
  letterSpacing,
  lineHeight,
  lineWidth,
  listStyleType,
  marginBlockStart,
  marginInline,
  math,
  maxInlineSize,
  minBlockSize,
  minWidth,
  monospaceStack,
  num,
  opacity,
  p,
  paddingBlockEnd,
  paddingInlineStart,
  placeItems,
  px,
  py,
  radii,
  radius,
  scheme,
  set,
  shadow,
  space,
  systemUiStack,
  text,
  textAlign,
  textDecorationLine,
  textTransform,
  tracks,
  unit,
  when,
} from '@craft-ts/style';

const lab = definePalette('ssrLab', {
  surface: {
    page: { light: '#f5f7fb', dark: '#0e1422' },
    raised: { light: '#ffffff', dark: '#172033' },
    inverse: { light: '#172033', dark: '#0a0f1a' },
    highlight: { light: '#e7efff', dark: '#26324a' },
    accent: { light: '#f7faff', dark: '#1a2540' },
    step: { light: '#edf3ff', dark: '#1f2d4d' },
    quote: { light: '#fff9e9', dark: '#2e2716' },
    pending: { light: '#f8faff', dark: '#141c2e' },
    skeleton: { light: '#d5e1f4', dark: '#2a3650' },
    brandMark: { light: '#ffcf66', dark: '#ffcf66' },
    button: { light: '#3567c5', dark: '#3567c5' },
    buttonHover: { light: '#234b9b', dark: '#4a7bd6' },
    stepDot: { light: '#3567c5', dark: '#5b8be0' },
    badgeServer: { light: '#d9f0e1', dark: '#12382a' },
    badgeClient: { light: '#fff0c7', dark: '#3a2c0c' },
    badgeFallback: { light: '#eee5ff', dark: '#2c2250' },
  },
  text: {
    strong: { light: '#172033', dark: '#e6ecf5' },
    body: { light: '#56657d', dark: '#a9b6c9' },
    muted: { light: '#66758c', dark: '#8a97ab' },
    nav: { light: '#536176', dark: '#b8c5d8' },
    accent: { light: '#4466ad', dark: '#8fb0ed' },
    onInverse: { light: '#ffffff', dark: '#f1f5fb' },
    onInverseMuted: { light: '#b8c5d8', dark: '#9aa8bd' },
    serverOk: { light: '#9ee6bd', dark: '#9ee6bd' },
    onBrand: { light: '#172033', dark: '#172033' },
    onButton: { light: '#ffffff', dark: '#ffffff' },
    step: { light: '#234b9b', dark: '#a9c3f5' },
    quote: { light: '#536176', dark: '#d8c9a0' },
    badgeServer: { light: '#176b45', dark: '#8fdcb3' },
    badgeClient: { light: '#874e00', dark: '#f5c46b' },
    badgeFallback: { light: '#6346a6', dark: '#c4b0f5' },
  },
  border: {
    subtle: { light: '#dce4ef', dark: '#2a3650' },
    accent: { light: '#b7caf4', dark: '#3a4f7a' },
    step: { light: '#8fb0ed', dark: '#4a6fb5' },
    dashed: { light: '#b5c5dd', dark: '#3a4a66' },
    input: { light: '#cbd7e8', dark: '#3a4a66' },
    divider: { light: '#edf1f7', dark: '#222d42' },
    quote: { light: '#ffcf66', dark: '#c99a2e' },
  },
  effect: {
    shadow: { light: '#1720330a', dark: '#0000004d' },
  },
});

const themed = { inherits: true };

/** The theme: one variable per palette entry, light by default. */
const tone = cssVars('ssrLab', {
  page: kind.color(lab.surface.page, themed),
  raised: kind.color(lab.surface.raised, themed),
  inverse: kind.color(lab.surface.inverse, themed),
  highlight: kind.color(lab.surface.highlight, themed),
  accentSurface: kind.color(lab.surface.accent, themed),
  stepSurface: kind.color(lab.surface.step, themed),
  quoteSurface: kind.color(lab.surface.quote, themed),
  pendingSurface: kind.color(lab.surface.pending, themed),
  skeleton: kind.color(lab.surface.skeleton, themed),
  brandMark: kind.color(lab.surface.brandMark, themed),
  button: kind.color(lab.surface.button, themed),
  buttonHover: kind.color(lab.surface.buttonHover, themed),
  stepDot: kind.color(lab.surface.stepDot, themed),
  badgeServerSurface: kind.color(lab.surface.badgeServer, themed),
  badgeClientSurface: kind.color(lab.surface.badgeClient, themed),
  badgeFallbackSurface: kind.color(lab.surface.badgeFallback, themed),
  strong: kind.color(lab.text.strong, themed),
  body: kind.color(lab.text.body, themed),
  muted: kind.color(lab.text.muted, themed),
  nav: kind.color(lab.text.nav, themed),
  accent: kind.color(lab.text.accent, themed),
  onInverse: kind.color(lab.text.onInverse, themed),
  onInverseMuted: kind.color(lab.text.onInverseMuted, themed),
  serverOk: kind.color(lab.text.serverOk, themed),
  onBrand: kind.color(lab.text.onBrand, themed),
  onButton: kind.color(lab.text.onButton, themed),
  stepText: kind.color(lab.text.step, themed),
  quoteText: kind.color(lab.text.quote, themed),
  badgeServer: kind.color(lab.text.badgeServer, themed),
  badgeClient: kind.color(lab.text.badgeClient, themed),
  badgeFallback: kind.color(lab.text.badgeFallback, themed),
  border: kind.color(lab.border.subtle, themed),
  accentBorder: kind.color(lab.border.accent, themed),
  stepBorder: kind.color(lab.border.step, themed),
  dashed: kind.color(lab.border.dashed, themed),
  inputBorder: kind.color(lab.border.input, themed),
  divider: kind.color(lab.border.divider, themed),
  quoteBorder: kind.color(lab.border.quote, themed),
  shadow: kind.color(lab.effect.shadow, themed),
});

/**
 * System stacks, not web fonts: the production CSP (`font-src 'self'`) would
 * block a Google Fonts link, and a lab about the first paint should not wait
 * on a third-party origin.
 */
const body = systemUiStack;
const mono = monospaceStack;

craftGlobalStyles('ssrLab', {
  root: [
    when(scheme.dark, [
      set(tone.page, darkOf(lab.surface.page)),
      set(tone.raised, darkOf(lab.surface.raised)),
      set(tone.inverse, darkOf(lab.surface.inverse)),
      set(tone.highlight, darkOf(lab.surface.highlight)),
      set(tone.accentSurface, darkOf(lab.surface.accent)),
      set(tone.stepSurface, darkOf(lab.surface.step)),
      set(tone.quoteSurface, darkOf(lab.surface.quote)),
      set(tone.pendingSurface, darkOf(lab.surface.pending)),
      set(tone.skeleton, darkOf(lab.surface.skeleton)),
      set(tone.buttonHover, darkOf(lab.surface.buttonHover)),
      set(tone.stepDot, darkOf(lab.surface.stepDot)),
      set(tone.badgeServerSurface, darkOf(lab.surface.badgeServer)),
      set(tone.badgeClientSurface, darkOf(lab.surface.badgeClient)),
      set(tone.badgeFallbackSurface, darkOf(lab.surface.badgeFallback)),
      set(tone.strong, darkOf(lab.text.strong)),
      set(tone.body, darkOf(lab.text.body)),
      set(tone.muted, darkOf(lab.text.muted)),
      set(tone.nav, darkOf(lab.text.nav)),
      set(tone.accent, darkOf(lab.text.accent)),
      set(tone.onInverse, darkOf(lab.text.onInverse)),
      set(tone.onInverseMuted, darkOf(lab.text.onInverseMuted)),
      set(tone.stepText, darkOf(lab.text.step)),
      set(tone.quoteText, darkOf(lab.text.quote)),
      set(tone.badgeServer, darkOf(lab.text.badgeServer)),
      set(tone.badgeClient, darkOf(lab.text.badgeClient)),
      set(tone.badgeFallback, darkOf(lab.text.badgeFallback)),
      set(tone.border, darkOf(lab.border.subtle)),
      set(tone.accentBorder, darkOf(lab.border.accent)),
      set(tone.stepBorder, darkOf(lab.border.step)),
      set(tone.dashed, darkOf(lab.border.dashed)),
      set(tone.inputBorder, darkOf(lab.border.input)),
      set(tone.divider, darkOf(lab.border.divider)),
      set(tone.quoteBorder, darkOf(lab.border.quote)),
      set(tone.shadow, darkOf(lab.effect.shadow)),
    ]),
  ],
  elements: {
    body: [
      minWidth(unit.px(320)),
      fontFamily(body),
      bg(tone.page),
      color(tone.strong),
    ],
  },
});

/** Wide enough for the two-column grid and the one-line masthead. */
const bp = defineBreakpoints({ wide: at.minInlineSize(unit.rem(45)) });

/** The gutter every full-width band shares. */
const gutter = math.clamp(unit.rem(1), unit.vw(4), unit.rem(4));

const border = (tint: typeof tone.border) => [
  borderWidth(lineWidth.hairline),
  borderStyle.solid,
  borderColor(tint),
];

export const shell = craftStyles('ssrShell', {
  root: [display.block, minBlockSize(unit.vh(100))],
  masthead: [
    display.flex,
    flexDirection.column,
    alignItems.flexStart,
    justifyContent.spaceBetween,
    gap(space(4)),
    py(space(5)),
    px(gutter),
    color(tone.onInverse),
    bg(tone.inverse),
    when(bp.wide, [flexDirection.row, alignItems.center]),
  ],
  brand: [
    display.inlineFlex,
    alignItems.center,
    gap(space(3)),
    color(tone.onInverse),
    textDecorationLine.none,
  ],
  brandMark: [
    display.grid,
    inlineSize(unit.rem(2.25)),
    blockSize(unit.rem(2.25)),
    placeItems.center,
    radius(radii.xl),
    color(tone.onBrand),
    bg(tone.brandMark),
    fontWeight(num(800)),
  ],
  brandTitle: [display.block],
  brandTagline: [
    display.block,
    marginBlockStart(space(1)),
    font(text.xs),
    color(tone.onInverseMuted),
  ],
  serverIndicator: [
    display.grid,
    gap(space(1)),
    justifyItems.start,
    textAlign.start,
    font(text.xs),
    color(tone.onInverseMuted),
    when(bp.wide, [justifyItems.end, textAlign.end]),
  ],
  serverOk: [color(tone.serverOk)],
  nav: [
    display.flex,
    flexWrap.wrap,
    gap(space(2)),
    py(space(3)),
    px(gutter),
    borderBlockEndWidth(lineWidth.hairline),
    borderBlockEndStyle.solid,
    borderBlockEndColor(tone.border),
    bg(tone.raised),
  ],
  navLink: [
    py(space(2)),
    px(space(3)),
    radius(radii.full),
    font(text.xs),
    fontWeight(num(700)),
    color(tone.nav),
    textDecorationLine.none,
    when(interaction.hover, [color(tone.strong), bg(tone.highlight)]),
    when(ariaCurrent.page, [color(tone.strong), bg(tone.highlight)]),
  ],
  content: [
    maxInlineSize(unit.rem(76)),
    marginInline.auto,
    py(math.clamp(unit.rem(2), unit.vw(5), unit.rem(4.5))),
    px(gutter),
  ],
  footer: [
    display.flex,
    flexWrap.wrap,
    justifyContent.spaceBetween,
    gap(space(3)),
    px(gutter),
    paddingBlockEnd(space(6)),
    font(text.xs),
    color(tone.muted),
  ],
});

/** Which badge: server-rendered is the default, the others are states. */
export const badgeKind = defineStateAxis('ssrBadge', ['client', 'fallback']);

/** A card that carries the page's point. Drives `data-ssrCard`. */
export const cardTone = defineStateAxis('ssrCard', ['accent']);

const pulse = keyframes('ssrLabPulse', {
  '0%': [opacity(num(0.55))],
  '50%': [opacity(num(1))],
  '100%': [opacity(num(0.55))],
});

export const page = craftStyles('ssrPage', {
  root: [display.grid, gap(space(6))],
  hero: [display.grid, gap(space(2)), maxInlineSize(unit.rem(52))],
  eyebrow: [
    font(text.xs),
    fontFamily(mono),
    fontWeight(num(500)),
    letterSpacing(unit.em(0.12)),
    textTransform.uppercase,
    color(tone.accent),
  ],
  title: [
    fontSize(math.clamp(unit.rem(2), unit.vw(5), unit.rem(4))),
    lineHeight(num(1.02)),
    letterSpacing(unit.em(-0.055)),
  ],
  intro: [font(text.lg), color(tone.body)],
  grid: [
    display.grid,
    gap(space(4)),
    when(bp.wide, [gridTemplateColumns(tracks.equal(2))]),
  ],
  card: [
    display.grid,
    alignContent.start,
    gap(space(4)),
    p(math.clamp(unit.rem(1), unit.vw(3), unit.rem(1.5))),
    ...border(tone.border),
    radius(unit.rem(1)),
    bg(tone.raised),
    shadow({ y: unit.rem(0.7), blur: unit.rem(2), color: tone.shadow }),
    when(cardTone.accent, [
      borderColor(tone.accentBorder),
      bg(tone.accentSurface),
    ]),
  ],
  notFound: [justifyItems.start],
  cardTitle: [font(text.lg), fontWeight(num(700))],
  text: [color(tone.body), lineHeight(num(1.55))],
  list: [
    display.grid,
    gap(space(2)),
    paddingInlineStart(space(5)),
    listStyleType(ident('disc')),
    color(tone.body),
    lineHeight(num(1.55)),
  ],
  muted: [font(text.sm), color(tone.muted)],
  badge: [
    display.inlineFlex,
    inlineSize.fitContent,
    px(space(2)),
    py(space(1)),
    radius(radii.full),
    fontSize(unit.rem(0.68)),
    fontFamily(mono),
    fontWeight(num(500)),
    letterSpacing(unit.em(0.05)),
    textTransform.uppercase,
    color(tone.badgeServer),
    bg(tone.badgeServerSurface),
    when(badgeKind.client, [
      color(tone.badgeClient),
      bg(tone.badgeClientSurface),
    ]),
    when(badgeKind.fallback, [
      color(tone.badgeFallback),
      bg(tone.badgeFallbackSurface),
    ]),
  ],
  quote: [
    py(space(3)),
    px(space(4)),
    borderInlineStartWidth(unit.px(3)),
    borderInlineStartStyle.solid,
    borderInlineStartColor(tone.quoteBorder),
    fontStyle.italic,
    color(tone.quoteText),
    bg(tone.quoteSurface),
  ],
  button: [
    display.inlineBlock,
    inlineSize.fitContent,
    py(space(2)),
    px(space(4)),
    borderStyle.none,
    radius(radii.lg),
    fontWeight(num(700)),
    textDecorationLine.none,
    cursor.pointer,
    color(tone.onButton),
    bg(tone.button),
    when(interaction.hover, [bg(tone.buttonHover)]),
  ],
  form: [display.flex, flexWrap.wrap, alignItems.flexEnd, gap(space(2))],
  label: [flexBasis(unit.pct(100)), font(text.sm), color(tone.body)],
  input: [
    flex(num(1)),
    minWidth(unit.rem(7)),
    py(space(2)),
    px(space(3)),
    ...border(tone.inputBorder),
    radius(radii.lg),
    color(tone.strong),
    bg(tone.raised),
  ],
  metric: [display.grid, gap(space(1))],
  metricValue: [
    fontSize(unit.rem(3.3)),
    lineHeight(num(1)),
    letterSpacing(unit.em(-0.06)),
  ],
  dataList: [display.grid, gap(space(3))],
  dataRow: [
    paddingBlockEnd(space(2)),
    borderBlockEndWidth(lineWidth.hairline),
    borderBlockEndStyle.solid,
    borderBlockEndColor(tone.divider),
    color(tone.body),
  ],
  pendingBox: [
    display.grid,
    gap(space(3)),
    minBlockSize(unit.rem(5)),
    p(space(4)),
    borderWidth(lineWidth.hairline),
    borderStyle.dashed,
    borderColor(tone.dashed),
    radius(radii.xl),
    color(tone.body),
    bg(tone.pendingSurface),
  ],
  skeleton: [
    inlineSize(unit.pct(70)),
    blockSize(space(3)),
    radius(radii.full),
    bg(tone.skeleton),
    animate(pulse, { duration: unit.s(1.4), iterations: 'infinite' }),
  ],
});

export const pipeline = craftStyles('ssrPipeline', {
  root: [
    display.flex,
    flexWrap.wrap,
    gap(space(2)),
    marginBlockStart(space(4)),
    p(space(0)),
    listStyleType.none,
  ],
  step: [
    display.inlineFlex,
    alignItems.center,
    gap(space(2)),
    py(space(1)),
    px(space(3)),
    ...border(tone.stepBorder),
    radius(radii.full),
    font(text.xs),
    color(tone.stepText),
    bg(tone.stepSurface),
  ],
  dot: [
    display.grid,
    inlineSize(unit.rem(1.3)),
    blockSize(unit.rem(1.3)),
    placeItems.center,
    radius(radii.full),
    fontFamily(mono),
    fontWeight(num(500)),
    color(tone.onButton),
    bg(tone.stepDot),
  ],
});
